### PR TITLE
Trigger extending import only when the item is not in scope

### LINKED ISSUE #1308: Auto extend import list in some needless cases
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 0.9.0.0 (GHC: 8.10.3) (PATH: /home/berberman/.cabal/store/ghc-8.10.3/haskell-language-server-0.9.0.0-8f2c9238aa6456c28366c2c5b74966c6998aac099da88e4737c3be342793b2b1/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:          3.2.0.0
stack:          Not found
ghc:            8.10.3
```
Which lsp-client do you use:
vscode

### Steps to reproduce
Create B.hs:

```haskell

module B where

data K = K

```

Re-export `B` in A.hs:

```haskell

module A (module B) where

import B

```

Then import `A` in Test.hs (the import declaration of module `B` is prior to that of module `A`):

```haskell

module Test where

import B ()
import A

foo = _

```

Type `K` in the type hole.

### Expected behaviour

`K` has already been brought into scope by `A`, so we don't need extend the import list of `B`.

```haskell

module Test where

import B ()
import A

foo = K

```

### Actual behaviour

Peek

### Extra information

The same thing happens to `Prelude` as well:

Peek

### PR DESCRIPTION
**Pull request by berberman**
Closes #1308

Not sure if this will have significant impact on performance...

### CODE REVIEW

**Review by konn — COMMENTED** [review]
Seems plausible to me, but I'm not so familiar with caching and benchmarking things to be honest, I would want to wait @pepeiborra to double-check this PR.

File: ghcide/src/Development/IDE/Plugin/Completions.hs [hunk 1]
```diff
@@ -77,10 +77,11 @@ produceCompletions = do
...
               -- We do this to be able to provide completions of items that are not restricted to the explicit list
               res <- liftIO $ tcRnImportDecls env (dropListFromImportDecl <$> imps)
-              case res of
-                  (_, Just rdrEnv) -> do
+              inScope <- liftIO $ tcRnImportDecls env imps
+              case (res, inScope) of
+                  ((_, Just rdrEnv), (_, Just inScopeEnv)) -> do
                       let uri = fromNormalizedUri $ normalizedFilePathToUri file
-                      cdata <- liftIO $ cacheDataProducer uri env (ms_mod ms) rdrEnv imps parsedDeps
+                      cdata <- liftIO $ cacheDataProducer uri env (ms_mod ms) rdrEnv inScopeEnv imps parsedDeps
```
Comment (pepeiborra) [inline ghcide/src/Development/IDE/Plugin/Completions.hs:84]: rather than passing both `inScopeEnv` and `rdrEnv`, is there any way to pass just the difference?

**Comment by pepeiborra** [comment]
To check the performance impact, wait until the Bench jobs are completed, download the artifacts, and look for `completions after edit.svg`

**Comment by pepeiborra** [comment]
The benchmarks look good, there is no noticeable impact in performance

File: ghcide/src/Development/IDE/Plugin/Completions.hs (hunk 1 above)
Comment (berberman) [reply ghcide/src/Development/IDE/Plugin/Completions.hs]: Thanks for your suggestion! I was going to use IntMap.merge, but I realized that `UniqFM` behind `OccEnv` is opaque. Since we don't need keys (`OccName`s) in `cacheDataProducer`, I extract elements and then use `getDiff` to mark if it's in scope.

File: ghcide/src/Development/IDE/Plugin/Completions.hs [hunk 2]
```diff
@@ -77,10 +79,19 @@ produceCompletions = do
...
                       let uri = fromNormalizedUri $ normalizedFilePathToUri file
-                      cdata <- liftIO $ cacheDataProducer uri env (ms_mod ms) rdrEnv imps parsedDeps
+                          globalElts = globalRdrEnvElts globalEnv
+                          inScopeElts = globalRdrEnvElts inScopeEnv
+                          diff = getDiff globalElts inScopeElts
+                          go (First x : xs) ys = go xs $ (x, False) : ys
+                          go (Second x : xs) ys = go xs $ (x, True) : ys
+                          go (Both x _ : xs) ys = go xs $ (x, True) : ys
+                          go [] ys = ys
+                          rdrElts = go diff []
```
Comment (Ailrun) [inline ghcide/src/Development/IDE/Plugin/Completions.hs:93]: do we need to reverse the `diff` list? If not, why don't you use `map` instead?

Comment (berberman) [reply ghcide/src/Development/IDE/Plugin/Completions.hs:93]: Thanks, `map` should work here. I switched to `map`, which means the list is reversed back to positive order, and then I found the tests failed. This reveals a bug in code that we should not use `Eq` instance of `GlobalRdrElt`, because it compares not only `gre_name`, but `gre_imp` as well. However we don't want to compare this, since a same element in `globalEnv` and `inScopeEnv` may not have the same `gre_imp` (they are brought into scope in different ways), for example:

```
ZeroPad: fst | ZeroPad parent:FormatAdjustment
  imported from ‘Text.Printf’ at /run/user/1000/extra-dir-46668153349363/A.hs:2:1-42
ZeroPad: snd | ZeroPad parent:FormatAdjustment
  imported from ‘Text.Printf’ at /run/user/1000/extra-dir-46668153349363/A.hs:2:21-41
```

So it becomes clear that the order of the list affects the result.

File: ghcide/src/Development/IDE/Plugin/Completions.hs [hunk 3]
```diff
@@ -77,10 +79,18 @@ produceCompletions = do
...
-              case res of
-                  (_, Just rdrEnv) -> do
+              inScope <- liftIO $ tcRnImportDecls env imps
+              case (res, inScope) of
+                  ((_, Just globalEnv), (_, Just inScopeEnv)) -> do
                       let uri = fromNormalizedUri $ normalizedFilePathToUri file
-                      cdata <- liftIO $ cacheDataProducer uri env (ms_mod ms) rdrEnv imps parsedDeps
+                          globalElts = globalRdrEnvElts globalEnv
+                          inScopeElts = globalRdrEnvElts inScopeEnv
+                          diff = getDiffBy (\GRE {gre_name = nameA} GRE {gre_name = nameB} -> nameA == nameB) globalElts inScopeElts
```
Comment (Ailrun) [inline ghcide/src/Development/IDE/Plugin/Completions.hs:88]: Minor suggestion: how about
```suggestion
                          diff = getDiffBy ((==) `on` gre_name) globalElts inScopeElts
```

**Review by Ailrun — APPROVED** [review]
LGTM :)

File: ghcide/src/Development/IDE/Plugin/Completions.hs [hunk 4]
```diff
@@ -77,10 +79,18 @@ produceCompletions = do
...
+                          rdrElts = flip map diff $ \case
+                            First x -> (x, False)
+                            Second x -> (x, True)
+                            Both x _ -> (x, True)
```
Comment (pepeiborra) [inline ghcide/src/Development/IDE/Plugin/Completions.hs:92]: Let's roll this back, benchmarks show that this diff computation is rather expensive.
Sorry, I didn't realise that `OccEnv a` doesn't provide any means of taking the set of keys.

This is a local benchmark, where:

HEAD: f8c796f112a9680db6ab85a68d7bd592c5a9dc7e
no-diff: e2067a365c863a00d31f2f66432d25a2219c007b

```
diff --git a/ghcide/bench/config.yaml b/ghcide/bench/config.yaml
index 25cf4080..43b1675b 100644
--- a/ghcide/bench/config.yaml
+++ b/ghcide/bench/config.yaml
@@ -62,5 +62,6 @@ versions:
 # - ghcide-v0.7.1
 # - ghcide-v0.7.2
 # - ghcide-v0.7.3
+- no-diff: e2067a365c863a00d31f2f66432d25a2219c007b
 - HEAD
(END)
```

image

File: ghcide/src/Development/IDE/Plugin/Completions.hs [hunk 5]
```diff
@@ -77,10 +79,18 @@ produceCompletions = do
               let env = hscEnv sess
               -- We do this to be able to provide completions of items that are not restricted to the explicit list
               res <- liftIO $ tcRnImportDecls env (dropListFromImportDecl <$> imps)
-              case res of
-                  (_, Just rdrEnv) -> do
+              inScope <- liftIO $ tcRnImportDecls env imps
```
Comment (pepeiborra) [inline ghcide/src/Development/IDE/Plugin/Completions.hs:82]: Can we compute these two in parallel using something like https://hackage.haskell.org/package/async-2.2.2/docs/Control-Concurrent-Async.html#v:concurrently ?

**Review by pepeiborra — APPROVED** [review]
Thanks for this fix!
