### PR TITLE
Send unhandled exceptions to the user

### LINKED ISSUE #2390: Report error conditions via LSP message dialogs
Fatal errors that do not show up in diagnostics should be handled an LSP `WindowShowMessage` including a short description of the error together with a link to the HLS docs and issue tracker. 

The poster example would be GHC<->HLS version mismatches.

### PR DESCRIPTION
**Pull request by pepeiborra**
Closes #2390

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2484"></a>

### CODE REVIEW

File: ghcide/src/Development/IDE/LSP/LanguageServer.hs [hunk 1]
```diff
@@ -137,48 +139,49 @@ runLanguageServer options inH outH getHieDbLoc defaultConfig onConfigurationChan
...
                     exitClientMsg
                 handleServerException _ = pure ()
+
+                uncaughtError (e :: SomeException) = do
+                    logError logger $ T.pack $
+                        "Unexpected exception on notification, please report!\n" ++
+                        "Exception: " ++ show e
+                    LSP.runLspT env $ LSP.sendNotification SWindowShowMessage $
+                        ShowMessageParams MtError $ T.unlines
+                        [ "Unhandled error, please [report](" <> issueTrackerUrl <> "): "
```
Comment (michaelpj) [inline ghcide/src/Development/IDE/LSP/LanguageServer.hs:153]: I don't believe this is supposed to support markup, it's not a `MarkedString`.

File: ghcide/src/Development/IDE/LSP/LanguageServer.hs [hunk 2]
```diff
@@ -137,48 +139,49 @@ runLanguageServer options inH outH getHieDbLoc defaultConfig onConfigurationChan
...
             let handleServerException (Left e) = do
-                    logError (ideLogger ide) $
+                    logError logger $
                         T.pack $ "Fatal error in server thread: " <> show e
                     exitClientMsg
                 handleServerException _ = pure ()
+
+                uncaughtError (e :: SomeException) = do
+                    logError logger $ T.pack $
+                        "Unexpected exception on notification, please report!\n" ++
```
Comment (michaelpj) [inline ghcide/src/Development/IDE/LSP/LanguageServer.hs:149]:
```suggestion
                        "Unexpected exception or notification, please report!\n" ++
```

Comment (michaelpj) [reply ghcide/src/Development/IDE/LSP/LanguageServer.hs:149]: Generally, is there a reason why the log message and the window message are different here?

File: ghcide/src/Development/IDE/LSP/LanguageServer.hs [hunk 3]
```diff
@@ -137,48 +139,49 @@ runLanguageServer options inH outH getHieDbLoc defaultConfig onConfigurationChan
             registerIdeConfiguration (shakeExtras ide) initConfig
 
             let handleServerException (Left e) = do
-                    logError (ideLogger ide) $
+                    logError logger $
```
Comment (michaelpj) [inline ghcide/src/Development/IDE/LSP/LanguageServer.hs:142]: Should we be sending a message here too?

**Review by michaelpj — APPROVED** [review]

File: ghcide/src/Development/IDE/LSP/LanguageServer.hs (hunk 1 above)
Comment (pepeiborra) [reply ghcide/src/Development/IDE/LSP/LanguageServer.hs:153]: VSCode supports some basic markup, see https://github.com/microsoft/vscode/issues/20595#issuecomment-281099832
I expect other clients to support it, and if not, everyone can read markdown :)

File: ghcide/src/Development/IDE/LSP/LanguageServer.hs (hunk 2 above)
Comment (pepeiborra) [reply ghcide/src/Development/IDE/LSP/LanguageServer.hs:149]: This function is called from multiple places, not just the notification handler.

File: ghcide/src/Development/IDE/LSP/LanguageServer.hs (hunk 3 above)
Comment (pepeiborra) [reply ghcide/src/Development/IDE/LSP/LanguageServer.hs:142]: No, since that will result in double notifications being sent, notice the `finally` in `checkCancelled`. 

I'll take the chance to clean it up

Comment (pepeiborra) [reply ghcide/src/Development/IDE/LSP/LanguageServer.hs:142]: Nevermind, `checkCancelled` doesn't propagate exceptions, so we should be sending a message here too indeed

File: ghcide/src/Development/IDE/LSP/LanguageServer.hs (hunk 1 above)
Comment (michaelpj) [reply ghcide/src/Development/IDE/LSP/LanguageServer.hs]: Ugh, this stupid poorly-specified protocol :roll_eyes:

**Review by michaelpj — APPROVED** [review]

**Comment by jneira** [comment]
The test suite for tactics has failed twice for windows 8.10.7, with different test error cases, not sur if it will be transient

**Comment by Anton-Latukha** [comment]
Recent failed test builds were:
`pepeiborra` - https://github.com/haskell/haskell-language-server/runs/4513326877?check_suite_focus=true
`AntonLatukha` - https://github.com/haskell/haskell-language-server/runs/4527885363?check_suite_focus=true
`jneira` - https://github.com/haskell/haskell-language-server/runs/4530467808?check_suite_focus=true

**Comment by pepeiborra** [comment]
The last failure is due to the old sqlite3 hiedb problem, not something specific to this change. We have a ticket for it somewhere, but I am on my phone right now and can't look. 

We have a couple of sources of flakiness, and I would appreciate if someone would find the time to look into the hiedb one. Why is it getting triggered? Is the test suite   running tests in parallel?

```
SQLite3 returned ErrorBusy while attempting to perform step: database is locked\n",

```

**Comment by pepeiborra** [comment]
Added code to stop the hiedb on shutdown. Might or might not help

File: ghcide/src/Development/IDE/LSP/LanguageServer.hs [hunk 4]
```diff
@@ -57,11 +58,16 @@ runLanguageServer
...
-    -- LSP loop will be canceled when it's full.
+    -- LSP server will be canceled when it's full.
     clientMsgVar <- newEmptyMVar
     -- Forcefully exit
     let exit = void $ tryPutMVar clientMsgVar ()
 
+    -- An MVar to control the lifetime of the reactor loop.
+    -- The loop will be stopped and resources freed when it's full
+    reactorLifetime <- newEmptyMVar
+    let stopReactorLoop = void $ tryPutMVar reactorLifetime ()
```
Comment (michaelpj) [inline ghcide/src/Development/IDE/LSP/LanguageServer.hs:69]: Why `tryPutMVar`? So it doesn't block? Shouldn't we at least return the bool and log something in the shutdown handler if it fails to shutdown the reactor?

File: ghcide/src/Development/IDE/LSP/LanguageServer.hs [hunk 5]
```diff
@@ -57,11 +58,16 @@ runLanguageServer
 runLanguageServer options inH outH getHieDbLoc defaultConfig onConfigurationChange userHandlers getIdeState = do
 
     -- This MVar becomes full when the server thread exits or we receive exit message from client.
-    -- LSP loop will be canceled when it's full.
+    -- LSP server will be canceled when it's full.
     clientMsgVar <- newEmptyMVar
     -- Forcefully exit
     let exit = void $ tryPutMVar clientMsgVar ()
```
Comment (michaelpj) [inline ghcide/src/Development/IDE/LSP/LanguageServer.hs:64]: and tbh ditto here

File: ghcide/src/Development/IDE/LSP/LanguageServer.hs [hunk 6]
```diff
@@ -190,15 +194,22 @@ runLanguageServer options inH outH getHieDbLoc defaultConfig onConfigurationChan
             pure $ Right (env,ide)
 
 
+-- | Runs the action until it ends or until the given MVar is put.
+--   Rethrows any exceptions.
+untilMVar :: MonadUnliftIO m => MVar () -> m () -> m ()
```
Comment (michaelpj) [inline ghcide/src/Development/IDE/LSP/LanguageServer.hs:199]: Kind of surprised these sorts of utilities aren't available elsewhere. I couldn't find them, anyway.

Comment (michaelpj) [reply ghcide/src/Development/IDE/LSP/LanguageServer.hs:199]: Especially the pattern of forking a thread with an MVar to control terminating it :thinking:

**Review by michaelpj — APPROVED** [review]

File: ghcide/src/Development/IDE/LSP/LanguageServer.hs (hunk 4 above)
Comment (pepeiborra) [reply ghcide/src/Development/IDE/LSP/LanguageServer.hs:69]: Why? So that it can be called twice (not that we depend on that)
Not sure which bool you have in mind.
The reactor is guaranteed to be killed, and it has an exception handler attached (which hopefully should only capture non-async exceptions)

File: ghcide/src/Development/IDE/LSP/LanguageServer.hs (hunk 6 above)
Comment (pepeiborra) [reply ghcide/src/Development/IDE/LSP/LanguageServer.hs:199]: They may exist, I'm not sure either.

File: ghcide/src/Development/IDE/LSP/LanguageServer.hs (hunk 4 above)
Comment (pepeiborra) [reply ghcide/src/Development/IDE/LSP/LanguageServer.hs:69]: We already log a "Received shutdown message", that's good enough for me

**Comment by michaelpj** [comment]
The windows jobs seemed to be hanging (stuck for 4h). I attempted to cancel them but it's unclear that it's worked.

**Comment by michaelpj** [comment]
... how did that work?

**Comment by jneira** [comment]
> ... how did that work?

it should not 😕
the test post-jobs was supposed to be cancelled but it was not
https://github.com/haskell/haskell-language-server/runs/4549724494?check_suite_focus=true

**Comment by michaelpj** [comment]
I _think_ this might be making the ghcide tests hang on windows. I think we should revert it until we can confirm.

**Comment by jneira** [comment]
> I _think_ this might be making the ghcide tests hang on windows. I think we should revert it until we can confirm.

well i have a pr fixing the cancelling thing and including this pr, if its tests are not stuck it would be fine

**Comment by jneira** [comment]
pr in my fork with this reverted https://github.com/jneira/haskell-language-server/pull/56

**Comment by jneira** [comment]
Ok the pr in my fork with this reverted has passed the ghcide tests: https://github.com/jneira/haskell-language-server/runs/4559275575?check_suite_focus=true
I am gonna open here
