### PR TITLE
 Doctest comment parsing using module annotations in Eval Plugin

### LINKED ISSUE #1214: HLS version 0.8.0 frequently stuck when saving files
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 0.8.0.0 (GHC: 8.10.3) (PATH: /nix/store/px0cwk7xl79yq4b1pvkwaxfkwaswhis1-haskell-language-server-0.8.0.0/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		Not found
ghc:		8.10.3
```
Which lsp-client do you use:
vscode
Describe your project (alternative: link to the project):
cabal project
Contents of `hie.yaml`:
implicit hie

### Steps to reproduce
I'm not sure how to reproduce this issue reliably, but it seems that this issue comes up a lot more frequently when I'm editing a file that has errors (type errors/parse errors, etc.) in it.

### Expected behaviour
HLS should not stuck

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

<details>
<summary>
Debug output:
</summary>

```
<paste your logs here>
```
</details>

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
LSP logs:
</summary>

```
<paste your logs here>
```
</details>

### LINKED ISSUE #1258: Token parse error on {-# UNPACK #-}
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:
```sh
haskell-language-server version: 0.8.0.0 (GHC: 8.6.5) (PATH: /home/flix/.config/Code/User/globalStorage/haskell.haskell/haskell-language-server-0.8.0-linux-8.6.5) (GIT hash: eb58f13f7b8e4f9bc771af30ff9fd82dc4309ff5)
Tool versions found on the $PATH
cabal:		2.4.1.0
stack:		2.5.1
ghc:		8.0.2
```
Which lsp-client do you use: VSCode
Describe your project (alternative: link to the project): https://github.com/yesodweb/wai/blob/master/warp/Network/Wai/Handler/Warp/Request.hs#L212
Contents of `hie.yaml`: none

### Expected behaviour
Should just parse the .hs file.

### Actual behaviour
HLS fails to process the file. (`Request.hs`, see link to project)

### Include debug information

<details>
<summary>
LSP logs:
</summary>

```
haskell-language-server-0.8.0-linux-8.6.5: Tokens.next failed to parse     {-# UNPACK #-} !Int -- running total byte count (excluding current header chunk) Parser did not consume entire stream, left: "!Int -- running total byte count (excluding current header chunk)"
CallStack (from HasCallStack):
  error, called at src/Ide/Plugin/Eval/Parse/Token.hs:134:19 in hls-eval-plugin-0.1.0.0-inplace:Ide.Plugin.Eval.Parse.Token
```
</details>

### PR DESCRIPTION
**Pull request by konn**
This PR aims at rewriting existing custom comment parser in Eval plugin with `getParsedModuleWithComments`, which is introduced recently.
This should address #1214, #1231 and #1258.

closes #1214, closes #1258

### CODE REVIEW

**Comment by konn** [comment]
I think it's done for line comments (not blocks yet), and it seems that the infinite loop occurring when one toggles block comments, as described in #1214, seems gone with the current change.

**Comment by konn** [comment]
Hmm, also `plugins/hls-eval-plugin/README.rm` states that Multiline expressions are supported, there seem no implementation and test cases for it. I decided just to ignore this feature in this PR.

**Comment by konn** [comment]
Fmm, I assume that `Opt_Haddock` is disabled in `getParsedModuleWithComments`, but it seems it is.
Then, we have to decide the style (block or line) of comments corresponding to `AnnDocCommentNext`, `AnnDocCommentPrev` and `AnnDocCommentNamed`.
I couldn't find the information to decide their style, does anyone has knowledge of them, or we have to decide it by just scanning the corresponding final segments of range from editor buffer and see whether it ends with `-}` or not?

**Comment by jneira** [comment]
and what about disable haddock for getPsrsedModuleWithComents?

**Comment by konn** [comment]
> and what about disable haddock for getPsrsedModuleWithComents?

Yes, it must be the easiest way to try!
I'm not sure if other plugins using `getParsedModuleWithComments` (e.g. HLint) work as previous. Let me try disabling Opt_Haddock and see how CI result changes.

**Comment by jneira** [comment]
In fact when i wrrte the rule i was about to disable haddock, but as hlint worked without doing it i decided to let is as is now

**Comment by konn** [comment]
To comply with the current Eval Plugin behaviour, I decided to limit the indentation level to be processed as Eval command so that:

- In ordinary `.hs`:  indent level must be 0
- Literate Haskell: Indent Level must be 1

This doesn't cover modules with the base indentation level strictly greater than those specified above, though it might rarely occur.
Since the objective of this PR is just to replace the existing comment parser, such improvements deserve another PR.

**Comment by konn** [comment]
Hmm. It is rather annoying that func-test for Eval Plugin won't run at all on my laptop, with a bunch of the following exceptions:

```zsh
Exception: Received an exepected error in a response for id IdRspInt 1:
      ResponseError {_code = InternalError, _message = "BadDependency \"GetParsedModuleWithComments\"", _xdata = Nothing}
```

Eval Plugin itself seems running correctly on my laptop and in CI it at least starts to evaluate expressions. I think this kinda odd behaviour of tests occurs when I implemented the Splice Plugin, even if  I set `HLS_TEST_EXE` to full-path to the HLS exe, which results in just push and pray for CI passes.
Perhaps am I missing something?

**Comment by konn** [comment]
Eval Plugin on the master branch doesn't allow block comment in a single line like this:

```haskell
{- >>> "IGNORED" -}
```

But rejecting this case increases the complexity of parser implementation, and it is likely that users generally expect them to work, I decided to allow such case in this PR.

**Comment by konn** [comment]
OK, tests essentially passed, but we need to wait a second between executing commands consecutively to avoid staled insertion range makes makes false-positive.
Since such miss-insertion due to staled location info persists through the history of Eval Plugin, so this might be considerably reasonable solution.

**Comment by konn** [comment]
OK, test code assumes that commands in lens are sorted in order; new implementation violates this implicit invariant.
Although it doesn't affect the user experience, I changed to comply this behaviour to make CI happy.

**Comment by konn** [comment]
Hmm. Eval plugin with CPP on Windows seems to fail... It must be due to CRLF, but I have no idea why modules without CPP works without CRLF but fails with CPP. I don't have a handy access to Windows environment, so, well, it is hard to debug...

**Comment by konn** [comment]
Since I have no mean to debug on Windows, I would rather label CPP Eval test-case as `expected failure` on Windows env and let someone to fix that issue later. I think it is now ready for Review.

File: plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Types.hs [hunk 1]
```diff
@@ -62,22 +79,61 @@ hasTests :: Section -> Bool
...
-    | Property {testline :: Txt, testOutput :: [Txt]}
+    = Example {testLines :: NonEmpty Txt, testOutput :: [Txt], testRange :: Range}
+    | Property {testline :: Txt, testOutput :: [Txt], testRange :: Range}
     deriving (Eq, Show, Generic, FromJSON, ToJSON, NFData)
 
+data Comments = Comments
+    { lineComments :: Map Range RawLineComment
+    , blockComments :: Map Range RawBlockComment
+    }
+    deriving (Show, Eq, Ord, Generic)
```
Comment (Ailrun) [inline plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Types.hs:97]: Out of curiosity, does this work well with nested comments?

Comment (konn) [reply plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Types.hs:97]: Ah, I've never thought of such a situation.

It seems that if the eval line isn't placed right before the end of the inner ending brace, it seems work:

nested-space

But if it is placed right before the inner closing brace, it will break the output (as it is considered as a result line literally saying `-}` and get replaced with evaluation result):

nested-no-space

It seems that old parser can handle both cases correctly, so it might be desirable to support such a case in this PR.
I think we don't have to maintain nesting level but suffices to treat line solely consisting of `-}` or `{-` and white spaces as a delimiting empty line in block comment contexts.

Indeed, there can be (somewhat pathological) cases that `-}` can appear as an evaluation result, e.g:

```hs
data EndingBrace = EndingBrace
instance Show EndingBrace where
  showsPrec _ = const $ showString "-}"

{-
>>> EndingBrace
-}
```

But this already breaks block comment eval line regardless of special treatment of `-}`-line, so mentioned special treatment of non-terminating `-}` and `{-` would suffice, I think.

Comment (Ailrun) [reply plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Types.hs:97]: Thank you for the detailed investigation. How does the `doctest` tool work on `EndingBrace` case? It would be more safe to say "stable" if we can follow their practice, since their practice has a much longer history than the Eval plugin.

Comment (konn) [reply plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Types.hs:97]: > It would be more safe to say "stable" if we can follow their practice, since their practice has a much longer history than the Eval plugin.

Agreed. But we have to mind the major difference between Eval and doctest that the former has the functionality to evaluate line and insert to the source code, `doctest` does evaluation but just compares the result to existing contents following the test-line.

As for nested comments, `doctest` seems to ignore any eval inside nested block comments (of nesting level >= 2).
As for EndingBrace, it just tries to compare the newly-computed value with the existing one.
And doctest seems to treat escaped inputs such as `-\}` as-is, so it seems there is no way to check the validity of outputs containing `-}`.

That said, `EndingBrace` is just a corner-case and it seems such a case rarely comes up in practice.
If one has to use Eval Plugin to inspect output containing `-}`, they can use one-line comments instead anyway (plus some attention to configure code formatters not to convert them into multiline comments). So I think just ignoring nested `-}` makes sense in this case.

Comment (Ailrun) [reply plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Types.hs:97]: > That said, EndingBrace is just a corner-case and it seems such a case rarely comes up in practice.

It indeed looks it's the case. Thank you for fixing this parser hazard!

**Comment by konn** [comment]
Since current goldenTest in Eval Plugin cannot handle eval lines in separate-groups but in the same section, I separate two blocks in the new test case into two separate two blocks.
It seems that the first commit to change it passed CI, but the second commit merging master into this topic branch seems stuck due to the [recent degraded availability for GitHub Actions](https://www.githubstatus.com/incidents/tf9v5jjmq2lg?utm_ts=1611807667).

**Comment by konn** [comment]
Hmm, CI fails unexpected exception in seemingly unrelated module... why?

**Comment by Ailrun** [comment]
There is an issue with `eval` test: https://github.com/haskell/haskell-language-server/issues/1228.
HLS maintainers need to restart it several times...

**Comment by Ailrun** [comment]
IDK why, but now it passes all.

File: plugins/hls-eval-plugin/test/Eval.hs [hunk 2]
```diff
@@ -147,15 +150,25 @@ tests =
...
                 liftIO $ do
                     let mdl = "TLastLine.hs"
                     -- Write the test file, to make sure that it has no final line return
-                    writeFile (evalPath </> mdl) $ "module TLastLine where\n\n-- >>> take 3 [1..]"
+                    writeFile (evalPath </> mdl) "module TLastLine where\n\n-- >>> take 3 [1..]"
                     goldenTest mdl
 #if __GLASGOW_HASKELL__ >= 808
-            , testCase "CPP support" $ goldenTest "TCPP.hs"
+            ,
+#if mingw32_HOST_OS
```
Comment (jneira) [inline plugins/hls-eval-plugin/test/Eval.hs:168]: Maybe we could add a dedicated function to mark tests broken for windows like https://github.com/haskell/haskell-language-server/blob/master/test/utils/Test/Hls/Util.hs#L119
We can use `extra` function `isWindows`: https://hackage.haskell.org/package/extra-1.7.9/docs/System-Info-Extra.html#v:isWindows

File: plugins/hls-eval-plugin/test/Eval.hs [hunk 3]
```diff
@@ -147,15 +150,25 @@ tests =
...
+            $ goldenTest "TNested.hs"
         , testCase "Test on last line insert results correctly" $ do
             runSession hlsCommand fullCaps evalPath $
                 liftIO $ do
                     let mdl = "TLastLine.hs"
                     -- Write the test file, to make sure that it has no final line return
-                    writeFile (evalPath </> mdl) $ "module TLastLine where\n\n-- >>> take 3 [1..]"
+                    writeFile (evalPath </> mdl) "module TLastLine where\n\n-- >>> take 3 [1..]"
                     goldenTest mdl
 #if __GLASGOW_HASKELL__ >= 808
```
Comment (jneira) [inline plugins/hls-eval-plugin/test/Eval.hs:166]: In a similar spirit we could use `ignoreForGhcVersions ` or `knownBrokenForGhcVersions` instead raw cpp conditions

File: plugins/hls-eval-plugin/test/Eval.hs (hunk 2 above)
Comment (jneira) [reply plugins/hls-eval-plugin/test/Eval.hs:168]: Anyway i will try to take a look in my local windows env

File: plugins/hls-eval-plugin/test/Eval.hs (hunk 3 above)
Comment (konn) [reply plugins/hls-eval-plugin/test/Eval.hs]: Thank you for your suggestions! I've just switched to `knownBrokenForGhcVersions` and implement `knownBrokenOnWindows`. Now CPP disappears from func-test for eval!

**Review by jneira — APPROVED** [review]
Looks good to me, and tests are the evidence it improves the actual situation.
I would like to have some other approve before merge though.

File: plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Comments.hs [hunk 4]
```diff
@@ -0,0 +1,576 @@
...
+        doesn't include starting @--@ and @{\-@ and no ending @-\}@
+
+    *   Line comment group parser: parses a contiguous group of
+        tuples of position and line comment into sections of line comments.
+        Each input MUST start with @--@.
+
+    *   Block comment parser: Parsing entire block comment into sections.
+        Input must be surrounded by @{\-@ and @-\}@.
+-}
+type Parser inputs = Parsec Void inputs
```
Comment (Ailrun) [inline plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Comments.hs:68]: It looks like this function is not reused anywhere except `LineGroupParser` definition and `parseLine`. Do we need this?

File: plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Option.hs [hunk 5]
```diff
@@ -24,10 +21,13 @@ Right []
...
 
--- >>> runParser languageOpts ":set -XBinaryLiterals -XOverloadedStrings"
--- Right ["BinaryLiterals","OverloadedStrings"]
-languageOpts :: Parser Char [[Char]]
-languageOpts = string ":set" *> many (many space *> string "-X" *> many letterChar)
+-- >>> parseMaybe languageOpts ":set -XBinaryLiterals -XOverloadedStrings"
+-- Just ["BinaryLiterals","OverloadedStrings"]
+languageOpts :: Parsec Void String [String]
+languageOpts = string ":set" *> space1
+  *> many (string "-X" *> many letterChar <* space)
```
Comment (Ailrun) [inline plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Option.hs:33]: This does not support, for example, `Rank2Types`, right? Is this intentional?

Comment (konn) [reply plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Option.hs:33]: This code remains the same as old Extended Eval Plugin, except switched to use Megaparsec as a parsing backend. That is to say, this is so regardless of my intension from the start and already exists in the current master. Anyway, yes, I think we must use GHC's flag parser (if exists) to allow more flags of form e.g. `-fprint-explicit-foralls` etc.

File: plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Comments.hs (hunk 4 above)
Comment (konn) [reply plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Comments.hs:68]: I suppose you are talking about 'Parser` *synonym*, right?
If so, yes, this could be eliminated. Thanks!

File: plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs [hunk 6]
```diff
@@ -310,7 +308,9 @@ evalCommandName = "evalCommand"
 evalCommand :: PluginCommand IdeState
 evalCommand = PluginCommand evalCommandName "evaluate" runEvalCmd
 
--- |Specify the test section to execute
+-- | Specify the test section to execute
+--
+-- >>> 12
```
[the remark this answers is not in the document]
Comment (konn) [reply plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs:313]: Ooops, that was accidentaly. Thanks!

File: plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs [hunk 7]
```diff
@@ -25,258 +26,255 @@ module Ide.Plugin.Eval.CodeLens (
...
-                -- dbg "PREPROCESSED CONTENT" text
+                (ParsedModule{..}, posMap) <- liftIO $
+                    runAction "parsed" st $ useWithStale_ GetParsedModuleWithComments nfp
+                let comments = foldMap
+                        ( foldMap (\case
+                            L (RealSrcSpan real) bdy
+                                | unpackFS (srcSpanFile real) ==
+                                    fromNormalizedFilePath nfp ->
+                                    let ran0 = realSrcSpanToRange real
+                                        curRan = fromMaybe ran0 $ toCurrentRange posMap ran0
```
[the remark this answers is not in the document]
Comment (konn) [reply plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs:244]: OK, I will make it fail if `toCurrentRange` was `Nothing`

File: plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Comments.hs (hunk 4 above)
Comment (Ailrun) [reply plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Comments.hs:68]: Sorry, yes. I meant the type synonym.

File: plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Option.hs (hunk 5 above)
Comment (Ailrun) [reply plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Option.hs:33]: Aha, thank you for the explanation.

**Review by Ailrun — APPROVED** [review]
I think it's in a good shape.
