### PR TITLE
ghcide: Implements a CodeAction to disambiguate ambiguous symbols

### LINKED ISSUE #1274: Exactprint-based import list modification introduces extra newline when there is at least one newline between the module header and the topmost import
As found in PR #1264, it seems that exactprint-based import list modification seems to introduce an extra newline in certain situation.
Bisecting it in the master branch, this behaviour is first introduced in eb557b3efc9ea3ca7516a19d761dd5cb9d2ad882.

### Steps to reproduce

1. Checkout eb557b3efc9ea3ca7516a19d761dd5cb9d2ad882 and build ghcide the binary and make sure your LSP client will use it as a language server executable.
2. Save the following as `Lib.hs`:

    ```hs
    module Lib where

    import Data.Vector ()

    theFun = fromList
    ```

    Make sure there is at least one newline between the module header and the import declaration; otherwise this bug won't occur.
3. Open `Lib.hs` and wait for the module to be loaded.
4. Apply `Add fromList to Data.Vector` code action.

### Expected behaviour
`fromList` is added to the import list, without any modification to the lines except for import list itself, resulting in:

 ```hs
module Lib where

import Data.Vector (fromList)

theFun = fromList
```

### Actual behaviour
An extra newline added between the module header and the import declaration:

 ```hs
module Lib where


import Data.Vector (fromList)

theFun = fromList
```

Note that there are two blank lines in-between instead of just one.

### PR DESCRIPTION
**Pull request by konn**
This PR aims at automating the disambiguation of import lists with the following options:

* Hide all the imports except the chosen module
* Make ambiguous symbol qualified
  - Currently, if two colliding modules have the same qualified name, the resulting code can still have ambiguous occurrence, though.

This PR fixes #1274: it calls `setEntryDPT (DP (0,0))` at the end of `rewriteToEdits`.

## DEMO
disamb-import-demo

### CODE REVIEW

**Comment by konn** [comment]
Hmm, it seems annotation transfer doesn't go well and error is occurring at the call of `tail` in `rewriteToEdit`, making HLS clash when colliding symbol is detected...

**Comment by pepeiborra** [comment]
> I think naïve implementation is done; now I want to write functional/golden tests. Where should I place the ghcide-related functional tests?
> 

Thank you! The ghcide test suite is all one big module: `ghcide/test/exe/Main.hs`

**Comment by konn** [comment]
OK, before implementing tests, it somehow became working!

disamb

But it seems that combining multiple Rewrites into one adds unnecessary lines over the import list.
Although it doesn't pose a functional issue, it is more desirable to retain lines...

**Comment by berberman** [comment]
I think `extendHiding` closely resembles `extendImport`. They both process `Located [LIE pass]` similarly, and the only difference might be the `Bool` value, the first item of `ideclHiding`.

**Comment by konn** [comment]
> I think `extendHiding` closely resembles `extendImport`. They both process `Located [LIE pass]` similarly, and the only difference might be the `Bool` value, the first item of `ideclHiding`.

Yeah, indeed `extendHiding` is derived from `extendImportToplevel`. Major difference is that we have to insert `AnnHiding` annotation before open parens when there is no `hiding` clause before.
Another difference is that extendImports accepts new imported symbol with parens when they are infix operato, while extendHiding without parens. This difference comes from the slight difference of how problematic identifier is reported in `undefined identifier` and `ambiguous imports` error.

Other difference is just a matter of preference: 'extendHiding` adds new hidden symbol at the start while extendImportToplevel at end.

Yes, these differences can be abstracted away and we can unify two functions. But I didn't do that because their usage and purpose differ slightly and can cause some confusion. Still, there can be some refactoring to factor out common operations as separate functions, as you pointed out.

**Comment by berberman** [comment]
You are right, I've ignored `AnnHiding` XD

For parens, I think it was #1212 that made identifiers parenthesized before stored into `ExportsMap`, so I didn't treate them specially in extending imports. A little bit off-topic: IMHO It would be better to handle parens right here, because on the one hand, functions to extend hiding and imports could behave consistently; on the other hand, afaik diagnostics reported for extending imports don't parenthesize operators, and we don't insert rendered text but operate AST to make sure that they are parenthesized correctly, so there is no need to parenthesize them in exports map.  In this case `unIEWrappedName` can be removed, and as you said, further refactor might be smoother because of the unification.

**Comment by konn** [comment]
It turns out that multiple import list isn't a direct cause of an additional newline at the top.
A new line will be added when some identifier is removed from the import lists in the topmost import declaration.
I couldn't figure out why this phenomenon occurs, though...

**Comment by konn** [comment]
Hmm, this behaviour seems to exist in any code base modifying import lists using functionality in `Development.IDE.Plugin.CodeAction.ExactPrint`: new *extend imports* functionality rewritten using ghc-exactprint presents the same behaviour adding redundant lines:

new-line-import

Note that I've tested this with the current master (1ebd374), which doesn't include this PR.
@berberman @pepeiborra @alanz Do you have any idea?

**Comment by pepeiborra** [comment]
I'm not seeing this @konn, and the test suite isn't seeing it either. Have you tried to bisect it?

**Comment by konn** [comment]
> I'm not seeing this @konn, and the test suite isn't seeing it either. Have you tried to bisect it?

Hmm, strange. OK, I'll try to locate the root commit.

**Comment by konn** [comment]
After bisection, it seems that eb557b3efc9ea3ca7516a19d761dd5cb9d2ad882 is the root commit for this behaviour in my environment.
Tested against `ghcide` binary built with stack 2.5.1 + GHC 8.8.4 on macOS.

**Comment by konn** [comment]
Ah, it seems that precondition is slightly more involved: we need an extra newline between the module header and the topmost import declaration, as fourmolu automatically does.

For example

```hs
module Lib where

import Data.Vector ()

theFun = fromList
```

will become:

```hs
module Lib where


import Data.Vector (fromList)

theFun = fromList
```

But:

```hs
module Lib where
import Data.Vector ()

theFun = fromList
```

becomes

```hs
module Lib where
import Data.Vector (fromList)

theFun = fromList
```

**Comment by konn** [comment]
As all the import suggestion test places no extra newline between the module header and the first import declaration, this problem has not been detected by unit-tests.

**Comment by konn** [comment]
As this behaviour seems to exist before this PR, I will make another issue to track this issue.

**Comment by konn** [comment]
OK, I think I have reached the point that can be used.
It cannot detect the distinction between expression- and type-operators yet, but the situation is the same as other import-related suggestions.

File: ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs [hunk 1]
```diff
@@ -298,3 +309,97 @@ unqalDP paren =
...
+                L lieL $ IEThingWith xt ty wild
+                  (filter ((/= symbol) . rawIEWrapName . unLoc) cons)
+                  (filter ((/= symbol) . unpackFS . flLabel . unLoc) flds)
+        killLie v = Just v
+
+-- This must not belong here?
+rawIEWrapName :: IEWrappedName RdrName -> String
+rawIEWrapName (IEName (L _ nam)) = occNameString $ rdrNameOcc nam
+rawIEWrapName (IEPattern (L _ nam)) = occNameString $ rdrNameOcc nam
+rawIEWrapName (IEType (L _ nam)) = occNameString $ rdrNameOcc nam
```
Comment (pepeiborra) [inline ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs:405]: isn't this just `prettyPrint`?

File: ghcide/test/exe/Main.hs [hunk 2]
```diff
@@ -1464,6 +1476,106 @@ suggestImportTests = testGroup "suggest import actions"
...
+    Range ->
+    Session [CAResult]
+waitForAtLeatOneAction wait count doc range = go count []
+    where
+        go !remain !acc = do
+            liftIO $ sleep wait
+            actions <- getCodeActions doc range
+            if not (null actions) || remain <= 0
+                then pure $ acc ++ actions
+                else go (remain - 1) (acc ++ actions)
```
Comment (pepeiborra) [inline ghcide/test/exe/Main.hs:1577]: Are you sure that we need this? 

I believe that ghcide currently returns all the code actions at the same time

The only case where a recursive call would ever be needed is if a test is expecting too many code actions. This will cause an unnecessary delay and go undetected, slowing down the test suite forever

File: ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs (hunk 1 above)
Comment (konn) [reply ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs:405]: Yes, it must be equivalent to `prettyPrint` on `OccName`. One difference is that if we apply `prettyPrint` directly to `IEWrappedName`, then we have some modifiers added around identifiers. e.g.

```hs
>>> import Development.IDE.GHC.Util
>>> prettyPrint (Unqual $ mkVarOcc "++")
"++"

>>> prettyPrint $ IEType $ L (UnhelpfulSpan "<input>") $ Unqual $ mkVarOcc "++"
"type (++)"
```

Another difference is that we need unqualified names here. If we apply `prettyPrint` to `RdrName`, we get, e.g.

```
-- >>> prettyPrint $ Qual (mkModuleName "Bar") $ mkVarOcc "++"
-- "Bar.++"
```

Hence we need to strip IEWrapping and qualifiers here.

File: ghcide/test/exe/Main.hs (hunk 2 above)
Comment (konn) [reply ghcide/test/exe/Main.hs:1577]: This was not at first introduced. But it seems some test-cases introduced in this PR, especially `Use AVec for Vec, hiding other imports` and `Use EVec for Vec, ...`, continually fail in CI complaining that `Found no matching actions for "Use AVec for Vec, hiding other imports" in []` (see, for example [this log](https://github.com/haskell/haskell-language-server/runs/1797000004?check_suite_focus=true)).
Once I tried to increase `sleep` duration from `0.5` to `1.0`, `1.5` and then `2.0`. But it still fails by accident.
I can, of course, increase sleep duration further, but it also introduces additional overhead to other tests related to disambiguation actions.

Hence, I decided to call `getCodeActions` repeatedly until any action becomes available.
It can be the case that some bug is accidentally introduced and no code action is generated, so I limit the number of retries. This is the intention of this hack.

Comment (pepeiborra) [reply ghcide/test/exe/Main.hs:1577]: The problem is that `waitForDiagnostics` doesn't wait for *all* the diagnostics.
You need to wait for diagnostics on the source file where you expect the code action.
Use `expectDiagnostics` instead

File: ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs (hunk 1 above)
Comment (pepeiborra) [reply ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs:405]: you can use `showNameWithoutUniques` which will remove the qualifiers, or you can create your own render style

File: ghcide/src/Development/IDE/Plugin/CodeAction.hs [hunk 3]
```diff
@@ -29,30 +49,21 @@ import Development.IDE.Plugin.TypeLenses (suggestSignature)
...
-import Bag (isEmptyBag)
-import qualified Data.HashSet as Set
-import Control.Concurrent.Extra (readVar)
-import Development.IDE.GHC.Util (printRdrName)
-import Ide.PluginUtils (subRange)
-import Ide.Types
+import Text.Regex.TDFA (mrAfter, (=~), (=~~))
+import Data.Either (fromRight)
+import Retrie (unpackFS)
+import FieldLabel (flLabel)
```
Comment (pepeiborra) [inline ghcide/src/Development/IDE/Plugin/CodeAction.hs:66]: Could you minimise the change to the imports? Otherwise it's guaranteed to generate painful conflicts for other PRs

File: ghcide/src/Development/IDE/Plugin/CodeAction.hs [hunk 4]
```diff
@@ -96,18 +107,48 @@ codeAction lsp state _ (TextDocumentIdentifier uri) _range CodeActionContext{_di
...
-          , (title, graft) <- suggestExactAction exportsMap dynflags ps x
-          , Right edit <-
-                [ -- either (Left . traceShow) Right $
-                 rewriteToEdit dynflags uri (annsA ps) graft
-                 ]
+          , (title, grafts) <- suggestExactAction exportsMap dynflags ps x
+          , let edit = foldMapBy unionWSEdit mempty (either error id .
+                        rewriteToEdit dynflags uri (annsA ps)) grafts
+          ] ++
+          [mkCA title [x] edit
```
Comment (pepeiborra) [inline ghcide/src/Development/IDE/Plugin/CodeAction.hs:114]: Isn't there any way to package `suggestImportDisambiguation` inside `suggestExactAction`? 
As seen in #1273 it is strongly preferable to for all the code action "providers" to have a compatible signature, so that they can be reordered easily

File: ghcide/src/Development/IDE/Plugin/CodeAction.hs (hunk 3 above)
Comment (konn) [reply ghcide/src/Development/IDE/Plugin/CodeAction.hs:66]: Ah, I applied code-formatter restricted to the import list, but it seems it introduced so much unnecessary change...

File: ghcide/src/Development/IDE/Plugin/CodeAction.hs [hunk 5]
```diff
@@ -705,6 +746,167 @@ suggestExtendImport exportsMap (L _ HsModule {hsmodImports}) Diagnostic{_range=_
...
+        in [Left $ TextEdit _range
+            $ T.pack $ showSDoc df
+            $ parenSymOcc occSym
+            $ ppr rdr]
+
+-- Couldn't make out how to add New imports by ghc-exactprint;
+-- using direct TextEdit instead.
+hidePreludeSymbol :: DynFlags -> String -> ParsedSource -> TextEdit
+hidePreludeSymbol df symbol (L _ HsModule{..}) =
+    let ran = fromJust $ srcSpanToRange $ getLoc $ last hsmodImports
```
Comment (pepeiborra) [inline ghcide/src/Development/IDE/Plugin/CodeAction.hs:901]: `ImportDecl` has an `ASTElement` instance, so you should be able to parse the new import using `parseAST` and then insert it in the list of imports. Or did you try that already?

File: ghcide/src/Development/IDE/Plugin/CodeAction.hs [hunk 6]
```diff
@@ -96,18 +107,48 @@ codeAction lsp state _ (TextDocumentIdentifier uri) _range CodeActionContext{_di
...
     pure $ Right $ List actions''
 
+-- | Semigroup instance just overrides duplicated keys in the first argument
+unionWSEdit :: WorkspaceEdit -> WorkspaceEdit -> WorkspaceEdit
+unionWSEdit (WorkspaceEdit a b) (WorkspaceEdit c d) =
+    -- FIXME: Want to use monoidal-containers, but it supports aeson <1.5 only...
+    WorkspaceEdit (runCatHashMap <$> fmap CatHashMap a <> fmap CatHashMap c)
+        (b <> d)
+
+newtype CatHashMap k v = CatHashMap { runCatHashMap :: Map.HashMap k v }
```
Comment (pepeiborra) [inline ghcide/src/Development/IDE/Plugin/CodeAction.hs:146]:
```suggestion
    WorkspaceEdit (runCatHashMap <$> fmap CatHashMap a <> fmap CatHashMap c)
        (b <> d)

-- | A monoidal hashmap
     -- FIXME: Want to use monoidal-containers, but it supports aeson <1.5 only...
newtype CatHashMap k v = CatHashMap { runCatHashMap :: Map.HashMap k v }
```

File: ghcide/src/Development/IDE/Plugin/CodeAction.hs (hunk 4 above)
Comment (konn) [reply ghcide/src/Development/IDE/Plugin/CodeAction.hs:111]: I first did so, but some AST manipulation failed with ghc-exactprint so I decided to make it return `[Either TextEdit Rewrite]`. If we could rewrite the code solely by ghc-exactprint, I will be happy to package it into `suggestExactAction`, which was my first attempt.

File: ghcide/src/Development/IDE/Plugin/CodeAction.hs (hunk 5 above)
Comment (konn) [reply ghcide/src/Development/IDE/Plugin/CodeAction.hs:898]: I once tried to insert Prelude hiding by ghc-exactprint, but get stuck.
I think we must append or prepend `import Prelude hiding  (...)` to the `hsmodImports`, but I couldn't figure out how.
I've first try to return `[LImportDecl GhcPs]` in `Rewrite`, but this won't compile because `[LImportDecl GhcPs]` was not an `ASTElement`.

File: ghcide/src/Development/IDE/Plugin/CodeAction.hs (hunk 6 above)
Comment (konn) [reply ghcide/src/Development/IDE/Plugin/CodeAction.hs]: Thanks!

File: ghcide/test/exe/Main.hs (hunk 2 above)
Comment (konn) [reply ghcide/test/exe/Main.hs]: Thank you for your suggestion! I've just switched to `expectDiagnostics` and changed code to open documents in separate isolated directory. Everything works fine 😄

File: ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs (hunk 1 above)
Comment (konn) [reply ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs]: It seems that `showNameWithoutUniques` doesn't remove qualifier, only Uniques generated by GHC. Anyway, it gives the expected result on OccName, and returning type is Text, so I decided to use `showNameWithoutUniques` inside `rawIEWrapName` and move to `Development.IDE.Spans.Common.unqualIEWrapName`.

File: ghcide/src/Development/IDE/Plugin/CodeAction.hs (hunk 5 above)
Comment (konn) [reply ghcide/src/Development/IDE/Plugin/CodeAction.hs:901]: Ah, I misunderstood the purpose of `Rewrite`; it doesn't do any AST replacement, but do some replacement against the range in the sourcode with the generated AST element, right? Then I think I can find a way. Thanks!

Comment (pepeiborra) [reply ghcide/src/Development/IDE/Plugin/CodeAction.hs:901]: Yup

Comment (konn) [reply ghcide/src/Development/IDE/Plugin/CodeAction.hs:901]: Hmm. I could generate a single line of an import declaration, but couldn't make out how to prepend or append extra newlines at the level of `Rewrite`...

Comment (konn) [reply ghcide/src/Development/IDE/Plugin/CodeAction.hs:901]: ... Aha! I forgot that I added `stripPrecedingNewlines` as a tentative solution. Everything works fine if one switches to `setEntryDPT`-based approach.

Comment (konn) [reply ghcide/src/Development/IDE/Plugin/CodeAction.hs]: OK, I rewrote `hidePreludeSymbol` using `Rewrite` somehow (much more complicated than the `TextEdit` version, though...), moved it to ExactPrint module.

File: ghcide/src/Development/IDE/Plugin/CodeAction.hs (hunk 4 above)
Comment (konn) [reply ghcide/src/Development/IDE/Plugin/CodeAction.hs]: I finally reunite `suggestImportDisambiguation` into `suggestExactAction`. Thank you!

File: ghcide/src/Development/IDE/Plugin/CodeAction.hs [hunk 7]
```diff
@@ -705,6 +731,155 @@ suggestExtendImport exportsMap (L _ HsModule {hsmodImports}) Diagnostic{_range=_
...
+            -- I don't find this particularly comprehensible,
+            -- but HLint suggested me to do so...
+        (ideclHiding <&> \(isHiding, L _ ents) ->
+            let occurs = any ((symbol `symbolOccursIn`) . unLoc) ents
+            in isHiding && not occurs || not isHiding && occurs
+        )
+occursUnqualified _ _ = False
+
+symbolOccursIn :: T.Text -> IE GhcPs -> Bool
+symbolOccursIn symb = \case
```
Comment (berberman) [inline ghcide/src/Development/IDE/Plugin/CodeAction.hs:835]: Can we use `ieNames` here to avoid case splitting?

File: ghcide/src/Development/IDE/Spans/Common.hs [hunk 8]
```diff
@@ -52,6 +54,12 @@ showNameWithoutUniques = T.pack . prettyprint
     prettyprint x = renderWithStyle dyn (ppr x) style
     style = mkUserStyle dyn neverQualify AllTheWay
 
+-- | Shows IEWrappedName, without any modifier, qualifier or unique identifier.
+unqualIEWrapName :: IEWrappedName RdrName -> T.Text
+unqualIEWrapName (IEName (L _ nam)) = showNameWithoutUniques $ rdrNameOcc nam
+unqualIEWrapName (IEPattern (L _ nam)) = showNameWithoutUniques $ rdrNameOcc nam
+unqualIEWrapName (IEType (L _ nam)) = showNameWithoutUniques $ rdrNameOcc nam
```
Comment (berberman) [inline ghcide/src/Development/IDE/Spans/Common.hs:61]:
```suggestion
unqualIEWrapName = showNameWithoutUniques . rdrNameOcc . ieWrappedName
```

File: ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs [hunk 9]
```diff
@@ -298,3 +295,113 @@ unqalDP paren =
...
+            | nam == symbol = Nothing
+            | otherwise = Just $
+                L lieL $ IEThingWith xt ty wild
+                  (filter ((/= symbol) . unqualIEWrapName . unLoc) cons)
+                  (filter ((/= symbol) . T.pack . unpackFS . flLabel . unLoc) flds)
+        killLie v = Just v
+
+hideImplicitPreludeSymbol
+    :: String -> ParsedSource -> Rewrite
+hideImplicitPreludeSymbol symbol (L _ HsModule{..}) =
```
Comment (berberman) [inline ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs:389]: I think it would be better to make this a total function.

Comment (konn) [reply ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs:389]: Sorry, I couldn't understand the suggestion. Isn't it already total? GHC didn't show any warning at least on my env.

File: ghcide/src/Development/IDE/Spans/Common.hs (hunk 8 above)
Comment (konn) [reply ghcide/src/Development/IDE/Spans/Common.hs]: Thanks!

File: ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs (hunk 9 above)
Comment (berberman) [reply ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs:389]: Ah, I mean is it possible to avoid using partial functions from Prelude, e.g. `last` or `fromJust`?

Comment (konn) [reply ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs:389]: Ah, I got it. I think the use of `last` is safe under the assumption that there must be at least one import decl already. As for `fromJust`... I'm not sure. If the module is an unsaved virtual one, it could be `Nothing`? Or such cases are rejected by the absence of `NormalizedFilePath`?

**Comment by konn** [comment]
OK, as the resolution of the conflict with `master`, I decided to address #1274 in this PR, following the workaround suggested by @pepeiborra and @berberman.
One difference from @pepeiborra's solution is that we invoke `setEntryDPT` in `rewriteToEdit`, not in `rewrite`; this is intended to keep implementation details and necessary procedure in a single module, say `Development.IDE.Plugin.CodeAction.ExactPrint`. This is to avoid a similar procedure scattered over several modules.

File: ghcide/src/Development/IDE/Plugin/CodeAction.hs [hunk 10]
```diff
@@ -694,6 +711,143 @@ suggestExtendImport exportsMap (L _ HsModule {hsmodImports}) Diagnostic{_range=_
...
+            ++ mconcat
+                [ if null imps
+                    then [hideImplicitPreludeSymbol symbol pm]
+                    else hideSymbol symbol <$> imps
+                | ImplicitPrelude imps <- hiddens0
+                ]
+    (ToQualified qualMod) ->
+        let occSym = mkVarOcc symbol
+            rdr = Qual qualMod occSym
+        in [Rewrite (rangeToSrcSpan nfp _range) $ \df -> do
```
Comment (berberman) [inline ghcide/src/Development/IDE/Plugin/CodeAction.hs:846]: Do we really need `nfp` here? Our final goal is `TextEdit`, which requires `Range`. `srcSpanToRange` in `rewriteToEdit` will drop the file name, so I think it should be OK to pass a dummy value.

Comment (konn) [reply ghcide/src/Development/IDE/Plugin/CodeAction.hs:846]: Good catch. Thanks!

**Comment by konn** [comment]
Hmm, it seems `addConstraint` tests start to fail... I will look into.

**Comment by konn** [comment]
OK, now it passes tests for constraint manipulation.

File: ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs (hunk 9 above)
Comment (konn) [reply ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs]: OK, I've made `hideImplicitPreludeSymbol` total by returning `Maybe` value instead and ignores Prelude rewrite if it returns Nothing. Thank you for your suggestion!

**Comment by konn** [comment]
I think this PR reached a stable state after merging current master's change.

**Review by berberman — APPROVED** [review]
LGTM, thank you for this awesome work!

**Comment by konn** [comment]
Not so important, but I've just added DEMO GIF to the summary.
