### PR TITLE
Fix Completion document format

### LINKED ISSUE #683: Completion provenance for local definition is Just ModuleName instead of just ModuleName
To reproduce:

Create the following module:

```haskell
module Foo
  where

bar = ()

foo = ba
```

- Trigger completion for `ba`
- Observe that the provenance of `bar` is `Just Foo` instead of just `Foo`

image

### PR DESCRIPTION
**Pull request by July541**
This pr contributes to repairing broken markdown format in completion documents, and close #683 since this bug does not exist.

The function `spanDocToMarkdown` is both used in completion and hover, hover looks well, let's look at the tests.

Here are some comparations:

---

### Scenario 1
old1
new1

---

### Scenario 2
old2
new2

---

### Scenario 3
old3
new3

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2848"></a>

### CODE REVIEW

File: ghcide/test/exe/Main.hs [hunk 1]
```diff
@@ -5230,6 +5231,87 @@ projectCompletionTests =
...
+  , broken $ testSession "extern mulit line doc" $ do
+      doc <- createDoc "A.hs" "haskell" $ T.unlines
+        [ "module A where"
+        , "foo = i"
+        ]
+      let expected = "*Imported from 'Prelude'*\n* * *\n\n\nIdentity function. \n```haskell\nid x = x\n```\n* * *\n[Documentation](file:"
+      test doc (Position 1 7) "id" (Just $ T.length expected) [expected]
+  ]
+  where
+    broken = knownBrokenForGhcVersions [GHC90, GHC92] "Completion doc doesn't support ghc9"
```
Comment (michaelpj) [inline ghcide/test/exe/Main.hs:5301]: :o do we have a ticket for this?

File: ghcide/src/Development/IDE/Spans/Common.hs [hunk 2]
```diff
@@ -77,12 +79,19 @@ emptySpanDoc :: SpanDoc
...
-spanDocToMarkdown (SpanDocText txt uris) = txt <> ["\n"] <> spanDocUrisToMarkdown uris
+spanDocToMarkdown = \case
+    (SpanDocString docs uris) ->
+        let doc = T.pack $ haddockToMarkdown $ H.toRegular $ H._doc $ H.parseParas Nothing $ unpackHDS docs
+        in  go [doc] uris
+    (SpanDocText txt uris) -> go txt uris
+  where
+    go [] uris = spanDocUrisToMarkdown uris
+    go txt uris = init txt <> [render (last txt)] <> spanDocUrisToMarkdown uris
+    -- If the doc is not end with an `'\n'`, we append it.
```
Comment (michaelpj) [inline ghcide/src/Development/IDE/Spans/Common.hs:90]: This logic is a bit confusing, because we have a collection of lines, some of them ending with newlines. The old comment *is* correct, we do need two newlines to get a paragraph break in markdown, but that works out here because `T.unlines [ "foo\n", "bar" ]` will end up with two newlines. Confusing. 

In fact, should the lines _ever_ have trailing newlines? That seems odd.

I wonder if it would be simpler if this function just dealt with a single `Text` representing the whole piece of doc. AFAICT it would be fine if `spanDocToMarkdown` returned just a `Text`.

File: ghcide/test/exe/Main.hs (hunk 1 above)
Comment (July541) [reply ghcide/test/exe/Main.hs:5301]: No, I just found this https://github.com/haskell/haskell-language-server/blob/da0379b78caff2a3bc72e08b97b9f608fe73d50e/ghcide/src/Development/IDE/Spans/Documentation.hs#L104-L122

, ghc9.0 test fails on my machine, so I marked it as broken

File: ghcide/src/Development/IDE/Spans/Common.hs (hunk 2 above)
Comment (July541) [reply ghcide/src/Development/IDE/Spans/Common.hs:90]: 1. Two newlines to get a new paragraph is correct, but one `\n` is enough to get a section separator(xxx\n***\nxxx)
2. My idea is: we just ensure the last line should end up with `\n`, so the separator can rendered correctly. https://github.com/haskell/haskell-language-server/blob/da0379b78caff2a3bc72e08b97b9f608fe73d50e/ghcide/src/Development/IDE/Plugin/Completions/Logic.hs#L211-L213

Comment (July541) [reply ghcide/src/Development/IDE/Spans/Common.hs:90]: >I wonder if it would be simpler if this function just dealt with a single Text representing the whole piece of doc. AFAICT it would be fine if spanDocToMarkdown returned just a Text.

Unfortunately, `spanDocToMarkdown` is both used in completion and hover, and they have different UI(completion uses section separator, hover uses new line), so we can't return a `Text` in `spanDocToMarkdown`. Furthermore, the final documentation is the combination of `Defined in`, haddock, and source link.

Comment (pepeiborra) [reply ghcide/src/Development/IDE/Spans/Common.hs:90]: Does it return a list of sections then? Please add a Haddock comment clarifying what `spanDocToMarkdown` returns

File: ghcide/test/exe/Main.hs (hunk 1 above)
Comment (pepeiborra) [reply ghcide/test/exe/Main.hs:5301]: Note that this code path is only used to get documentation for local completions (from the same module). I dont' think that it is being used in your test.

Are you in Mac OS? Some ghc 9.x distributions are shipping without interface haddocks

**Comment by July541** [comment]
Failure reason:
- windows-ghc9.2 can't deal local doc (ubuntu-ghc9.2 works fine)
- ubuntu-ghc9.0 can't deal local doc

I'll remove local doc test instead of just testing whether the defined doc(`Defined at`) ends with '\n', it weakens the test power:(

File: ghcide/src/Development/IDE/Spans/Common.hs (hunk 2 above)
Comment (July541) [reply ghcide/src/Development/IDE/Spans/Common.hs]: Done

**Comment by July541** [comment]
> Failure reason:
> 
> * windows-ghc9.2 can't deal with extern doc (ubuntu-ghc9.2 works fine)
> * ubuntu-ghc9.0 can't deal with local doc
> 
> I'll remove doc test instead of just testing whether the defined doc(`Defined at`) ends with '\n', it weakens the test power:(

I began to doubt the necessity of so many tests. In fact, it was just testing whether the "defined doc" ended with '\ n'.

**Comment by pepeiborra** [comment]
> Failure reason:
> 
> * windows-ghc9.2 can't deal with extern doc (ubuntu-ghc9.2 works fine)

This could be the same as Mac OS, where the ghc 9.2.1 and ghc 9.0.2 distributions shipped without haddock docs in interfaces: https://gitlab.haskell.org/ghc/ghc/-/issues/20903

> * ubuntu-ghc9.0 can't deal with local doc
> 
> I'll remove doc test instead of just testing whether the defined doc(`Defined at`) ends with '\n', it weakens the test power:(

Preferably keep the full test, mark it as broken, and then add a reduced test that only checks for the final `'\n'`.

**Comment by July541** [comment]
OK, doc tests should exist, I'll check each ghc and platform.

File: ghcide/src/Development/IDE/Spans/Common.hs [hunk 3]
```diff
@@ -76,13 +78,24 @@ data SpanDocUris =
 emptySpanDoc :: SpanDoc
 emptySpanDoc = SpanDocText [] (SpanDocUris Nothing Nothing)
 
+-- | Convert `SpanDoc` to Markdown format.
+--
+-- Return a list `Text` includes haddock, document uri and source code uri,
+-- each item can be empty and must end with '\\n' if exist.
```
Comment (pepeiborra) [inline ghcide/src/Development/IDE/Spans/Common.hs:84]: It would be good to explain why each item must end with a newline.

Also, I don't think all the items end with a newline - the ones produced by `spanDocUrisToMarkdown` don't, do they ?

**Review by pepeiborra — APPROVED** [review]
Thanks for the fix, and for reworking the broken tests support in the testsuite 😍 !
