### PR TITLE
Fix sticky diagnostics

### LINKED ISSUE #1171: Sticky diagnostics
I have seen a redundant import warning refusing to go away after clearing the import, and I believe this could well be an unintended consequence of haskell/ghcide#959

I haven't been able to reproduce it consistently, much less to create a failing test. Just recording it here as a known issue for now.

### PR DESCRIPTION
**Pull request by pepeiborra**
In haskell/ghcide#959 I tried to fix a problem with diagnostics:
- PROBLEM: when early cut-off kicks in and a stage is skipped (e.g. `TypeCheck`) its diagnostics are lost
- SOLUTION: when creating diagnostics for a new version of a document, start from the diagnostics for the previous version.

The assumption in the solution is that starting with the previous diagnostics is sound because they will get updated incrementally as the rules are re-run. If a rule is not re-run then it must have been cut-off and its diagnostics are still valid.

But hold on, the "build" graph is dynamic, so the rules to be run for a file can change at any time! So it's not always the case that if a rule is not re-run, its diagnostics are still valid. For instance, the graph for a non-FOI changes when it becomes a FOI, e.g. `GetModIfaceFromDisk` is not re-run, so its diagnostics will stick around until the file becomes a non-FOI again, and `GetModIfaceFromDisk` is re-run.

The right solution is to store the diagnostics in our state (the `values` ref):
- when creating diagnostics for a new version, just start from scratch as we used to
- when early cut-off kicks in, reuse the diagnostics stored during the previous run of the rule
- graph changes are not a problem, since only the diagnostics from the rules that actually run are considered

Fixes #1171

### CODE REVIEW

File: ghcide/src/Development/IDE/Core/Shake.hs [hunk 1]
```diff
@@ -842,18 +814,21 @@ defineEarlyCutoff op = addBuiltinRule noLint noIdentity $ \(Q (key, file)) (old
                 (bs, (diags, res)) <- actionCatch
                     (do v <- op key file; liftIO $ evaluate $ force v) $
                     \(e :: SomeException) -> pure (Nothing, ([ideErrorText file $ T.pack $ show e | not $ isBadDependency e],Nothing))
-                modTime <- liftIO $ (currentValue =<<) <$> getValues state GetModificationTime file
-                (bs, res) <- case res of
+                modTime <- liftIO $ (currentValue . fst =<<) <$> getValues state GetModificationTime file
+                (bs, diags, diagsV, res) <- case res of
```
Comment (wz1000) [inline ghcide/src/Development/IDE/Core/Shake.hs:818]: `diags` and `diagsV` are the same, and you just return both to avoid doing `Vector.fromList (Vector.toList v)`?

Comment (pepeiborra) [reply ghcide/src/Development/IDE/Core/Shake.hs:818]: Yes. Depending on the branch we start with either a list or a vector, and later we need both

Comment (wz1000) [reply ghcide/src/Development/IDE/Core/Shake.hs:818]: Instead can we make `updateFileDiagnostics` take a Vector?

**Review by wz1000 — APPROVED** [review]

File: ghcide/src/Development/IDE/Core/Shake.hs (hunk 1 above)
Comment (pepeiborra) [reply ghcide/src/Development/IDE/Core/Shake.hs:818]: `updateFileDiagnostics` wants a list though, since it partitions diagnostics in shown and hidden

Comment (wz1000) [reply ghcide/src/Development/IDE/Core/Shake.hs:818]: Vector has partition operations too?

Comment (pepeiborra) [reply ghcide/src/Development/IDE/Core/Shake.hs:818]: Why would you want to allocate an intermediate vector though?
