### PR TITLE
Make cradle dependencies absolute paths

### LINKED ISSUE #1068: Reload required when adding new dependencies to package.yaml/.cabal file
When adding new dependencies to `package.yaml` you need to reload VSCode to keep ghcide up to date.

To reproduce:

- Add a new dependency to the `package.yaml` of a project
- Import a module from that new dependency
- You get an error for the import
- Reload and the error should go away

Adding a new dependency happens relatively infrequently so this isn't a big deal, but I thought it might be worth noting as a limitation if it isn't easy to fix.

### PR DESCRIPTION
**Pull request by jian-lin**
This patch fixes #1068 when the cabal plugin is not used.

---

   
The code change in Session.hs is written by @fendor.  Tests and comments are added by me.

### CODE REVIEW

File: plugins/hls-cabal-plugin/test/Utils.hs [hunk 1]
```diff
@@ -61,6 +65,14 @@ runHaskellAndCabalSession :: FilePath -> Session a -> IO a
 runHaskellAndCabalSession subdir =
     failIfSessionTimeout . runSessionWithServer def (cabalPlugin <> cabalHaskellPlugin) (testDataDir </> subdir)
 
+runShiftedRootInTmpDirSession :: FilePath -> (FilePath -> Session a) -> IO a
+runShiftedRootInTmpDirSession subdir =
+    failIfSessionTimeout . runSessionWithTestConfig def
+        { testDirLocation = Right $ mkVirtualFileTree testDataDir [copyDir subdir]
+        , testShiftRoot = True
```
Comment (jian-lin) [inline plugins/hls-cabal-plugin/test/Utils.hs:72]: It takes me some time to figure out that `testShiftRoot = True` is necessary for tests to work.

When `testShiftRoot` is the default value `False`, cradle dependencies except `hie.yaml` are relative paths, which can be wrong under the working directory of HLS.  When the path is wrong, its mtime is also wrong.  Wrong mtime makes it [always be considered up-to-date][1], which will never [invalidate][2] the cache of `GhcSession` action.

Maybe it is better to make cradle dependencies always absolute?

[1]: https://github.com/haskell/haskell-language-server/blob/173b5a7fbfb92c3c6a3375be100b662226aad852/ghcide/session-loader/Development/IDE/Session.hs#L679
[2]: https://github.com/haskell/haskell-language-server/blob/173b5a7fbfb92c3c6a3375be100b662226aad852/ghcide/src/Development/IDE/Core/Rules.hs#L719

File: plugins/hls-cabal-plugin/test/CabalAdd.hs [hunk 2]
```diff
@@ -183,3 +195,17 @@ cabalAddTests =
...
+        hsdoc <- openDoc haskellFile "haskell"
+        _ <- waitForDiagnosticsFrom hsdoc
+        cabalContent <- liftIO $ T.readFile cabalFile
+        let fix = T.replace "build-depends:    base" "build-depends:    base, split"
+        liftIO $ T.writeFile cabalFile (fix cabalContent)
+        sendNotification SMethod_WorkspaceDidChangeWatchedFiles $ DidChangeWatchedFilesParams
+            [ FileEvent (filePathToUri $ root </> cabalFile) FileChangeType_Changed ]
+        diagnostics <- waitForDiagnosticsFrom hsdoc
+        case diagnostics of
+            [diagnostic] -> liftIO $ assertEqual "Wrong diagnostic after HLS restarts" (Just $ InR "GHC-66111") (diagnostic ^. L.code)
```
Comment (jian-lin) [inline plugins/hls-cabal-plugin/test/CabalAdd.hs:210]: This fails in GHC 9.4 and 9.6.  Should we use CPP or should we match something else for all GHC versions?

Comment (fendor) [reply plugins/hls-cabal-plugin/test/CabalAdd.hs:210]: Wait, this test can only succeed if the hls-cabal-plugin is enabled...? But this patch only works if the hls-cabal-plugin is disabled? Or is this test run without the `hls-cabal-plugin`? If the test is run without the plugin, I think it should be part of the `ghcide-test`s.

Regarding `InR "GHC-66111"` (which I assume to be the reason for the test case to fail) The `expectDiagnostics` test helper ignores the test code for the unsupported GHC versions 9.4 and 9.6, maybe use that if possible?

The windows failure is flaky, just ignore :)

File: plugins/hls-cabal-plugin/test/Utils.hs (hunk 1 above)
Comment (fendor) [reply plugins/hls-cabal-plugin/test/Utils.hs:72]: Yeah, cradle dependencies are supposed to be always absolute. Perhaps this is even a bug in `hie-bios`...

**Review by fendor — APPROVED** [review]
LGTM, small nitpick

File: plugins/hls-cabal-plugin/test/CabalAdd.hs (hunk 2 above)
Comment (jian-lin) [reply plugins/hls-cabal-plugin/test/CabalAdd.hs:210]: > this test can only succeed if the hls-cabal-plugin is enabled...?

`hls-cabal-plugin` contains two plugins: [`cabal`][1] and [`cabalHaskellIntegration`][2]. This test works if and only if HLS does not handle `.cabal` files, i.e., the `cabal` plugin is not used.

> If the test is run without the plugin, I think it should be part of the `ghcide-test`s.

I was not quite sure where to put this test.  I will move this test to `ghcide-test`.

When a fix for #1068 with `cabal` plugin **enabled** is proposed in the future, its test probably should be put here.  I think it makes (some) sense to put tests for these two cases together so I put this test (for #1068 with `cabal` plugin **disabled**) here.

[1]: https://github.com/haskell/haskell-language-server/blob/173b5a7fbfb92c3c6a3375be100b662226aad852/src/HlsPlugins.hs#L154
[2]: https://github.com/haskell/haskell-language-server/blob/173b5a7fbfb92c3c6a3375be100b662226aad852/src/HlsPlugins.hs#L155



> The `expectDiagnostics` test helper ignores the test code for the unsupported GHC versions 9.4 and 9.6, maybe use that if possible?

`expectDiagnostics` seems not suitable here since it only ignores [GHC < 9.6][3].  Here, the actual diagnostic code is `Nothing` for GHC 9.6 and 9.4 and the expected diagnostic is as follows:

```
  [ Diagnostic
      { _range = Range {_start = Position {_line = 2, _character = 0}, _end = Position {_line = 2, _character = 22}},
        _severity = Just DiagnosticSeverity_Warning,
        _code = Just (InR "GHC-66111"),
        _codeDescription = Nothing,
        _source = Just "typecheck",
        _message = "The import of \8216Data.List.Split\8217 is redundant\n  except perhaps to import instances from \8216Data.List.Split\8217\nTo import instances alone, use: import Data.List.Split()",
        _tags = Just [DiagnosticTag_Unnecessary],
        _relatedInformation =
          Just
            [ DiagnosticRelatedInformation
                { _location =
                    Location
                      { _uri = Uri {getUri = "file:///tmp/hls-test-root/extra-dir-44362888928157/src/MyLib.hs"},
                        _range = Range {_start = Position {_line = 2, _character = 0}, _end = Position {_line = 2, _character = 22}}
                      },
                  _message = "TypeCheck"
                }
            ],
        _data_ = Just (Object (fromList [("attachedReason", Array [String "-Wunused-imports"])]))
      }
  ]
```



[3]: https://github.com/haskell/haskell-language-server/blob/173b5a7fbfb92c3c6a3375be100b662226aad852/hls-test-utils/src/Development/IDE/Test/Diagnostic.hs#L69

Comment (fendor) [reply plugins/hls-cabal-plugin/test/CabalAdd.hs:210]: Ok, then you can use the `ghcVersion` variable to change the assertion based on the GHC version. This avoids CPP which much more annoying.

File: plugins/hls-cabal-plugin/test/Utils.hs (hunk 1 above)
Comment (jian-lin) [reply plugins/hls-cabal-plugin/test/Utils.hs]: > cradle dependencies are supposed to be always absolute

That is good to know.  When I have time, I will check hie-bios to see if I can do something there.

File: ghcide-test/exe/WatchedFileTests.hs [hunk 3]
```diff
@@ -69,6 +73,17 @@ tests = testGroup "watched files"
...
+          let hsFile = "src" </> "MyLib.hs"
+          _ <- openDoc hsFile "haskell"
+          expectDiagnostics [(hsFile, [(DiagnosticSeverity_Error, (2, 7), "Could not load module \8216Data.List.Split\8217.\nIt is a member of the hidden package \8216split", Nothing)])]
+          let cabalFile = "reload.cabal"
+          cabalContent <- liftIO $ T.readFile cabalFile
+          let fix = T.replace "build-depends:    base" "build-depends:    base, split"
+          liftIO $ T.writeFile cabalFile (fix cabalContent)
+          sendNotification SMethod_WorkspaceDidChangeWatchedFiles $ DidChangeWatchedFilesParams
+            [ FileEvent (filePathToUri $ sessionDir </> cabalFile) FileChangeType_Changed ]
+          expectDiagnostics [(hsFile, [])]
```
Comment (jian-lin) [inline ghcide-test/exe/WatchedFileTests.hs:86]: When this test is in `hls-cabal-plugin-tests`, there [is][1] a diagnostic after HLS restarts.

```
The import of \8216Data.List.Split\8217 is redundant\n  except perhaps to import instances from \8216Data.List.Split\8217\nTo import instances alone, use: import Data.List.Split()
```

Moving the tests into `ghcide-tests` causes that diagnostic to disappear.  I have not tried to find the cause yet.  I guess it is because we enable fewer plugins in the test now and the plugin providing this diagnostic is not enabled.

I have verified that HLS does reload after the `SMethod_WorkspaceDidChangeWatchedFiles` notification.

[1]: https://github.com/haskell/haskell-language-server/pull/4576#discussion_r2072602661

**Review by jian-lin — COMMENTED** [review]
I think previous comments are addressed.

File: ghcide-test/exe/WatchedFileTests.hs (hunk 3 above)
Comment (fendor) [reply ghcide-test/exe/WatchedFileTests.hs:86]: Hm, it is weird, the diagnostic is generated by GHC, not any plugin... In any way, still a clear improvement, thank you!

**Review by fendor — APPROVED** [review]

**Comment by fendor** [comment]
@jian-lin Please rebase, then we can get this in :)

**Comment by jian-lin** [comment]
Now all windows `/Diagnostics in .hs files from invalid .cabal file/` tests fail.  I vaguely remember that all tests pass before the rebase.  Any ideas?

**Comment by fendor** [comment]
Hm, that's indeed weird... No, unfortunately nothing comes immediately to mind.

**Comment by jian-lin** [comment]
Thanks for all the help!
