### PR TITLE
Use apply-refact 0.12.0

### LINKED ISSUE #3241: HLS suggests quick fixes but cannot apply them
### Your environment

* Arch Linux
* Emacs 28.2 + Eglot (also tested: lsp-mode, VSCode OSS with Haskell LSP plugin 2.2.1)
* GHC 9.2.4
* HLS 1.8.0.0
* Cabal 3.6.2.0
* Stack 2.9.1

### Steps to reproduce

Write any code that HLS will suggest a quick fix for, such as: f x = id x.

### Expected behaviour

HLS should suggest a quick fix, then apply the change after selecting the quick fix.

### Actual behaviour

HLS offers the appropriate code actions, but quick fixes throw errors instead of applying the changes to the code. Other code actions, such as "Ignore hint ... in this module" still work. Other HLS features also work.
I have tested this with both Emacs LSP packages as well as VSCode, with identical results in all three cases.

### Debug information

Error condition, please check your setup and/or the [issue tracker](https://github.com/haskell/haskell-language-server/issues): ReactorMessageActionException ExitFailure 1

### PR DESCRIPTION
**Pull request by fendor**
Fixes #3241 by upgrading to apply-refact 0.12.0 for compatible GHC versions. Other GHC versions are not affected.

### CODE REVIEW

File: plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs [hunk 1]
```diff
@@ -609,7 +601,7 @@ applyHint recorder ide nfp mhint =
                 (anns', modu') <-
                     ExceptT $ mapM (uncurry Refact.applyFixities)
                             $ postParseTransform (Right (anns, [], dflags, modu)) rigidLayout
-                liftIO $ (Right <$> withRuntimeLibdir (Refact.applyRefactorings' position commands anns' modu'))
+                liftIO $ (Right <$> Refact.applyRefactorings' position commands anns' modu')
```
Comment (fendor) [inline plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs:604]: This is curious, this code-path is definitely not exercised for GHC >= 9.2, since the API in apply-refact has changed in 0.11.0. And in apply-refact <= 0.10.0, I don't think we need the hack `withRuntimeLibdir` because the libdir is only needed for parsing and we pass in a module already.

**Comment by fendor** [comment]
PR breaks because of https://github.com/tweag/ormolu/issues/981

**Review by hasufell — APPROVED** [review]

**Review by michaelpj — APPROVED** [review]

File: plugins/hls-hlint-plugin/hls-hlint-plugin.cabal [hunk 2]
```diff
@@ -62,7 +62,7 @@ library
     , ghc-lib-parser
     , ghc-lib-parser-ex
   if impl(ghc >= 9.2)
-    build-depends: apply-refact ^>= 0.11.0.0
```
Comment (pepeiborra) [inline plugins/hls-hlint-plugin/hls-hlint-plugin.cabal:65]: Why isn't the version selection handled by Cabal? Just set proper bounds for the `ghc` dependency  in the `apply-refact` Cabal descriptor and remove all these conditionals from here

File: plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs [hunk 3]
```diff
@@ -641,3 +633,57 @@ bimapExceptT f g (ExceptT m) = ExceptT (fmap h m) where
...
+  -- to right. An extension (e.g., @StarIsType@) may be overridden later (e.g., by @NoStarIsType@).
+  --
+  -- These are in addition to the @LANGUAGE@ pragmas in the target file. When they conflict
+  -- with the @LANGUAGE@ pragmas, pragmas win.
+  [String] ->
+  IO String
+applyRefactorings =
+#if MIN_VERSION_apply_refact(0,12,0)
+  Refact.applyRefactorings
+#elif MIN_VERSION_apply_refact(0,10,0) && !MIN_VERSION_apply_refact(0,11,0)
```
[the remark this answers is not in the document]
Comment (fendor) [reply plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs:674]: ok, removing it!

File: plugins/hls-hlint-plugin/hls-hlint-plugin.cabal (hunk 2 above)
Comment (fendor) [reply plugins/hls-hlint-plugin/hls-hlint-plugin.cabal:65]: Like this? Now we just explicitly forbid 0.11.0

Comment (pepeiborra) [reply plugins/hls-hlint-plugin/hls-hlint-plugin.cabal:65]: No, simply: `build-depends: apply-refact`. Then cabal will select the version that works with the `ghc` package that is built-in

Comment (fendor) [reply plugins/hls-hlint-plugin/hls-hlint-plugin.cabal:65]: That would in theory permit version 0.11.0, I want to explicitly forbid this. Or do you think that's pointless?

Comment (pepeiborra) [reply plugins/hls-hlint-plugin/hls-hlint-plugin.cabal:65]: I think it's pointless, as it won't be used in any scenarios. If you still have concerns, mark it as deprecated in Hackage

**Review by georgefst — APPROVED** [review]
