### PR TITLE
Disable flaky test on Windows

### LINKED ISSUE #2997: Re-exported symbol hover ghcide test is flaky on Windows
Recently windows tests are unstable due to https://github.com/haskell/haskell-language-server/blob/master/ghcide/test/exe/Main.hs#L4442

It's a test for the definition of reexported symbol. I've checked that both the expected result and the real result are all acceptable for goto definition behavior.

Some observations:
1. It failed most time.
2. Retry has a chance to pass the test.

Known affected prs:
1. #2995
2. #2988 
3. #2986 
4. #2960

### PR DESCRIPTION
**Pull request by michaelpj**
I don't think anyone is going to fix this soon, let's just disable it so
we can move on.

Fixes #2997.

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3008"></a>

### CODE REVIEW

File: ghcide/test/exe/Main.hs [hunk 1]
```diff
@@ -4439,7 +4439,11 @@ findDefinitionAndHoverTests = let
   , test  no     yes    holeL65    hleInfo2      "hole with variable"
   , test  no     yes    cccL17     docLink       "Haddock html links"
   , testM yes    yes    imported   importedSig   "Imported symbol"
-  , testM yes    yes    reexported reexportedSig "Imported symbol (reexported)"
+  , if | isWindows ->
+        -- Flaky on Windows: https://github.com/haskell/haskell-language-server/issues/2997
+        testM broken yes    reexported reexportedSig "Imported symbol (reexported)"
```
Comment (July541) [inline ghcide/test/exe/Main.hs:4444]:
```suggestion
        testM no yes    reexported reexportedSig "Imported symbol (reexported)"
```

**Review by July541 — APPROVED** [review]
Should be `no` because it may succeed, we don't test it on Windows.

Otherwise, LGTM!

File: ghcide/test/exe/Main.hs (hunk 1 above)
Comment (michaelpj) [reply ghcide/test/exe/Main.hs]: Ah, thanks!
