### PR TITLE
Fix progress eval test randomly failing

### LINKED ISSUE #2578: Flaky test suite: progress reporting (func-test)
This test suite fails often with an unexpected progress token error:
```
FAIL (1.11s)
      test/functional/Progress.hs:105:
      Unexpected ProgressTextToken "47"
```
https://github.com/haskell/haskell-language-server/runs/4754928207?check_suite_focus=true
https://github.com/haskell/haskell-language-server/runs/4754788726?check_suite_focus=true
https://github.com/haskell/haskell-language-server/runs/4754639502?check_suite_focus=true
https://github.com/haskell/haskell-language-server/runs/4754227465?check_suite_focus=true

### PR DESCRIPTION
**Pull request by eddiemundo**
Fixes #2578.

Took way too long to find for how simple it was. The issue was that `getCodeLenses` was occasionally eating progress create messages, which caused any further messages with the same progress tokens to fail.

The implemented fix is to expect progress messages up to the point of the code lens response, do whatever we need the code lens response for, then pass the currently active progress tokens to the final expect progress messages function finishing up the expectations.

The other progress tests should be fine since they don't eat messages.

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2590"></a>

### CODE REVIEW

File: test/functional/Progress.hs [hunk 1]
```diff
@@ -59,47 +76,87 @@ formatLspConfig provider = object ["haskell" .= object ["formattingProvider" .=
...
       _ -> Nothing)
-    end = EndM <$> satisfyMaybe (\case
+    progressEnd = ProgressEnd <$> satisfyMaybe (\case
       FromServerMess SProgress (NotificationMessage _ _ (ProgressParams t (End x))) -> Just (ProgressParams t x)
       _ -> Nothing)
-    expectElem a as = a `elem` as @? "Unexpected " ++ show a
+
+interestingMessage :: Session a -> Session (InterestingMessage a)
+interestingMessage interestingMessage =
+  fmap InterestingMessage interestingMessage <|> fmap ProgressMessage progressMessage
```
Comment (pepeiborra) [inline test/functional/Progress.hs:106]:
```suggestion
interestingMessage :: Session a -> Session (InterestingMessage a)
interestingMessage theMessage =
  fmap InterestingMessage theMessage <|> fmap ProgressMessage progressMessage
```

File: test/functional/Progress.hs [hunk 2]
```diff
@@ -59,47 +76,87 @@ formatLspConfig provider = object ["haskell" .= object ["formattingProvider" .=
...
+      expectProgressMessages expectedTitles (getToken params : activeProgressTokens)
+    ProgressBegin params -> do
+      liftIO $ getToken params `expectedIn` activeProgressTokens
+      expectProgressMessages (delete (getTitle params) expectedTitles) activeProgressTokens
+    ProgressReport params -> do
+      liftIO $ getToken params `expectedIn` activeProgressTokens
+      expectProgressMessages expectedTitles activeProgressTokens
+    ProgressEnd params -> do
+      liftIO $ getToken params `expectedIn` activeProgressTokens
+      expectProgressMessages expectedTitles (delete (getToken params) activeProgressTokens)
```
Comment (pepeiborra) [inline test/functional/Progress.hs:147]: Can `expectProgressMessages` be defined in terms of `expectProgressMessagesTill`?

**Review by pepeiborra — APPROVED** [review]
Awesome! The effort invested in fixing these subtle flaky tests often goes unnoticed so please accept my unlimited gratitude.

File: test/functional/Progress.hs (hunk 2 above)
Comment (eddiemundo) [reply test/functional/Progress.hs]: I couldn't figure out how to write one in terms of the other because the termination conditions differ slightly, but did the next best thing of factoring out the common logic.
