### PR TITLE
Make type lenses plugin configurable

### LINKED ISSUE #622: CodeLens to add type signature failed to deal with functions with `*` in their names
image

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 0.6.0.0 (GHC: 8.10.2) (PATH: /home/berberman/.cabal/store/ghc-8.10.2/haskell-language-server-0.6.0.0-12a6a1bf45aba2e44066b7b11fef0d76d92497c62667866a713a7034b763f060/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:          3.2.0.0
stack:          2.5.1
ghc:            8.10.2
```
Which lsp-client do you use:
vscode

### Steps to reproduce
Create a function whose name contains `*` .
### Expected behaviour
Code lens helps me to add the missing type signature properly.

### Actual behaviour
Type signature is cut off at `*`.

### Note

https://github.com/haskell/ghcide/blob/c4418abdc10c93eda0b27f24b1076995fff9de45/src/Development/IDE/Plugin/CodeAction.hs#L686-L692

Why we take until the `*` or `•`?

### LINKED ISSUE #1468: CodeLens to add type signature inserts invalid type signature
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 1.0.0.0 (GHC: 8.10.3) (PATH: /home/berberman/.cabal/store/ghc-8.10.3/haskell-language-server-1.0.0.0-c7859e8f45ef6bd2fac7adc65982f4e497ee3c40299bcc89c5915aaa0534ebc3/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:          3.2.0.0
stack:          Not found
ghc:            8.10.3
```
Which lsp-client do you use:
vscode

### Steps to reproduce

Create a module with functions that lead to ambiguity:

```haskell
module Test where

head = 233

(+) = undefined
```

### Expected behaviour

```haskell
module Test where

head :: Integer
head = 233

(+) :: a
(+) = undefined

```

### Actual behaviour

Type signatures are qualified with the module name, which are invalid.

```haskell
module Test where

Test.head :: Integer
head = 233

(Test.+) :: a
(+) = undefined
```

### LINKED ISSUE #1477: How to control the display of type signature lenses
* With this flag the user signals he wants ghc warns about type signatures of  exported definitions and not for all top level definitions
* It would be nice follow that signal and only show type signature for those exported symbols and no all of them

(Suggested in fp discord channel by @edmundnoble)

### PR DESCRIPTION
**Pull request by berberman**
This PR is rebased on #1471, so we could close #1471 in favour of this (if it looks good).

Closes #1477
Closes #1468
Closes #622

## Demo

https://user-images.githubusercontent.com/26041945/109928100-10c8d000-7d00-11eb-85e7-66d6aa500a94.mp4

Previously, we set `Opt_WarnMissingSignatures` and `Opt_WarnMissingPatternSynonymSignatures` for each module to produce hidden diagnostics and generate code lenses. By contrast, types of global bindings are derived from results of typecheck, instead of parsing diagnostic messages.

There are four working modes introduced in generic plugin config:

* ~~`Enabled`~~ `Always` -- always displays type lenses of global bindings, no matter what GHC flags are set by users
* `Exported` -- similar to `Enabled`, but only shows for exported global bindings
* `Diagnostics` -- follows error messages produced by GHC, users can control the display of code lenses by setting GHC flags in this mode
~~* `Disabled` -- fully disabled~~

For local bindings, corrsponding type lenses show only when `Opt_WarnMissingLocalSignatures` is set and works in `Always` mode.

### CODE REVIEW

**Comment by jneira** [comment]
Wow, impressive work, many thanks

There would be a generic config option to enable or disable code lenses for the plugin, if ghcide plugins honour the generic configuration (and they should be imo, see #1321)

Add such a generic configuration maybe is out of the scope of this pr but maybe we should design the options taking in account the plugin will have enable/disable at some point.
You alway will be able to disable it set `diagnostics` and disable all ghc warnings about missing type definitions, no?

So the options could be

* Always-- always displays type lenses of global bindings, no matter what GHC flags are set by users
* Exported -- similar to Enabled, but only shows for exported global bindings
* Diagnostics -- follows error messages produced by GHC, users can control the display of code lenses by setting GHC flags in this mode

**Comment by jneira** [comment]
> You alway will be able to disable it setting diagnostics and disable all ghc warnings about missing type definitions in the meanwhile, no?

What about some test negating the ghc warnings, to check no type lens is emitted?

**Comment by berberman** [comment]
> So the options could be
> 
> * Always-- always displays type lenses of global bindings, no matter what GHC flags are set by users
> * Exported -- similar to Enabled, but only shows for exported global bindings
> * Diagnostics -- follows error messages produced by GHC, users can control the display of code lenses by setting GHC flags in this mode

Yeah, that makes sense.

> What about some test negating the ghc warnings, to check no type lens is emitted?

Agree, we need update tests to run against each mode.

**Comment by isovector** [comment]
There appears to be a space in the config string in the video. Is that intentional? Necessary?

**Comment by berberman** [comment]
@isovector Ah, good catch. It's not intentional, but works coincidentally because of the `Read` instance.

File: ghcide/src/Development/IDE/Plugin/TypeLenses.hs [hunk 1]
```diff
@@ -44,66 +89,182 @@ descriptor :: PluginId -> PluginDescriptor IdeState
...
+rules = do
+  define $ \GetGlobalBindingTypeSigs nfp -> do
+    tmr <- use TypeCheck nfp
+    -- we need session here for tidying types
+    hsc <- use GhcSession nfp
+    result <- liftIO $ gblBindingType (hscEnv <$> hsc) (tmrTypechecked <$> tmr)
+    pure ([], result)
+
+parseCustomConfig :: A.Object -> Maybe Mode
+parseCustomConfig = A.parseMaybe (\o -> read <$> o A..: "mode")
```
Comment (isovector) [inline ghcide/src/Development/IDE/Plugin/TypeLenses.hs:243]: This will crash if someone puts in a malformatted string, right? I think you might want some variant of safe read here --- perhaps `fmap fst . listToMaybe . reads`

Comment (isovector) [reply ghcide/src/Development/IDE/Plugin/TypeLenses.hs:243]: But a better play is probably just to write a `FromJSON` instance for `Mode` and delegate to that. The `Alternative` instance will let you parse more natural lower-case JSON strings.

Comment (berberman) [reply ghcide/src/Development/IDE/Plugin/TypeLenses.hs]: Thank you!

Comment (berberman) [reply ghcide/src/Development/IDE/Plugin/TypeLenses.hs]: Thank you!

**Review by jneira — APPROVED** [review]
great work, tests looks great too

**Comment by jneira** [comment]
4 issues closed in a row, amazing :clap:
