### PR TITLE
 idempotent command and code cleanup

### LINKED ISSUE #564: CodeLens provided by ModuleName does not disappear properly
### Subject of the issue

Peek 2020-11-02 18-57

### Your environment
```
haskell-language-server version: 0.5.1.0 (GHC: 8.10.2) (PATH: /home/berberman/.cabal/store/ghc-8.10.2/haskell-language-server-0.5.1.0-e719e6f687739d6ff770e7a1372b2b19718f9811d322d8cde279a5f71726b6a0/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.5.1
ghc:		8.10.2
```

### Steps to reproduce
Just by creating a new file

### PR DESCRIPTION
**Pull request by tittoassini**
This should fix #564

The operation to perform is recalculated before being applied.

### CODE REVIEW

**Review by Ailrun — COMMENTED** [review]
Sorry, it's bit hard to review with all these style changes mixed with logic changes. Could you divide them into separate commits?

**Comment by tittoassini** [comment]
> Sorry, it's bit hard to review with all these style changes mixed with logic changes. Could you divide them into separate commits?

Hi Ailrun, I would like to help but I would not know where to start to separate it in different commits, it's a single file and all changes are closely related.

Maybe it would be simpler to review directly the new code? It's a very short module:
 https://github.com/tittoassini/haskell-language-server/blob/idem/plugins/default/src/Ide/Plugin/ModuleName.hs

Apart from the code refactoring (mainly getting rid of dead code and simplifying the 'actions' function to 'action') the main difference is that 'action', that calculates what is to be done, is called every time the codeLens is used by the user, rather than just at CodeLens creation time.

This avoids the problem of the user clicking multiple times on the CodeLens and ending up with multiple inserts of 'module .. where'.

**Review by jneira — APPROVED** [review]
@tittoassini i think @Ailrun was talking about the formatting changes in language pragmas and imports.
As a general rule we like to separate semantic from syntactic pr's. But well, being the original author of the plugin, i think we can be flexible in thos case 😄
I am gonna approve it, @Ailrun i will wait yours for merging

File: plugins/default/src/Ide/Plugin/ModuleName.hs [hunk 1]
```diff
@@ -1,222 +1,206 @@
...
-asTextEdits Action {..} = [TextEdit aRange aCode]
-
-out :: IdeState -> [String] -> IO ()
-out state =
-  logPriority (ideLogger state) Debug
-    . pack
-    . unwords
-    . ("Plugin ModuleName " :)
+traceAs :: b -> a -> a
+traceAs _ a = a
```
Comment (Ailrun) [inline plugins/default/src/Ide/Plugin/ModuleName.hs:206]: Could you clean these debug functions? Other than that, looks good.

**Comment by tittoassini** [comment]
> @tittoassini i think @Ailrun was talking about the formatting changes in language pragmas and imports.
> As a general rule we like to separate semantic from syntactic pr's. But well, being the original author of the plugin, i think we can be flexible in thos case 😄
> I am gonna approve it, @Ailrun i will wait yours for merging

You are right, next time I will try to be more careful.

File: plugins/default/src/Ide/Plugin/ModuleName.hs (hunk 1 above)
Comment (tittoassini) [reply plugins/default/src/Ide/Plugin/ModuleName.hs:206]: Thanks.

But clean them up in what way exactly?

I could redefine them so that they use the standard logger, as in the previous 'out' function.
  
Would that be ok?

Comment (Ailrun) [reply plugins/default/src/Ide/Plugin/ModuleName.hs:206]: Yes, that and removing the commented one are what I mean.

**Comment by tittoassini** [comment]
@jneira I see that this branch has been merged, should I then make a different PR for @Ailrun proposed changes to the traceAs function?

**Comment by jneira** [comment]
@tittoassini oops, sorry i thought @ailrun gave its ok :worried: too eager to merge to include it in the ne release

please do it in a new pr
