### PR TITLE
Produce structured error for unknown module

### LINKED ISSUE #4684: Produce structured error for unknown module
Currently, we need to use a regex to figure out whether an error message relates to an unknown module.
With a structured error, we could handle this in a cleaner and safer way.

We are currently generating it like this:

```haskell
unknownModuleMessage :: String -> [String]
unknownModuleMessage moduleFileName =
  [ "Loading the module '" <> moduleFileName <> "' failed."
  , ""
  , "It may not be listed in your .cabal file!"
  , "Perhaps you need to add `"<> dropExtension (takeFileName moduleFileName) <> "` to other-modules or exposed-modules."
  , ""
  , "For more information, visit: https://cabal.readthedocs.io/en/3.4/developing-packages.html#modules-included-in-the-package"
  ]
```

Specifically, this would help in the new cabal-add-module code action, where I had to parse the string using a regex.

### PR DESCRIPTION
**Pull request by vidit-od**
Fixes #4684

This PR does 2 things : 

1) introduce a new Data Type called `StructuredErrors` and `UnknownModuleDetails`. StructuredErrors are then added inside `CradleErrorDetails`. 

This helps us make sure that we can easily extend `StructuredErrors` later with more details without changing cradleErrorDetials. 

i.e 

```haskell
data CradleErrorDetails =
  CradleErrorDetails
    { cabalProjectFiles :: [FilePath]
    , structuredError   :: Maybe StructuredErrors
    } deriving (Show, Eq, Ord, Read, Generic, Aeson.ToJSON, Aeson.FromJSON)

data StructuredErrors =
  StructuredErrors
    { unknownModule :: Maybe UnknownModuleDetails
    } deriving (Show, Eq, Ord, Read, Generic, Aeson.ToJSON, Aeson.FromJSON)

data UnknownModuleDetails =
  UnknownModuleDetails
    { moduleFilePath   :: FilePath
    , suggestedModName :: String
    } deriving (Show, Eq, Ord, Read, Generic, Aeson.ToJSON, Aeson.FromJSON)

```

Note : i am not 100% sure if these are the perfect names to use, any suggestions here will help a lot !!

2) change `isUnknownModuleDiagnostic` used in hls-cabal-plugin. Previously it used regex matching return Bool values if unknownModule error exists. Now we pattern match on our structuredError to find this detail.  

Note : i could not find any other callers where we are regex matching on the error string (for unknown modules). i am not sure if there are any more ?

### CODE REVIEW

File: ghcide/session-loader/Development/IDE/Session/Diagnostics.hs [hunk 1]
```diff
@@ -21,6 +21,20 @@ data CradleErrorDetails =
     { cabalProjectFiles :: [FilePath]
     -- ^ files related to the cradle error
     -- i.e. .cabal, cabal.project, etc.
+    , structuredError   :: Maybe StructuredErrors
+    -- ^ errors related to cradle error
+    -- i.e. unknownModules error
+    } deriving (Show, Eq, Ord, Read, Generic, Aeson.ToJSON, Aeson.FromJSON)
+
+data StructuredErrors =
```
Comment (VeryMilkyJoe) [inline ghcide/session-loader/Development/IDE/Session/Diagnostics.hs]: How about something like `structuredCradleError` ? 
I think just structuredError is a bit confusing as it reminds me of the GHC structured errors.

Since that would go in a more generalised direction, it would make sense to rename `cabalProjectFiles` in a similar manner, I think `cradleDependencies` could work?

File: ghcide/session-loader/Development/IDE/Session/Diagnostics.hs [hunk 2]
```diff
@@ -21,6 +21,20 @@ data CradleErrorDetails =
...
+  StructuredErrors
+    { unknownModule :: Maybe UnknownModuleDetails
+    } deriving (Show, Eq, Ord, Read, Generic, Aeson.ToJSON, Aeson.FromJSON)
+
```
Comment (VeryMilkyJoe) [inline ghcide/session-loader/Development/IDE/Session/Diagnostics.hs]: I think a sum-type could make sense here, i.e.:

```suggestion
   UnknownModuleError UnknownModuleDetails
     deriving (Show, Eq, Ord, Read, Generic, Aeson.ToJSON, Aeson.FromJSON)
```
and we can add new variants later.

File: ghcide/session-loader/Development/IDE/Session/Diagnostics.hs [hunk 3]
```diff
@@ -33,21 +47,34 @@ renderCradleError cradleError cradle nfp =
...
   in
   if HieBios.isCabalCradle cradle
-     then noDetails & fdLspDiagnosticL %~ \diag -> diag{_data_ = Just $ Aeson.toJSON CradleErrorDetails{cabalProjectFiles=absDeps}}
+     then noDetails & fdLspDiagnosticL %~ \diag -> diag
+            { _data_ = Just $ Aeson.toJSON CradleErrorDetails
+                { cabalProjectFiles = absDeps
+                , structuredError   =
+                    case mkUnknownModuleDetails of
+                      Nothing -> Nothing
+                      Just u  -> Just (StructuredErrors (Just u))
```
Comment (VeryMilkyJoe) [inline ghcide/session-loader/Development/IDE/Session/Diagnostics.hs]:
```suggestion
                    fmap UnknownModuleError mkUnknownModuleDetails 
```

File: ghcide/session-loader/Development/IDE/Session/Diagnostics.hs [hunk 4]
```diff
@@ -33,21 +47,34 @@ renderCradleError cradleError cradle nfp =
...
     absDeps = fmap (cradleRootDir cradle </>) (cradleErrorDependencies cradleError)
     userFriendlyMessage :: [String]
     userFriendlyMessage
-      | HieBios.isCabalCradle cradle = fromMaybe ms $ fileMissingMessage <|> mkUnknownModuleMessage
+      | HieBios.isCabalCradle cradle = fromMaybe ms $ fileMissingMessage <|> (unknownModuleMessage (fromNormalizedFilePath nfp) <$ mkUnknownModuleDetails)
       | otherwise = ms
 
-    mkUnknownModuleMessage :: Maybe [String]
-    mkUnknownModuleMessage
+    -- Produce structured details when unknown module error detected;
```
Comment (VeryMilkyJoe) [inline ghcide/session-loader/Development/IDE/Session/Diagnostics.hs]:
```suggestion
    -- Produce structured details when unknown module error is detected
```

File: ghcide/session-loader/Development/IDE/Session/Diagnostics.hs [hunk 5]
```diff
@@ -21,6 +21,20 @@ data CradleErrorDetails =
...
+
+data StructuredErrors =
+  StructuredErrors
+    { unknownModule :: Maybe UnknownModuleDetails
+    } deriving (Show, Eq, Ord, Read, Generic, Aeson.ToJSON, Aeson.FromJSON)
+
+data UnknownModuleDetails =
+  UnknownModuleDetails
+    { moduleFilePath   :: FilePath
+    , suggestedModName :: String
```
Comment (VeryMilkyJoe) [inline ghcide/session-loader/Development/IDE/Session/Diagnostics.hs]: Being consistent with using either "module" or "mod" in the naming would be nice.

File: ghcide/session-loader/Development/IDE/Session/Diagnostics.hs (hunk 1 above)
Comment (vidit-od) [reply ghcide/session-loader/Development/IDE/Session/Diagnostics.hs]: Sounds good to me :)
