### PR TITLE
Fix regression in Eval plugin and add test

### LINKED ISSUE #2438: Eval plugin fails in modules with transitive local dependency ("use GetModSummary instead of GetModSummaryWithoutTimestamps")
### Your environment

Which OS do you use: ArchLinux (using ghcup + cabal)
Which lsp-client do you use: VS Codium
Describe your project: https://github.com/ratherforky/hls-eval-bug

### Steps to reproduce

Given some local modules A, B, and C where:
- A depends on B
- B depends on C

In A, evaluate something in a comment using the eval plugin, eg.

```Haskell
module A where
import B ()
-- >>> 'A'
```

```Haskell
module B where
import C ()
```

```Haskell
module C where
```

### Expected behaviour

The comment in A should be evaluated successfully, resulting in:

```Haskell
-- >>> 'A'
-- 'A'
```

### Actual behaviour

<details>
<summary>
Despite HLS having no other issues, trying to evaluate any code comment in A leads to an error: "use GetModSummary instead of GetModSummaryWithoutTimestamps"
</summary>

```
2021-12-03 16:18:37.742615844 [ThreadId 26625] INFO hls:	finish: eval (took 0.00s)
2021-12-03 16:18:37.742750111 [ThreadId 26653] INFO hls:	finish: runEvalCmd.getModSummary (took 0.00s)
[Error - 16:18:37] Request workspace/executeCommand failed.
  Message: use GetModSummary instead of GetModSummaryWithoutTimestamps
CallStack (from HasCallStack):
  error, called at src/Development/IDE/Core/Rules.hs:845:34 in ghcide-1.5.0.1-inplace:Development.IDE.Core.Rules
  Code: -32603
```
</details>

Important things to note:
- It seems to have nothing to do with the actual code in any of the modules, including what you try to evaluate in A. It seems like it's the dependencies between the modules alone which cause the bug.
- Comment evaluation in B and C works without issue.
- Everything works fine in the repl
- HLS doesn't crash, it continues to work fine afterwards just as it did before
- If A imports B _and_ C, it still fails
- If A imports _only_ C, it works fine

### Include debug information
Execute in the root of your project the command `haskell-language-server-wrapper --debug`:
<details>
<summary>
Debug output: Everything works fine, the error happens at runtime when trying to evaluate a comment.
</summary>

```
Found "~/Playground/hls-eval-bug/hie.yaml" for "~/Playground/hls-eval-bug/a"
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper) Version 1.5.1.0, Git revision 745ef26f406dbdd5e4a538585f8519af9f1ccb09 (dirty) x86_64 ghc-8.10.7
Current directory: ~/Playground/hls-eval-bug
Operating system: linux
Arguments: ["--debug"]
Cradle directory: ~/Playground/hls-eval-bug
Cradle type: Cabal

Tool versions found on the $PATH
cabal:		3.6.2.0
stack:		2.7.3
ghc:		8.10.7


Consulting the cradle to get project GHC version...
Project GHC version: 8.10.7
haskell-language-server exe candidates: ["haskell-language-server-8.10.7","haskell-language-server"]
Launching haskell-language-server exe at:~/.ghcup/bin/haskell-language-server-8.10.7
haskell-language-server version: 1.5.1.0 (GHC: 8.10.7) (PATH: ~/.ghcup/bin/haskell-language-server-8.10.7~1.5.1) (GIT hash: 745ef26f406dbdd5e4a538585f8519af9f1ccb09)
 ghcide setup tester in ~/Playground/hls-eval-bug.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/4: Finding files to test in ~/Playground/hls-eval-bug
Found 3 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle
  (~/Playground/hls-eval-bug/hie.yaml)

Step 3/4: Initializing the IDE
2021-12-03 16:56:58.483762563 [ThreadId 7] DEBUG hls:	Initializing exports map from hiedb

Step 4/4: Type checki2021-12-03 16:56:58.484603908 [ThreadId 7] DEBUG hls:	Done initializing exports map from hiedb (0)
ng the files
2021-12-03 16:56:58.48525284 [ThreadId 36] INFO hls:	Consulting the cradle for "src/B.hs"
2021-12-03 16:56:58.485474744 [ThreadId 36] DEBUG hls:	Output from setting up the cradle Cradle {cradleRootDir = "~/Playground/hls-eval-bug", cradleOptsProg = CradleAction: Cabal}
2021-12-03 16:56:58.506165268 [ThreadId 42] INFO hie-bios:	Build profile: -w ghc-8.10.7 -O1
2021-12-03 16:56:58.506280607 [ThreadId 42] INFO hie-bios:	In order, the following will be built (use -v for more details):
2021-12-03 16:56:58.506331631 [ThreadId 42] INFO hie-bios:	 - hls-eval-bug-0.1.0.0 (lib) (first run)
2021-12-03 16:56:58.534164876 [ThreadId 42] INFO hie-bios:	Preprocessing library for hls-eval-bug-0.1.0.0..
2021-12-03 16:56:58.629292403 [ThreadId 36] DEBUG hls:	Session loading result: Right (ComponentOptions {componentOptions = ["-fbuilding-cabal-package","-O0","-outputdir","~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build","-odir","~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build","-hidir","~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build","-stubdir","~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build","-i","-i~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build","-isrc","-i~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build/autogen","-i~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build/global-autogen","-I~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build/autogen","-I~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build/global-autogen","-I~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build","-optP-include","-optP~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build/autogen/cabal_macros.h","-this-unit-id","hls-eval-bug-0.1.0.0-inplace","-hide-all-packages","-Wmissing-home-modules","-no-user-package-db","-package-db","~/.cabal/store/ghc-8.10.7/package.db","-package-db","~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/packagedb/ghc-8.10.7","-package-db","~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/package.conf.inplace","-package-id","base-4.14.3.0","-XHaskell2010","A","B","C","-hide-all-packages"], componentRoot = "~/Playground/hls-eval-bug", componentDependencies = ["hls-eval-bug.cabal","cabal.project","cabal.project.local"]},"~/.ghcup/ghc/8.10.7/lib/ghc-8.10.7")
2021-12-03 16:56:58.679088037 [ThreadId 36] INFO hls:	Using interface files cache dir: ~/.cache/ghcide/hls-eval-bug-0.1.0.0-inplace-cc4bab3f12043689811e3c608eb89f6af3d3c9bb
2021-12-03 16:56:58.679556235 [ThreadId 36] INFO hls:	Making new HscEnv[hls-eval-bug-0.1.0.0-inplace]
2021-12-03 16:56:58.695769401 [ThreadId 36] DEBUG hls:	New Component Cache HscEnvEq: (([],Just HscEnvEq 5),fromList [("~/Playground/hls-eval-bug/hie.yaml",Just 2021-12-03 15:57:43.239767852 UTC),("cabal.project",Nothing),("cabal.project.local",Nothing),("hls-eval-bug.cabal",Just 2021-12-03 16:52:16.64274343 UTC)])
2021-12-03 16:56:58.712127938 [ThreadId 36] DEBUG hls:	Known files updated: fromList [(TargetFile NormalizedFilePath "~/Playground/hls-eval-bug/src/B.hs",fromList ["~/Playground/hls-eval-bug/src/B.hs"]),(TargetModule A,fromList ["~/Playground/hls-eval-bug/src/A.hs"]),(TargetModule C,fromList ["~/Playground/hls-eval-bug/src/C.hs"]),(TargetModule B,fromList ["~/Playground/hls-eval-bug/src/B.hs"])]
2021-12-03 16:56:58.712444886 [ThreadId 10] DEBUG hls:	Finishing build session(exception: AsyncCancelled)
2021-12-03 16:56:58.712582245 [ThreadId 36] DEBUG hls:	Restarting build session due to new component with queue ["User TypeCheck"] for keys [GhcSessionIO; ,GetKnownTargets; ] (aborting the previous one took 0.00s)
2021-12-03 16:56:58.713192711 [ThreadId 58] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "~/Playground/hls-eval-bug/src/C.hs"
2021-12-03 16:56:58.713603559 [ThreadId 59] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "~/Playground/hls-eval-bug/src/A.hs"
2021-12-03 16:56:58.713790677 [ThreadId 57] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "~/Playground/hls-eval-bug/src/B.hs"
2021-12-03 16:56:58.887952289 [ThreadId 79] INFO hls:	finish: User TypeCheck (took 0.17s)
2021-12-03 16:56:58.889555949 [ThreadId 255] INFO hls:	finish: GetHie (took 0.00s)
2021-12-03 16:56:58.889718497 [ThreadId 270] INFO hls:	finish: GenerateCore (took 0.00s)

Completed (3 files worked, 0 files failed)
```
</details>

Paste the logs from the lsp-client:

<details>
<summary>
LSP logs (included all logs in case they're useful, but actual error is right near the end):
</summary>

```
[client][INFO] Searching for server executables haskell-language-server-wrapper,haskell-language-server in $PATH
[client][INFO] Found server executable in $PATH: haskell-language-server-wrapper
[client][INFO] Activating the language server in the workspace folder: ~/Playground/hls-eval-bug
[client][INFO] run command: haskell-language-server-wrapper --lsp -d
[client][INFO] debug command: haskell-language-server-wrapper --lsp -d
[client][INFO] document selector patten: ~/Playground/hls-eval-bug/**/*
[client][INFO] Starting language server
Found "~/Playground/hls-eval-bug/hie.yaml" for "~/Playground/hls-eval-bug/a"
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper) Version 1.5.1.0, Git revision 745ef26f406dbdd5e4a538585f8519af9f1ccb09 (dirty) x86_64 ghc-8.10.7
Current directory: ~/Playground/hls-eval-bug
Operating system: linux
Arguments: ["--lsp","-d"]
Cradle directory: ~/Playground/hls-eval-bug
Cradle type: Cabal

Tool versions found on the $PATH
cabal:		3.6.2.0
stack:		2.7.3
ghc:		8.10.7


Consulting the cradle to get project GHC version...
Project GHC version: 8.10.7
haskell-language-server exe candidates: ["haskell-language-server-8.10.7","haskell-language-server"]
Launching haskell-language-server exe at:~/.ghcup/bin/haskell-language-server-8.10.7
haskell-language-server version: 1.5.1.0 (GHC: 8.10.7) (PATH: ~/.ghcup/bin/haskell-language-server-8.10.7~1.5.1) (GIT hash: 745ef26f406dbdd5e4a538585f8519af9f1ccb09)
Starting (haskell-language-server)LSP server...
  with arguments: GhcideArguments {argsCommand = LSP, argsCwd = Nothing, argsShakeProfiling = Nothing, argsTesting = False, argsExamplePlugin = False, argsDebugOn = True, argsLogFile = Nothing, argsThreads = 0, argsProjectGhcVersion = False}
  with plugins: [PluginId "pragmas",PluginId "floskell",PluginId "fourmolu",PluginId "tactics",PluginId "ormolu",PluginId "stylish-haskell",PluginId "retrie",PluginId "brittany",PluginId "callHierarchy",PluginId "class",PluginId "haddockComments",PluginId "eval",PluginId "importLens",PluginId "refineImports",PluginId "moduleName",PluginId "hlint",PluginId "splice",PluginId "ghcide-hover-and-symbols",PluginId "ghcide-code-actions-imports-exports",PluginId "ghcide-code-actions-type-signatures",PluginId "ghcide-code-actions-bindings",PluginId "ghcide-code-actions-fill-holes",PluginId "ghcide-completions",PluginId "ghcide-type-lenses",PluginId "ghcide-core"]
  in directory: ~/Playground/hls-eval-bug
 2021-12-03 17:11:05.117923807 [ThreadId 4] INFO hls:	Starting LSP server...
2021-12-03 17:11:05.118042925 [ThreadId 4] INFO hls:	If you are seeing this in a terminal, you probably should have run WITHOUT the --lsp option!
2021-12-03 17:11:05.119463651 [ThreadId 7] INFO hls:	Started LSP server in 0.00s
2021-12-03 17:11:05.123547866 [ThreadId 7] DEBUG hls:	setInitialDynFlags cradle: Cradle {cradleRootDir = "~/Playground/hls-eval-bug", cradleOptsProg = CradleAction: Cabal}
2021-12-03 17:11:05.208580264 [ThreadId 7] DEBUG hls:	runSubset: True
2021-12-03 17:11:05.208742894 [ThreadId 13] DEBUG hls:	Initializing exports map from hiedb
2021-12-03 17:11:05.20899941 [ThreadId 7] INFO hls:	Registering ide configuration: IdeConfiguration {workspaceFolders = fromList [NormalizedUri (-6717748465680084564) "file://~/Playground/hls-eval-bug"], clientSettings = hashed Nothing}
2021-12-03 17:11:05.213640794 [ThreadId 13] DEBUG hls:	Done initializing exports map from hiedb (0)
2021-12-03 17:11:05.244574134 [ThreadId 15] DEBUG hls:	Configuration changed: Object (fromList [("haskell",Object (fromList [("checkProject",Bool True),("formattingProvider",String "ormolu"),("indentationRules",Object (fromList [("enabled",Bool True)])),("logFile",String ""),("maxCompletions",Number 40.0),("openDocumentationInHackage",Bool True),("openSourceInHackage",Bool True),("plugin",Object (fromList [("class",Object (fromList [("globalOn",Bool True)])),("eval",Object (fromList [("globalOn",Bool True)])),("ghcide-completions",Object (fromList [("config",Object (fromList [("autoExtendOn",Bool True),("snippetsOn",Bool True)]))])),("ghcide-type-lenses",Object (fromList [("config",Object (fromList [("mode",Bool True)])),("globalOn",Bool True)])),("haddockComments",Object (fromList [("globalOn",Bool True)])),("hlint",Object (fromList [("codeActionsOn",Bool False),("config",Object (fromList [("flags",Array [])])),("diagnosticsOn",Bool False)])),("importLens",Object (fromList [("codeActionsOn",Bool True),("codeLensOn",Bool True)])),("moduleName",Object (fromList [("globalOn",Bool True)])),("pragmas",Object (fromList [("codeActionsOn",Bool True),("completionOn",Bool True)])),("refineImports",Object (fromList [("globalOn",Bool True)])),("retrie",Object (fromList [("globalOn",Bool True)])),("splice",Object (fromList [("globalOn",Bool True)])),("tactics",Object (fromList [("config",Object (fromList [("auto_gas",Number 4.0),("hole_severity",Null),("max_use_ctor_actions",Number 5.0),("proofstate_styling",Bool True),("timeout_duration",Number 2.0)])),("globalOn",Bool True)]))])),("releasesURL",String ""),("serverExecutablePath",String ""),("serverExtraArgs",String ""),("trace",Object (fromList [("client",String "debug"),("server",String "messages")])),("updateBehavior",String "keep-up-to-date")]))])
2021-12-03 17:11:05.244899057 [ThreadId 18] DEBUG hls:	Finishing build session(exception: AsyncCancelled)
2021-12-03 17:11:05.244929708 [ThreadId 15] DEBUG hls:	Restarting build session due to config change with queue [] for keys [GetClientSettings; ] (aborting the previous one took 0.00s)
2021-12-03 17:11:05.245314207 [ThreadId 15] DEBUG hls:	Set files of interest to: fromList [(NormalizedFilePath "~/Playground/hls-eval-bug/src/A.hs",Modified {firstOpen = True})]
2021-12-03 17:11:05.246482612 [ThreadId 15] DEBUG hls:	Restarting build session due to ~/Playground/hls-eval-bug/src/A.hs (modified) with queue [] for keys [IsFileOfInterest; ~/Playground/hls-eval-bug/src/A.hs,GetModificationTime; ~/Playground/hls-eval-bug/src/A.hs] (aborting the previous one took 0.00s)
2021-12-03 17:11:05.246644059 [ThreadId 33] DEBUG hls:	Finishing build session(exception: AsyncCancelled)
2021-12-03 17:11:05.246623803 [ThreadId 15] DEBUG hls:	Opened text document: file://~/Playground/hls-eval-bug/src/A.hs
2021-12-03 17:11:05.247228413 [ThreadId 74] INFO hls:	Consulting the cradle for "src/A.hs"
2021-12-03 17:11:05.247472954 [ThreadId 77] DEBUG hls:	Output from setting up the cradle Cradle {cradleRootDir = "~/Playground/hls-eval-bug", cradleOptsProg = CradleAction: Cabal}
2021-12-03 17:11:05.270409971 [ThreadId 83] INFO hie-bios:	Build profile: -w ghc-8.10.7 -O1
2021-12-03 17:11:05.27051146 [ThreadId 83] INFO hie-bios:	In order, the following will be built (use -v for more details):
2021-12-03 17:11:05.270593502 [ThreadId 83] INFO hie-bios:	 - hls-eval-bug-0.1.0.0 (lib) (first run)
2021-12-03 17:11:05.29943062 [ThreadId 83] INFO hie-bios:	Preprocessing library for hls-eval-bug-0.1.0.0..
2021-12-03 17:11:05.392846555 [ThreadId 74] DEBUG hls:	Session loading result: Right (ComponentOptions {componentOptions = ["-fbuilding-cabal-package","-O0","-outputdir","~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build","-odir","~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build","-hidir","~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build","-stubdir","~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build","-i","-i~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build","-isrc","-i~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build/autogen","-i~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build/global-autogen","-I~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build/autogen","-I~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build/global-autogen","-I~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build","-optP-include","-optP~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/build/autogen/cabal_macros.h","-this-unit-id","hls-eval-bug-0.1.0.0-inplace","-hide-all-packages","-Wmissing-home-modules","-no-user-package-db","-package-db","~/.cabal/store/ghc-8.10.7/package.db","-package-db","~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/packagedb/ghc-8.10.7","-package-db","~/.cache/hie-bios/dist-hls-eval-bug-2004cdb0343334caded9985ff3720c0d/build/x86_64-linux/ghc-8.10.7/hls-eval-bug-0.1.0.0/package.conf.inplace","-package-id","base-4.14.3.0","-XHaskell2010","A","B","C","-hide-all-packages"], componentRoot = "~/Playground/hls-eval-bug", componentDependencies = ["hls-eval-bug.cabal","cabal.project","cabal.project.local"]},"~/.ghcup/ghc/8.10.7/lib/ghc-8.10.7")
2021-12-03 17:11:05.435876326 [ThreadId 74] INFO hls:	Using interface files cache dir: ~/.cache/ghcide/hls-eval-bug-0.1.0.0-inplace-cc4bab3f12043689811e3c608eb89f6af3d3c9bb
2021-12-03 17:11:05.436112408 [ThreadId 74] INFO hls:	Making new HscEnv[hls-eval-bug-0.1.0.0-inplace]
2021-12-03 17:11:05.443493699 [ThreadId 74] DEBUG hls:	New Component Cache HscEnvEq: (([],Just HscEnvEq 7),fromList [("~/Playground/hls-eval-bug/hie.yaml",Just 2021-12-03 15:57:43.239767852 UTC),("cabal.project",Nothing),("cabal.project.local",Nothing),("hls-eval-bug.cabal",Just 2021-12-03 16:52:16.64274343 UTC)])
2021-12-03 17:11:05.450903173 [ThreadId 74] DEBUG hls:	Known files updated: fromList [(TargetModule A,fromList ["~/Playground/hls-eval-bug/src/A.hs"]),(TargetFile NormalizedFilePath "~/Playground/hls-eval-bug/src/A.hs",fromList ["~/Playground/hls-eval-bug/src/A.hs"]),(TargetModule C,fromList ["~/Playground/hls-eval-bug/src/C.hs"]),(TargetModule B,fromList ["~/Playground/hls-eval-bug/src/B.hs"])]
2021-12-03 17:11:05.451177232 [ThreadId 55] DEBUG hls:	Finishing build session(exception: AsyncCancelled)
2021-12-03 17:11:05.451160054 [ThreadId 74] DEBUG hls:	Restarting build session due to new component with queue [] for keys [GhcSessionIO; ,IsFileOfInterest; ~/Playground/hls-eval-bug/src/A.hs,GetModificationTime; ~/Playground/hls-eval-bug/src/A.hs,GetKnownTargets; ] (aborting the previous one took 0.00s)
2021-12-03 17:11:05.475473449 [ThreadId 106] DEBUG hls:	finish: InitialLoad (took 0.02s)
2021-12-03 17:11:05.49974733 [ThreadId 274] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:121:15 "fp" "~/Playground/hls-eval-bug/src/A.hs"
2021-12-03 17:11:05.499938931 [ThreadId 279] INFO hls:	finish: Wingman.getIdeDynflags.GetModSummaryWithoutTimestamps (took 0.00s)
2021-12-03 17:11:05.500325023 [ThreadId 284] INFO hls:	finish: ModuleName.ghcSession (took 0.00s)
2021-12-03 17:11:05.500455862 [ThreadId 287] INFO hls:	finish: codeLens.TypeCheck (took 0.00s)
2021-12-03 17:11:05.500919828 [ThreadId 294] INFO hls:	finish: ModuleName.GetParsedModule (took 0.00s)
2021-12-03 17:11:05.50113592 [ThreadId 282] INFO hls:	finish:  (took 0.00s)
2021-12-03 17:11:05.501178997 [ThreadId 291] INFO hls:	finish: codeLens.GetBindings (took 0.00s)
2021-12-03 17:11:05.501347587 [ThreadId 280] INFO hls:	finish: eval.GetParsedModuleWithComments (took 0.00s)
2021-12-03 17:11:05.501374789 [ThreadId 288] INFO hls:	finish: Wingman.codeLensProvider.GetAnnotatedParsedSource (took 0.00s)
2021-12-03 17:11:05.501506982 [ThreadId 302] INFO hls:	finish: codeLens.GetGlobalBindingTypeSigs (took 0.00s)
2021-12-03 17:11:05.501495356 [ThreadId 274] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:121:15 "comments" "Comments {lineComments = fromList [(Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 14}},RawLineComment {getRawLineComment = \"-- import C ()\"}),(Range {_start = Position {_line = 5, _character = 0}, _end = Position {_line = 5, _character = 10}},RawLineComment {getRawLineComment = \"-- >>> 'A'\"})], blockComments = fromList []}"
2021-12-03 17:11:05.501646652 [ThreadId 312] INFO hls:	finish: Wingman.codeLensProvider.GetBindings (took 0.00s)
2021-12-03 17:11:05.50164203 [ThreadId 274] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:121:15 "Tests" "1 tests in 2 sections 0 setups 1 lenses."
2021-12-03 17:11:05.501765065 [ThreadId 274] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:121:15 "tests" "0.00s"
2021-12-03 17:11:05.501822164 [ThreadId 274] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:121:15 "codeLens" "0.00s"
2021-12-03 17:11:05.501913183 [ThreadId 317] INFO hls:	finish: Wingman.emptyCaseScrutinees.TypeCheck (took 0.00s)
2021-12-03 17:11:05.501998725 [ThreadId 319] INFO hls:	finish: Wingman.emptyCaseScrutinees.GhcSessionDeps (took 0.00s)
2021-12-03 17:11:05.502486839 [ThreadId 281] INFO hls:	finish: RefineImports (took 0.00s)
2021-12-03 17:11:06.23719102 [ThreadId 330] INFO hls:	finish: Outline (took 0.00s)
2021-12-03 17:11:08.508187832 [ThreadId 336] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:121:15 "fp" "~/Playground/hls-eval-bug/src/A.hs"
2021-12-03 17:11:08.508588189 [ThreadId 341] INFO hls:	finish: eval.GetParsedModuleWithComments (took 0.00s)
2021-12-03 17:11:08.508787176 [ThreadId 342] INFO hls:	finish: Wingman.getIdeDynflags.GetModSummaryWithoutTimestamps (took 0.00s)
2021-12-03 17:11:08.509110689 [ThreadId 343] INFO hls:	finish:  (took 0.00s)
2021-12-03 17:11:08.509358172 [ThreadId 344] INFO hls:	finish: codeLens.TypeCheck (took 0.00s)
2021-12-03 17:11:08.509525416 [ThreadId 345] INFO hls:	finish: RefineImports (took 0.00s)
2021-12-03 17:11:08.509469309 [ThreadId 336] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:121:15 "comments" "Comments {lineComments = fromList [(Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 14}},RawLineComment {getRawLineComment = \"-- import C ()\"}),(Range {_start = Position {_line = 5, _character = 0}, _end = Position {_line = 5, _character = 10}},RawLineComment {getRawLineComment = \"-- >>> 'A'\"})], blockComments = fromList []}"
2021-12-03 17:11:08.509699057 [ThreadId 346] INFO hls:	finish: ModuleName.ghcSession (took 0.00s)
2021-12-03 17:11:08.509774467 [ThreadId 336] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:121:15 "Tests" "1 tests in 2 sections 0 setups 1 lenses."
2021-12-03 17:11:08.509863019 [ThreadId 347] INFO hls:	finish: codeLens.GetBindings (took 0.00s)
2021-12-03 17:11:08.510041588 [ThreadId 336] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:121:15 "tests" "0.00s"
2021-12-03 17:11:08.510084003 [ThreadId 348] INFO hls:	finish: codeLens.GetGlobalBindingTypeSigs (took 0.00s)
2021-12-03 17:11:08.510168702 [ThreadId 336] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:121:15 "codeLens" "0.00s"
2021-12-03 17:11:08.5105059 [ThreadId 350] INFO hls:	finish: Wingman.codeLensProvider.GetBindings (took 0.00s)
2021-12-03 17:11:08.510705219 [ThreadId 351] INFO hls:	finish: Wingman.emptyCaseScrutinees.TypeCheck (took 0.00s)
2021-12-03 17:11:08.510410998 [ThreadId 349] INFO hls:	finish: Wingman.codeLensProvider.GetAnnotatedParsedSource (took 0.00s)
2021-12-03 17:11:08.510884855 [ThreadId 352] INFO hls:	finish: Wingman.emptyCaseScrutinees.GhcSessionDeps (took 0.00s)
2021-12-03 17:11:08.51119466 [ThreadId 353] INFO hls:	finish: ModuleName.GetParsedModule (took 0.00s)
2021-12-03 17:11:27.158576992 [ThreadId 358] DEBUG hls:	Restarting build session due to Eval with queue [] for keys [NeedsCompilation; ~/Playground/hls-eval-bug/src/A.hs] (aborting the previous one took 0.00s)
2021-12-03 17:11:27.158713637 [ThreadId 92] DEBUG hls:	Finishing build session(exception: AsyncCancelled)
2021-12-03 17:11:27.169225844 [ThreadId 374] INFO hls:	finish: eval (took 0.01s)
2021-12-03 17:11:27.169365065 [ThreadId 409] INFO hls:	finish: runEvalCmd.getModSummary (took 0.00s)
2021-12-03 17:11:27.173577609 [ThreadId 358] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:188:15 "QUICKCHECK NEEDS" False
2021-12-03 17:11:27.173667374 [ThreadId 358] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:188:15 "QUICKCHECK HAS" False
2021-12-03 17:11:27.173761406 [ThreadId 358] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:188:15 "setTarget" Right ()
2021-12-03 17:11:27.174896349 [ThreadId 357] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:188:15 "evalCmd" "0.02s"
[Error - 17:11:27] Request workspace/executeCommand failed.
  Message: use GetModSummary instead of GetModSummaryWithoutTimestamps
CallStack (from HasCallStack):
  error, called at src/Development/IDE/Core/Rules.hs:845:34 in ghcide-1.5.0.1-inplace:Development.IDE.Core.Rules
  Code: -32603 
2021-12-03 17:11:27.401495978 [ThreadId 422] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:121:15 "fp" "~/Playground/hls-eval-bug/src/A.hs"
2021-12-03 17:11:27.401821669 [ThreadId 423] INFO hls:	finish: Wingman.getIdeDynflags.GetModSummaryWithoutTimestamps (took 0.00s)
2021-12-03 17:11:27.402105762 [ThreadId 424] INFO hls:	finish: eval.GetParsedModuleWithComments (took 0.00s)
2021-12-03 17:11:27.402487499 [ThreadId 422] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:121:15 "comments" "Comments {lineComments = fromList [(Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 14}},RawLineComment {getRawLineComment = \"-- import C ()\"}),(Range {_start = Position {_line = 5, _character = 0}, _end = Position {_line = 5, _character = 10}},RawLineComment {getRawLineComment = \"-- >>> 'A'\"})], blockComments = fromList []}"
2021-12-03 17:11:27.402752693 [ThreadId 422] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:121:15 "Tests" "1 tests in 2 sections 0 setups 1 lenses."
2021-12-03 17:11:27.402905644 [ThreadId 429] INFO hls:	finish: RefineImports (took 0.00s)
2021-12-03 17:11:27.403031316 [ThreadId 422] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:121:15 "tests" "0.00s"
2021-12-03 17:11:27.40323576 [ThreadId 422] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:121:15 "codeLens" "0.00s"
2021-12-03 17:11:27.403521408 [ThreadId 433] INFO hls:	finish: ModuleName.ghcSession (took 0.00s)
2021-12-03 17:11:27.40361448 [ThreadId 434] INFO hls:	finish: codeLens.TypeCheck (took 0.00s)
2021-12-03 17:11:27.403782649 [ThreadId 436] INFO hls:	finish: Wingman.codeLensProvider.GetAnnotatedParsedSource (took 0.00s)
2021-12-03 17:11:27.404249868 [ThreadId 439] INFO hls:	finish: Wingman.codeLensProvider.GetBindings (took 0.00s)
2021-12-03 17:11:27.404553001 [ThreadId 443] INFO hls:	finish: Wingman.emptyCaseScrutinees.TypeCheck (took 0.00s)
2021-12-03 17:11:27.404944489 [ThreadId 435] INFO hls:	finish:  (took 0.00s)
2021-12-03 17:11:27.405038351 [ThreadId 445] INFO hls:	finish: ModuleName.GetParsedModule (took 0.00s)
2021-12-03 17:11:27.405221979 [ThreadId 446] INFO hls:	finish: codeLens.GetBindings (took 0.00s)
2021-12-03 17:11:27.405301531 [ThreadId 447] INFO hls:	finish: Wingman.emptyCaseScrutinees.GhcSessionDeps (took 0.00s)
2021-12-03 17:11:27.405409058 [ThreadId 448] INFO hls:	finish: codeLens.GetGlobalBindingTypeSigs (took 0.00s)
2021-12-03 17:12:14.645824463 [ThreadId 457] INFO hls:	finish: Outline (took 0.00s)

```
</details>

### PR DESCRIPTION
**Pull request by pepeiborra**
Fixes #2438 and includes a regression test

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2441"></a>

### CODE REVIEW

**Review by jneira — APPROVED** [review]
thanks for the fix

File: ghcide/src/Development/IDE/Core/Rules.hs [hunk 1]
```diff
@@ -697,22 +697,30 @@ loadGhcSession ghcSessionDepsConfig = do
                 Nothing -> LBS.toStrict $ B.encode (hash (snd val))
         return (Just cutoffHash, val)
 
-    defineNoDiagnostics $ \GhcSessionDeps file -> do
-        env <- use_ GhcSession file
-        ghcSessionDepsDefinition ghcSessionDepsConfig env file
+    defineEarlyCutoff $ RuleWithCustomNewnessCheck (<=) $
+    -- This rule uses a custom newness check that relies on the derived 'Ord' instance:
```
Comment (michaelpj) [inline ghcide/src/Development/IDE/Core/Rules.hs:701]: But... there's no `Ord` instance for `GhcSessionDeps`? Am I missing something?

Also, this is cute, but maybe it would be safer to just write a trivial but explicit function...

File: ghcide/src/Development/IDE/Core/RuleTypes.hs [hunk 2]
```diff
@@ -407,9 +408,15 @@ data GhcSession = GhcSession
 instance Hashable GhcSession
 instance NFData   GhcSession
 
-data GhcSessionDeps = GhcSessionDeps deriving (Eq, Show, Typeable, Generic)
-instance Hashable GhcSessionDeps
-instance NFData   GhcSessionDeps
+newtype GhcSessionDeps = GhcSessionDeps_
+    { -- | Load full ModSummary values in the GHC session.
+        -- Required for interactive evaluation, but leads to more cache invalidations
+        fullModSummary :: Bool
```
Comment (michaelpj) [inline ghcide/src/Development/IDE/Core/RuleTypes.hs:414]: Why do we put some things here and some things in `GhcSessionDepsConfig`? Should this field just be a `GhcSessionDepsConfig`, with a slightly-more-complex function for checking newness?

Comment (pepeiborra) [reply ghcide/src/Development/IDE/Core/RuleTypes.hs:414]: `fullModSummary` is part of the build key because it has an effect on the build result.
`checkForImportCycles` is part of the config because it only effects whether an exception is thrown on module cycles (and how expensive the build is), but not the build result

File: ghcide/src/Development/IDE/Core/Rules.hs (hunk 1 above)
Comment (pepeiborra) [reply ghcide/src/Development/IDE/Core/Rules.hs:701]: Hmm, this is actually quite tricky, so I'm going to retract it and leave it for future work. The `Ord` instance is actually over the `Bytestring` value returned for early cutoff, which in this rule is `Nothing`, so this is absolutely clowny
