### PR TITLE
Fix misplaced inlay hints by applying PositionMapping

### LINKED ISSUE #4561: Inlay Hints for imports seem to be misplaced
Image

This seems to happen if typechecking takes a long time, like on the GHC codebase.

Perhaps the Position Mapping is not applied correctly?

### PR DESCRIPTION
**Pull request by jetjinser**
resolve #4561.

fixed `hls-explicit-imports-plugin`, `hls-explicit-record-fields-plugin`.

### CODE REVIEW

File: plugins/hls-explicit-record-fields-plugin/src/Ide/Plugin/ExplicitFields.hs [hunk 1]
```diff
@@ -319,11 +320,11 @@ collectNamesRule = defineNoDiagnostics mempty $ \CollectNames nfp -> runMaybeT $
...
 getNames :: TcModuleResult -> UniqFM Name [Name]
-#if __GLASGOW_HASKELL__ < 910
+
 getNames (tmrRenamed -> (group,_,_,_))   = collectNames group
-#else
-getNames (tmrRenamed -> (group,_,_,_,_)) = collectNames group
-#endif
+
+
+
```
Comment (fendor) [inline plugins/hls-explicit-record-fields-plugin/src/Ide/Plugin/ExplicitFields.hs:327]: Did some formatter mess you up?

**Review by fendor — APPROVED** [review]
LGTM, didn't check this works correctly now, and I am not sure whether we even could add a test for this that isn't incredibly flaky.

File: plugins/hls-explicit-record-fields-plugin/src/Ide/Plugin/ExplicitFields.hs [hunk 2]
```diff
@@ -506,11 +507,11 @@ showRecordPatFlds (ConPat _ _ args) = do
...
     processRecCon _             = Nothing
-#if __GLASGOW_HASKELL__ < 911
+
     getOccName (FieldOcc x _) = Just $ getName x
-#else
-    getOccName (FieldOcc _ x) = Just $ getName (unLoc x)
-#endif
+
+
+
```
Comment (fendor) [inline plugins/hls-explicit-record-fields-plugin/src/Ide/Plugin/ExplicitFields.hs:514]: Revert

File: plugins/hls-explicit-record-fields-plugin/src/Ide/Plugin/ExplicitFields.hs [hunk 3]
```diff
@@ -561,11 +562,11 @@ getRecCons :: LHsExpr GhcTc -> ([RecordInfo], Bool)
 -- because there is a possibility that there were be more than one result per
 -- branch
 
-#if __GLASGOW_HASKELL__ >= 910
-getRecCons (unLoc -> XExpr (ExpandedThingTc a _)) = (collectRecords a, False)
-#else
+
+
+
```
Comment (fendor) [inline plugins/hls-explicit-record-fields-plugin/src/Ide/Plugin/ExplicitFields.hs:567]: Revert

File: plugins/hls-explicit-record-fields-plugin/src/Ide/Plugin/ExplicitFields.hs [hunk 4]
```diff
@@ -593,11 +594,11 @@ getRecCons expr@(unLoc -> app@(HsApp _ _ _)) =
...
     getExprFields (XExpr (ConLikeTc (conLikeFieldLabels -> fls) _ _)) = fls
-#if __GLASGOW_HASKELL__ >= 911
-    getExprFields (XExpr (WrapExpr _ expr)) = getExprFields expr
-#else
+
+
+
     getExprFields (XExpr (WrapExpr (HsWrap _ expr))) = getExprFields expr
-#endif
+
```
Comment (fendor) [inline plugins/hls-explicit-record-fields-plugin/src/Ide/Plugin/ExplicitFields.hs:601]: revert

File: plugins/hls-explicit-record-fields-plugin/src/Ide/Plugin/ExplicitFields.hs (hunk 1 above)
Comment (jetjinser) [reply plugins/hls-explicit-record-fields-plugin/src/Ide/Plugin/ExplicitFields.hs]: Yeah I noticed that but I forgot to push it before the PR 🫠
