### PR TITLE
Leverage last apply-refact improvements in hlint plugin (include getParsedModuleWithComments in ghcide)

### LINKED ISSUE #590: "Apply hint" code action for hlint does not work with default-extensions
### Subject of the issue

If an extension (LambdaCase in my case) is enabled using `default-extensions` in the cabal file and a module is using the extension, using the "Apply hint" code action fails with an error like this:

```
LSP :: Please open an issue in lsp-mode for implementing `98488:hlint:applyAll'.

(error "hlint:applyAll: \"\\\"(RealSrcSpan SrcSpanOneLine \\\\\\\"/tmp/Update98488-114.hs\\\\\\\" 148 23 27,\\\\\\\"Illegal lambda-case (use -XLambdaCase)\\\\\\\")\\\\nCallStack (from HasCallStack):\\\\n  error, called at src/Refact/Internal.hs:84:13 in apply-refact-0.8.2.1-e5ada769d1ed74b27020ceda163d33b8a75e91b8939fcd90cc77787a3840b289:Refact.Internal\\\"\"")
```

### Your environment
* Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`
   ```
   haskell-language-server version: 0.6.0.0 (GHC: 8.8.4) (PATH: /home/axeman/.local/bin/haskell-language-server-8.8.4)
   Tool versions found on the $PATH
   cabal:          3.2.0.0
   stack:          2.3.3
   ghc:            8.8.4
   ```
* Which lsp-client do you use
  Emacs
* Describe your project (alternative: link to the project)
  https://github.com/wireapp/wire-server
* Contents of `hie.yaml`
<details>
<summary>
hie.yaml
</summary>

```
cradle:
  stack:
    - path: ./libs/api-bot/src
      component: api-bot:lib
    - path: ./libs/api-client/src
      component: api-client:lib
    - path: ./tools/api-simulations/lib/src
      component: api-simulations:lib
    - path: ./tools/api-simulations/loadtest/src
      component: api-simulations:exe:api-loadtest
    - path: ./tools/api-simulations/smoketest/src
      component: api-simulations:exe:api-smoketest
    - path: ./tools/db/auto-whitelist/src
      component: auto-whitelist:exe:auto-whitelist
    - path: ./libs/bilge/src
      component: bilge:lib
    - path: ./tools/db/billing-team-member-backfill/src
      component: billing-team-member-backfill:exe:billing-team-member-backfill
    - path: ./tools/bonanza/src
      component: bonanza:lib
    - path: ./tools/bonanza/main/Main.hs
      component: bonanza:exe:bonanza
    - path: ./tools/bonanza/main/KibanaRaw.hs
      component: bonanza:exe:kibana-raw
    - path: ./tools/bonanza/main/Kibanana.hs
      component: bonanza:exe:kibanana
    - path: ./tools/bonanza/test/unit
      component: bonanza:test:bonanza-tests
    - path: ./services/brig/src
      component: brig:lib
    - path: ./services/brig/src/Main.hs
      component: brig:exe:brig
    - path: ./services/brig/index/src/Main.hs
      component: brig:exe:brig-index
    - path: ./services/brig/test/integration
      component: brig:exe:brig-integration
    - path: ./services/brig/schema/src
      component: brig:exe:brig-schema
    - path: ./services/brig/test/unit
      component: brig:test:brig-tests
    - path: ./libs/brig-types/src
      component: brig-types:lib
    - path: ./libs/brig-types/test/unit
      component: brig-types:test:brig-types-tests
    - path: ./services/cannon/src
      component: cannon:lib
    - path: ./services/cannon/src/Main.hs
      component: cannon:exe:cannon
    - path: ./services/cannon/test
      component: cannon:test:cannon-tests
    - path: ./services/cargohold/src
      component: cargohold:lib
    - path: ./services/cargohold/src/Main.hs
      component: cargohold:exe:cargohold
    - path: ./services/cargohold/test/integration
      component: cargohold:exe:cargohold-integration
    - path: ./libs/cargohold-types/src
      component: cargohold-types:lib
    - path: ./libs/cassandra-util/src
      component: cassandra-util:lib
    - path: ./libs/dns-util/src
      component: dns-util:lib
    - path: ./libs/dns-util/test
      component: dns-util:test:spec
    - path: ./libs/extended/src
      component: extended:lib
    - path: ./services/federator/src
      component: federator:lib
    - path: ./services/federator/exec
      component: federator:exe:federator
    - path: ./tools/db/find-undead/src
      component: find-undead:exe:find-undead
    - path: ./services/galley/src
      component: galley:lib
    - path: ./services/galley/src/Main.hs
      component: galley:exe:galley
    - path: ./services/galley/test/integration
      component: galley:exe:galley-integration
    - path: ./services/galley/migrate-data/src
      component: galley:exe:galley-migrate-data
    - path: ./services/galley/schema/src
      component: galley:exe:galley-schema
    - path: ./services/galley/test/unit
      component: galley:test:galley-types-tests
    - path: ./libs/galley-types/src
      component: galley-types:lib
    - path: ./libs/galley-types/test/unit
      component: galley-types:test:galley-types-tests
    - path: ./services/gundeck/src
      component: gundeck:lib
    - path: ./services/gundeck/src/Main.hs
      component: gundeck:exe:gundeck
    - path: ./services/gundeck/test/integration
      component: gundeck:exe:gundeck-integration
    - path: ./services/gundeck/schema/src
      component: gundeck:exe:gundeck-schema
    - path: ./services/gundeck/test/unit
      component: gundeck:test:gundeck-tests
    - path: ./services/gundeck/test/unit
      component: gundeck:bench:gundeck-bench
    - path: ./libs/gundeck-types/src
      component: gundeck-types:lib
    - path: ./libs/hscim/src
      component: hscim:lib
    - path: ./libs/hscim/server
      component: hscim:exe:hscim-server
    - path: ./libs/hscim/test
      component: hscim:test:spec
    - path: ./libs/imports/src
      component: imports:lib
    - path: ./tools/makedeb/src
      component: makedeb:lib
    - path: ./tools/makedeb/src/Main.hs
      component: makedeb:exe:makedeb
    - path: ./libs/metrics-core/src
      component: metrics-core:lib
    - path: ./libs/metrics-wai/src
      component: metrics-wai:lib
    - path: ./tools/db/migrate-sso-feature-flag/src
      component: migrate-sso-feature-flag:exe:migrate-sso-feature-flag
    - path: ./services/proxy/src
      component: proxy:lib
    - path: ./services/proxy/src/Main.hs
      component: proxy:exe:proxy
    - path: ./libs/ropes/src
      component: ropes:lib
    - path: ./tools/db/service-backfill/src
      component: service-backfill:exe:service-backfill
    - path: ./libs/sodium-crypto-sign/src
      component: sodium-crypto-sign:lib
    - path: ./services/spar/src
      component: spar:lib
    - path: ./services/spar/exec
      component: spar:exe:spar
    - path: ./services/spar/test-integration
      component: spar:exe:spar-integration
    - path: ./services/spar/schema/src
      component: spar:exe:spar-schema
    - path: ./services/spar/test
      component: spar:test:spec
    - path: ./libs/ssl-util/src
      component: ssl-util:lib
    - path: ./tools/stern/src
      component: stern:lib
    - path: ./tools/stern/src/Main.hs
      component: stern:exe:stern
    - path: ./libs/tasty-cannon/src
      component: tasty-cannon:lib
    - path: ./libs/types-common/src
      component: types-common:lib
    - path: ./libs/types-common/test
      component: types-common:test:tests
    - path: ./libs/types-common-aws/src
      component: types-common-aws:lib
    - path: ./libs/types-common-journal/src
      component: types-common-journal:lib
    - path: ./libs/wai-utilities/src
      component: wai-utilities:lib
    - path: ./libs/wire-api/src
      component: wire-api:lib
    - path: ./libs/wire-api/test/unit
      component: wire-api:test:wire-api-tests
    - path: ./libs/zauth/src
      component: zauth:lib
    - path: ./libs/zauth/main
      component: zauth:exe:zauth
    - path: ./libs/zauth/test
      component: zauth:test:zauth-unit
```
</details>

### Steps to reproduce

1. Add `LambdaCase` to `default-extensions` in the cabal file.
1. Create a module and write a function which uses LambdaCase.
1. Create another function which will make hlint provide a hint, maybe a redundant `do`.
1. Wait for the LSP server to suggest the code action
1. Apply the code action  

### Expected behaviour

The hlint hint should get applied

### Actual behaviour

hlint complains about LambdaCase.

### Include debug information

<details>
<summary>
LSP logs:
</summary>

```
Found "/home/axeman/workspace/wire-server/hie.yaml" for "/home/axeman/workspace/wire-server/a"
Module "/home/axeman/workspace/wire-server/a" is loaded by Cradle: Cradle {cradleRootDir = "/home/axeman/workspace/wire-server", cradleOptsProg = CradleAction: Stack}
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper) Version 0.6.0.0, Git revision 372a12e797069dc3ac4fa33dcaabe3b992999d7c (dirty) x86_64 ghc-8.10.1
Current directory: /home/axeman/workspace/wire-server
Operating system: linux
Arguments: ["--lsp","-d","-l","/tmp/hls.log"]
Cradle directory: /home/axeman/workspace/wire-server
Cradle type: Stack

Tool versions found on the $PATH
cabal:		3.0.0.0
stack:		2.3.3
ghc:		8.8.4


Consulting the cradle to get project GHC version...
Project GHC version: 8.8.4
haskell-language-server exe candidates: ["haskell-language-server-8.8.4","haskell-language-server-8.8","haskell-language-server"]
Launching haskell-language-server exe at:/home/axeman/.local/bin/haskell-language-server-8.8.4
haskell-language-server version: 0.6.0.0 (GHC: 8.8.4) (PATH: /home/axeman/.local/bin/haskell-language-server-8.8.4)
Starting (haskell-language-server)LSP server...
  with arguments: LspArguments {argLSP = True, argsCwd = Nothing, argFiles = [], argsShakeProfiling = Nothing, argsTesting = False, argsExamplePlugin = False, argsDebugOn = True, argsLogFile = Just "/tmp/hls.log", argsThreads = 0, argsProjectGhcVersion = False}
  with plugins: [PluginId "brittany",PluginId "eval",PluginId "floskell",PluginId "fourmolu",PluginId "ghcide",PluginId "hlint",PluginId "importLens",PluginId "moduleName",PluginId "ormolu",PluginId "pragmas",PluginId "retrie",PluginId "stylish-haskell",PluginId "tactic"]
  in directory: /home/axeman/workspace/wire-server
If you are seeing this in a terminal, you probably should have run ghcide WITHOUT the --lsp option!
 Started LSP server in 0.00s
Output from setting up the cradle Cradle {cradleRootDir = "/home/axeman/workspace/wire-server", cradleOptsProg = CradleAction: Stack}
> galley> configure (lib)
> Configuring galley-0.83.0...
> galley> initial-build-steps (lib)
> The following GHC options are incompatible with GHCi and have not been passed to it: -O2
> Configuring GHCi with the following packages: galley
> /home/axeman/workspace/wire-server/.stack-work/install/x86_64-linux-nix/730229c219acc762949b1a7da64c266b88463ab6c391a6a622e0cbcb64fca603/8.8.4/pkgdb:/home/axeman/.stack/snapshots/x86_64-linux-nix/730229c219acc762949b1a7da64c266b88463ab6c391a6a622e0cbcb64fca603/8.8.4/pkgdb:/nix/store/w30rhw13ji6vkv0zksms5h7897cxvl90-ghc-8.8.4/lib/ghc-8.8.4/package.conf.d
```
</details>

### LINKED ISSUE #597: Applying hlint deindents where clause and remove comments
Applying a hlint fix messes up the `where` block in the function. See gif screenshot below.

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
./haskell-language-server-8.8.4 --probe-tools
haskell-language-server version: 0.6.0.0 (GHC: 8.8.4) (PATH: /home/srid/.local/bin/haskell-language-server-8.8.4) (GIT hash: 61c69fd387281c2222f75f13542eaa2e91cbc1b1)
Tool versions found on the $PATH
cabal:		Not found
stack:		2.5.1
ghc:		Not found

```
Which lsp-client do you use:

VSCode w/ http://github.com/srid/neuron (Markdown.hs)

Contents of `hie.yaml`:
```yaml
cradle:
  cabal:
    - path: "./neuron/src/lib"
      component: "lib:neuron"
    - path: "./neuron/src/app"
      component: "lib:neuron-app-lib"
    - path: "./neuron/src/exe"
      component: "exe:neuron"
    - path: "./neuron/test"
      component: "test:neuron-test"

```

### Steps to reproduce
1. Open Markdown.hs in neuron repo
2. Apply eta reduction hlint for `partitionMarkdown`

### Expected behaviour
only hlint is applied

### Actual behaviour
where clause gets deindented. see gif attachment.
hls-wherebug

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

<details>
<summary>
Debug output:
</summary>

```
<paste your logs here>
```
</details>

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
LSP logs:
</summary>

```
<paste your logs here>
```
</details>

### PR DESCRIPTION
**Pull request by jneira**
This pr take advantage of recent improvements in apply-refact, courtesy of @zliu41:
* for ghc<8.10 we can pass ghc extensions used by the hls ghc session to apply-refact and make it work. So this would fix #590 
  * Issue: https://github.com/mpickering/apply-refact/issues/91
  * pr: https://github.com/mpickering/apply-refact/pull/98 (and https://github.com/mpickering/apply-refact/pull/99)
* for ghc-8.10 we can pass directly the already parsed module instead use a intermediate file that apply-refact has to parse again
  * it will avoid all problems of reparsing the source file, including the previous one
  * pr: https://github.com/mpickering/apply-refact/pull/100
* there had been some bug fixes:
  * https://github.com/mpickering/apply-refact/pull/101 -> it will alliviate #597 
  * https://github.com/mpickering/apply-refact/pull/96 -> closes #597 

We should use a release version of `apply-refact`, if possible

### CODE REVIEW

File: plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs [hunk 1]
```diff
@@ -352,27 +367,47 @@ applyHint ide nfp mhint =
...
+#else
+    mbParsedModule <- liftIO $ runAction' $ getParsedModule nfp
+    res <-
+        case mbParsedModule of
+            Nothing -> throwE "Apply hint: error parsing the module"
+            Just pm -> do
+                let anns = pm_annotations pm
+                let modu = pm_parsed_source pm
+                hsc <- liftIO $ runAction' $ hscEnv <$> use_ GhcSession nfp
+                let dflags = hsc_dflags hsc
```
Comment (pepeiborra) [inline plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs:398]: These `dflags` should probably be coming from the `ModSummary`

File: plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs [hunk 2]
```diff
@@ -352,27 +367,47 @@ applyHint ide nfp mhint =
...
     -- the "Redundant bracket" hint will never be executed
     -- because SrcSpan (1,20,??,??) doesn't contain position (1,13).
-    let fp = fromNormalizedFilePath nfp
-    (_, mbOldContent) <- liftIO $ runAction "hlint" ide $ getFileContents nfp
-    oldContent <- maybe (liftIO $ T.readFile fp) return mbOldContent
-    -- We need to save a file with last edited contents cause `apply-refact`
-    -- doesn't expose a function taking directly contents instead a file path.
-    -- Ideally we should try to expose that function upstream and remove this.
-    res <- liftIO $ withSystemTempFile (takeFileName fp) $ \temp h -> do
+#ifdef GHC_LIB
```
Comment (pepeiborra) [inline plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs:370]: Is anyone using the GHC_LIB path?

Comment (ndmitchell) [reply plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs:370]: Digital Asset were using it for DAML. But they use Ghcide not HLS, so I believe that for HLS its totally unused. I'd just delete it.

Comment (jneira) [reply plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs:370]: `GHC_LIB` is used by hlint for ghc < 8.10 and we are following it closely. This is [the significative part of its .cabal file](https://github.com/mpickering/apply-refact/issues/95#issuecomment-731926466):

```cabal

    if !flag(ghc-lib) && impl(ghc >= 8.10.0) && impl(ghc < 8.11.0)
      build-depends:
        ghc == 8.10.*,
        ghc-boot-th,
        ghc-boot
    else
      build-depends:
          ghc-lib-parser == 8.10.*
```

As ghcide and apply-refact are using the "real" ghc for all versions we have some friction between them.

But your question make me think that maybe we dont have to use it for `apply-refact` and pass the parsed module in all cases. Only hlint requires ghc-lib.
Not sure if that dissymmetry could cause issues though. Moreover, there is an issue in apply-refact to make it use ghc-lib, logical move if we take in account both packages are closely related.

File: plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs (hunk 1 above)
Comment (jneira) [reply plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs:398]: does `ModSummary` includes the flags set as ghc arguments (so in .cabal/stack.yaml files)? or only the defined ones in the source file itself?
If it does not we 'll have to merge them.

File: plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs (hunk 2 above)
Comment (ndmitchell) [reply plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs:370]: Ah, that makes sense, its quite a different purpose GHC_LIB to the one in Ghcide.

File: plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs (hunk 1 above)
Comment (pepeiborra) [reply plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs:398]: It includes all the extensions that apply to the file, including the cabal and the local ones

File: plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs (hunk 2 above)
Comment (pepeiborra) [reply plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs:370]: If this defined variable serves a different purpose, then maybe give it a different name to avoid confusion.

But I still don't understand what it means. Where/when is it defined?

Comment (jneira) [reply plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs:370]: Well, afaiu for all cases it means you want to use ghc-lib, usually instead ghc:
* in ghcide the default is to use real ghc for all ghc versions and the cabal flag makes the package use ghc-lib for *all* ghc versions
  * the main goal is support daml
* in hlint the default is use ghc-lib for ghc < 8.10 and ghc for 8.10, the cabal flag makes hlint use ghc-lib for all versions
  * afaik the main goal is to avoid a ghc compat module, as ghc-lib is *the* ghc compat package

We copied in the plugin hlint cabal definitions:

https://github.com/haskell/haskell-language-server/blob/d0fb85eb2c35d0c5ad0e4d0610d89e05d37f5b26/plugins/hls-hlint-plugin/hls-hlint-plugin.cabal#L19-L23

https://github.com/haskell/haskell-language-server/blob/d0fb85eb2c35d0c5ad0e4d0610d89e05d37f5b26/plugins/hls-hlint-plugin/hls-hlint-plugin.cabal#L55-L64

But we have to use ghc and ghc-lib at the same time, to make a bridge between ghcide and hlint.

The `GHC-LIB` cpp condition guards code that have to take in account ghc-lib (like in ghcide, no?). Not sure what other better name could have.

Comment (pepeiborra) [reply plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs:370]: A suitable name would be HLINT_ON_GHC_LIB perhaps?

Comment (jneira) [reply plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs:370]: Mmm, maybe a little bit too close to the actual implementation (i can imagine apply-refact also using ghc-lib f.e.) but it is clear in exchange, will do

**Comment by jneira** [comment]
I've detected that the ghc-8.10 path that uses the new `applyRefactoring'` is dropping language pragmas from the module header. :worried: 
Calling `hlint Module.hs --refactor` works so i guess something is missing from ghc-exactprint annotations

**Comment by jneira** [comment]
rebased over the tests recently added in master

**Comment by jneira** [comment]
Ok, tests are passing for ghc <= 8.8
About the lose of language pragmas, i guess the parsed module we are getting from ghcide does not have them (or doesn't in a way apply-refact is able to include in the output).
`apply-refact` is using `ghc-exactprint` to parse the module source file:  https://github.com/alanz/ghc-exactprint/blob/81c2ef9cdcf284724df0d66ef1fe5616fdc8ae6c/src/Language/Haskell/GHC/ExactPrint/Parsers.hs#L293 and it is preserving language pragmas with this code path

We have two options:
* to have in the shake graph a version of the parsed module extracted from ghc-exactprint while it is not integrated in ghc itself (and keep it for previous versions)
  * or having a version of the parsed module preserving them (if it is not doing it already)
* try to recover language pragmas in the plugin with existing info

**Comment by jneira** [comment]
As expected, the ghc-8.10 code path does not preserve normal comments :worried: 
The behaviour is weird indeed:
* It removes inline comments (`{- -}`) entirely (so like pragmas)
* It removes regular comments starting with `--` entirely
* It removes haddock comment tokens `-- |` but keeps the comment itself, duplicating it

```
 FAIL (1.77s)
        test/functional/FunctionalCodeAction.hs:186:
        expected: "-- comment before header\nmodule ApplyRefact6 where\n\n{-# standalone annotation #-}\n\n-- standalone comment\n\n-- | haddock comment\nf = {- inline comment -} 1 -- ending comment\n\n-- final comment\n"
         but got: "\nmodule ApplyRefact6 where\n\n\n\n\n\n haddock comment haddock comment\nf =                      1\n\n\n"
```

**Comment by jneira** [comment]
ok, i *think* i know the cause of mising comments:
* `getParsedModule` parses the source file with `Opt_Haddock` to get its nice comments over definitions
  * but that option is not compatible with `Opt_KeepRawTokenStream`, as warned in ghcide `getParsedModuleRule`:

```
-- | IMPORTANT FOR HLINT INTEGRATION:
-- We currently parse the module both with and without Opt_Haddock, and
-- return the one with Haddocks if it -- succeeds. However, this may not work
-- for hlint, and we might need to save the one without haddocks too.
-- See https://github.com/haskell/ghcide/pull/350#discussion_r370878197
-- and https://github.com/mpickering/ghcide/pull/22#issuecomment-625070490
```
links: https://github.com/haskell/ghcide/pull/350#discussion_r370878197, and https://github.com/mpickering/ghcide/pull/22#issuecomment-625070490

* otoh apply refactorings has no position informed, to avoid mismatches between the hint and the refactoring, so the entire file is being replaced by the refactor, so the edit must be perfect:

https://github.com/haskell/haskell-language-server/blob/9ac127e04c5f51249df8d3fb8e1f455595f2bdbc/plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs#L342-L356

So the plan would be
* Create a rule to get the `ParsedModule` with all comments using `Opt_KeepRawTokenStream` (the defaul i guess), i would name it `GetParsedModuleWithComments` or `GetParsedModuleKeepRawTokenStream`
* Try to be more precise with the sope of the refactoring, maybe taking all the line or the line from the hint position instead the entire file

**Comment by ndmitchell** [comment]
> Create a rule to get the ParsedModule with all comments using Opt_KeepRawTokenStream (the defaul i guess), i would name it GetParsedModuleWithComments or GetParsedModuleKeepRawTokenStream

That seems very sensible. Have two graph nodes which are the parsed module with Opt_KeepRawTokenStream  and with Opt_Haddock as separate entities with distinct names. Then you have a single "I don't care" node which is haddock if you have it, otherwise not.

> Try to be more precise with the sope of the refactoring, maybe taking all the line or the line from the hint position instead the entire file

I think this is a matter of heuristics. Is the case you are worried about having CPP? I would play around and see what works best, but I think its inevitable that you aren't going to be able to do all cases every time.

**Comment by jneira** [comment]
> I think this is a matter of heuristics. Is the case you are worried about having CPP? I would play around and see what works best, but I think its inevitable that you aren't going to be able to do all cases every time.

A possible heuristic could be take the smallest source span between:
* the closest cpp `#if ... #endif` block
* the closest top level definition

Unless a refactoring could cross those boundaries...

**Comment by jneira** [comment]
Ok, tests now are green so the pr could be reviewed

**Review by pepeiborra — APPROVED** [review]
The ghcide changes lgtm

**Comment by jneira** [comment]
I am gonna merge this as is, if noboy disagree.
There is an [unexpected behavior with comments in apply refact](https://github.com/mpickering/apply-refact/pull/101#issuecomment-759944948) but hopefully it will be resolved before the next release.

**Comment by jneira** [comment]
The build is failing with

```
 session-loader/Development/IDE/Session/VersionCheck.hs:17:24: error:
    • Exception when trying to run compile-time code:
        I could not find a GHC installation at /home/runner/.ghcup/ghc/8.10.3/lib/ghc-8.10.3. Please do a clean rebuild and/or reinstall GHC.
CallStack (from HasCallStack):
  error, called at src/GHC/Check.hs:166:7 in ghc-check-0.5.0.3-a5c4fe466b9db954d5acec57d6f2911207e4ee3d449b9c03333ebfde2286e811:GHC.Check
      Code: makeGhcVersionChecker
              (fromMaybe GHC.Paths.libdir <$> lookupEnv "NIX_GHC_LIBDIR")
    • In the Template Haskell splice
        $$(makeGhcVersionChecker
             (fromMaybe GHC.Paths.libdir <$> lookupEnv "NIX_GHC_LIBDIR"))
      In the expression:
        $$(makeGhcVersionChecker
             (fromMaybe GHC.Paths.libdir <$> lookupEnv "NIX_GHC_LIBDIR"))
      In an equation for ‘ghcVersionChecker’:
          ghcVersionChecker
            = $$(makeGhcVersionChecker
                   (fromMaybe GHC.Paths.libdir <$> lookupEnv "NIX_GHC_LIBDIR"))
   |
17 | ghcVersionChecker = $$(makeGhcVersionChecker (fromMaybe GHC.Paths.libdir <$> lookupEnv "NIX_GHC_LIBDIR"))
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

ghc was already installed in other location:

```
 Preparing to setup a Haskell environment
Resolved 3.2 to 3.2.0.0
Installing ghc version 8.10.3
  Found ghc 8.10.3 in cache at path /opt/ghc/8.10.3/bin. Setup successful.
```

So i think ghc was installed using ppa:hvr and the haskell-setup is not longer using the runtime installation using ghcsup.
But the previous libdir has been cached in the ghc-paths installation in the cabal store.

Weird thing, i guess if the session checker should be able to use the libdir returned by the cradle to avoid this kind of errors
// cc @pepeiborra 

I am gonna update the hackage index in cabal project, to invalidate the cache.

**Comment by jneira** [comment]
The cache mechanism has ignored the change in the cabal.project, [it is using the same cache](https://github.com/haskell/haskell-language-server/pull/635/checks?check_run_id=1701985416) key: 

` Cache restored from key: Linux-8.10.3-build-983ae526727aa0f660de5830ca5d98226b86c55f1bba83af04420296d5f3b317`

But afaiu the cache had to be invalidated due to `${{ hashFiles('cabal.project') }}`:

https://github.com/haskell/haskell-language-server/blob/a4627e5ec7df24b7b43eb2c828de85b70023063e/.github/workflows/test.yml#L74-L86

**Comment by pepeiborra** [comment]
Adding the ghc lib dir to the cache key does sound like  a good idea

**Comment by jneira** [comment]
well it only will be an issue when using a new ghc version and I think the right solution could be

> i wonder if the ghc session checker should be able to use the libdir returned by the cradle to avoid this kind of errors

will do in a new pr if needed
