### PR TITLE
Exclude superclass-generated names in class placeholders

### LINKED ISSUE #4450: Adding placeholders for non-implemented class methods adds non-existant methods
### Your environment

GHC 9.6.6, arch linux, HLS 2.9.0.1 installed via ghcup

### Steps to reproduce

```cabal
cabal-version:      3.12
name:               hls-megaparsec-bug
version:            0.1.0.0
-- synopsis:
-- description:
license:            NONE
author:             Fendor
maintainer:         fendor@posteo.de
-- copyright:
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  MyLib
    -- other-modules:
    -- other-extensions:
    build-depends:
        base,
        megaparsec

    hs-source-dirs:   src
    default-language: Haskell2010
```

```haskell
{-# LANGUAGE FlexibleInstances #-}
module MyLib where
import Text.Megaparsec

instance VisualStream [Int] where
```

image

### Expected behaviour

Should add methods `showTokens`

### Actual behaviour

```haskell
{-# LANGUAGE FlexibleInstances #-}
module MyLib where
import Text.Megaparsec

instance VisualStream [Int] where
  p1VisualStream = _
  showTokens = _
  tokensLength = _
```

No idea where `p1VisualStream` is coming from.

### PR DESCRIPTION
**Pull request by crtschin**
Closes #4450.

Superclasses generate bindings in typeclasses as well. When determining which bindings to create placeholders for, these superclass-generated names need to be excluded. At the time of writing, this corresponds to the `mkSuperDictAuxOcc` function in Occurrence.hs in GHC, see the subsection on `Making system names` for the relevant bit.

### CODE REVIEW

File: plugins/hls-class-plugin/src/Ide/Plugin/Class/Utils.hs [hunk 1]
```diff
@@ -22,8 +22,20 @@ import           Language.LSP.Protocol.Types
 bindingPrefix :: IsString s => s
 bindingPrefix = "$c"
 
+-- | Superclasses generate bindings in typeclasses as well.
+--
+-- At the time of writing, this corresponds to the @mkSuperDictAuxOcc@ function
+-- in Occurrence.hs in GHC, see the subsection on @Making system names@ for the
+-- relevant bit. When determining which bindings to create placeholders for,
+-- these superclass-generated names need to be excluded.
```
Comment (fendor) [inline plugins/hls-class-plugin/src/Ide/Plugin/Class/Utils.hs]: This is bound to become outdated, we should open an issue in GHC to expose a function which takes care of this.

Comment (fendor) [reply plugins/hls-class-plugin/src/Ide/Plugin/Class/Utils.hs]: I opened an issue https://gitlab.haskell.org/ghc/ghc/-/issues/27195. We should reference this issue from here.

**Review by fendor — APPROVED** [review]
LGTM, thank you! Just one comment

File: plugins/hls-class-plugin/src/Ide/Plugin/Class/Utils.hs (hunk 1 above)
Comment (crtschin) [reply plugins/hls-class-plugin/src/Ide/Plugin/Class/Utils.hs]: Thanks! Done 👍🏽
