### PR TITLE
Avoid unnecessary Target canonicalisation in Session setup

### LINKED ISSUE #2358: HLS can't find symlinked Modules
### Steps to reproduce

Project structure
```
.
├── _ghci
│   └── Sym.hs -> /home/hugin/Documents/haskell/hls-bug2/some_loc/Sym.hs
├── hie.yaml
├── some_loc
│   └── Sym.hs
└── src
    └── Foo.hs
```

where hie.yaml is:
```yaml
cradle:
  direct:
    arguments:
      - -i
      - -isrc
      - -i_ghci/
      - _ghci/Sym.hs
      - src/Foo.hs
```

and `Foo.hs` imports `Sym.hs`. 

The following script generates this project:
<details>
<summary>Generate project</summary>

```sh
#!/usr/bin/env bash

mkdir _ghci some_loc src
echo -e "module Foo where\n\nimport Sym\n" > src/Foo.hs
echo -e "module Sym where foo = \"\"" > some_loc/Sym.hs
ln -s $(pwd)/some_loc/Sym.hs _ghci/Sym.hs

echo "" > hie.yaml # create empty hie.yaml
echo "cradle:" >> hie.yaml
echo "  direct:" >> hie.yaml
echo "    arguments:" >> hie.yaml
echo "      - -i" >> hie.yaml
echo "      - -isrc" >> hie.yaml
echo "      - -i_ghci/" >> hie.yaml
echo "      - _ghci/Sym.hs" >> hie.yaml
echo "      - src/Foo.hs" >> hie.yaml
```
</details>

### Expected behaviour

HLS should be able to load this project, just like `ghc`:
```sh 
> ghc -i -isrc -i_ghci/ _ghci/Sym.hs src/Foo.hs
[1 of 2] Compiling Sym              ( _ghci/Sym.hs, _ghci/Sym.o )
[2 of 2] Compiling Foo              ( src/Foo.hs, src/Foo.o )
```

and `hie-bios`:
```sh
> hie-bios check src/Foo.hs
src/Foo.hs:3:1:Warning: The import of ‘Sym’ is redundant
  except perhaps to import instances from ‘Sym’
To import instances alone, use: import Sym()
```

### Actual behaviour

However, the following error is shown:
```sh
> haskell-language-server-8.10.7 src/Foo.hs
haskell-language-server version: 1.4.0.0 (GHC: 8.10.7) (PATH: /home/hugin/.ghcup/bin/haskell-language-server-8.10.7~1.4.0) (GIT hash: 253547816ee216c53ee7dacc0ad3cac43e863d30)
 ghcide setup tester in /home/hugin/Documents/haskell/hls-bug2.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/4: Finding files to test in /home/hugin/Documents/haskell/hls-bug2
Found 1 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle
  (/home/hugin/Documents/haskell/hls-bug2/hie.yaml)

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
2021-11-16 10:19:35.405428645 [ThreadId 51] INFO hls:	Consulting the cradle for "src/Foo.hs"
Output from setting up the cradle Cradle {cradleRootDir = "/home/hugin/Documents/haskell/hls-bug2", cradleOptsProg = CradleAction: Direct}
2021-11-16 10:19:35.484578014 [ThreadId 51] INFO hls:	Using interface files cache dir: /home/hugin/.cache/ghcide/main-066636b74adb0ec22204dccf3a86bd38674b1c5a
2021-11-16 10:19:35.484741616 [ThreadId 51] INFO hls:	Making new HscEnv[main]
2021-11-16 10:19:35.503112003 [ThreadId 138] INFO hls:	File:     /home/hugin/Documents/haskell/hls-bug2/src/Foo.hs
Hidden:   no
Range:    3:8-3:11
Source:   not found
Severity: DsError
Message: 
  Could not find module ‘Sym’
  It is not a module in the current program, or in any known package.
2021-11-16 10:19:35.503728548 [ThreadId 146] INFO hls:	finish: User TypeCheck (took 0.01s)
Files that failed:
 * /home/hugin/Documents/haskell/hls-bug2/src/Foo.hs
2021-11-16 10:19:35.503915219 [ThreadId 148] INFO hls:	finish: GetHie (took 0.00s)

2021-11-16 10:19:35.504074281 [ThreadId 151] INFO hls:	finish: GenerateCore (took 0.00s)
Completed (0 files worked, 1 file failed)
```

I think there are some duplicates of this issue, usually where the modules point into the nix-store, but I couldn't find them right away.

### PR DESCRIPTION
**Pull request by fendor**
Closes #2358  

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2359"></a>

### CODE REVIEW

File: ghcide/session-loader/Development/IDE/Session.hs [hunk 1]
```diff
@@ -553,11 +553,11 @@ fromTargetId is exts (GHC.TargetModule mod) env dep = do
               , i <- is
               , boot <- ["", "-boot"]
               ]
-    locs <- mapM (fmap toNormalizedFilePath' . canonicalizePath) fps
+    let locs = map toNormalizedFilePath' fps
     return [TargetDetails (TargetModule mod) env dep locs]
 -- For a 'TargetFile' we consider all the possible module names
 fromTargetId _ _ (GHC.TargetFile f _) env deps = do
-    nf <- toNormalizedFilePath' <$> canonicalizePath f
+    let nf = toNormalizedFilePath' f
```
Comment (fendor) [inline ghcide/session-loader/Development/IDE/Session.hs:560]:
```suggestion
    nf <- toNormalizedFilePath' <$> makeAbsolute f
```

This might be better to make sure the paths are absolute but let's see what CI says

**Comment by pepeiborra** [comment]
Did you check the git history to make sure we are not missing anything? This seems like a risky change

**Comment by fendor** [comment]
The canonicalisation seems to be from the first implementation done by mpickering. One of the earliest commits I can find in this repository is https://github.com/haskell/haskell-language-server/commit/f1b36bac0462020725958d093474ca390ae870e9#diff-d7140bbfca1b7aaafd8c82d1d6aa21a3f941eb27ba8f08e4d9fb13766b21b418R316

I think this was mainly done to avoid possible issues with relative and absolute paths. In hie-bios we had similar issues with symbolic links due to the use of `canonicalizePath`. We gradually replaced every occurrence of that with `makeAbsolute`.

Alternatively, if you feel uncomfortable with this solution, we can canonicalize the candidates of the imports at https://github.com/haskell/haskell-language-server/blob/master/ghcide/src/Development/IDE/Import/FindImports.hs#L71
This way this issue is also resolved.
However, I feel like patching it in `FindImports` is the worse solution, as `NormalizedFilePath` does currently not guarantee that file paths are canonicalised, so canonicalising in seemingly arbitrary places feels like a band aid.

**Comment by fendor** [comment]
After looking some more around, I found: https://github.com/haskell/haskell-language-server/blob/a03013ce1837353a59c85074d5cc8e4b51b14601/ghcide/src/Development/IDE/Types/HscEnvEq.hs#L62 which we need to patch as well for the same reasons.

Any other occurrence of `canonicalizePath` is either in tests, not in a relevant code-path (e.g. Main.hs debug loading) or in a plugin. Notably, in the module-name plugin, which we almost definitely have to patch as well to use `makeAbsolute`.

 I think we should use `makeAbsolute` everywhere in ghcide instead of `canonicalizePath`.

**Comment by fendor** [comment]
I am weirded out that this commit fixed anything

**Comment by fendor** [comment]
@jneira are windows tests flaky?

**Comment by jneira** [comment]
> 
> 
> @jneira are windows tests flaky?

always :laughing: 

a little bit more flaky than ubuntu/macos ones

**Comment by jneira** [comment]
> 
> 
> > @jneira are windows tests flaky?
> 
> always laughing
> 
> a little bit more flaky than ubuntu/macos ones

Lately ghcide tests are more flaky in ubuntu :thinking:

**Comment by fendor** [comment]
This is weird. CI is apparently slightly flaky. I am not fully on-board with changes from b7901424ec4d6f0ecf669a5e64e8d6433f7d0f0c as I did not check thoroughly what they influence. Should we just ignore it, or should I revert this commit since I didnt check it?

**Comment by jneira** [comment]
> This is weird. CI is apparently slightly flaky. I am not fully on-board with changes from b7901424ec4d6f0ecf669a5e64e8d6433f7d0f0c as I did not check thoroughly what they influence. Should we just ignore it, or should I revert this commit since I didnt check it?

makeAbsolute does a normalisation? or it keeps . and .. f.e.? (one of the call sites talk about remove ..)

**Review by jneira — APPROVED** [review]
Looks good, it includes the appropiate regression test and ci is green. Great work as usual.

I would wait to next release to dogfooding it if you dont mind

Would like to know @pepeiborra thoughts though

**Review by pepeiborra — APPROVED** [review]

**Comment by jneira** [comment]
we will need a new release with the fixes for the early bugs found in 1.5.0, will merge afterwards
