### PR TITLE
Fix: Show actual parse errors for external Fourmolu/Ormolu

### LINKED ISSUE #4853: Show external fourmolu errors in notification
If I try to format a file with an error (e.g. invalid syntax), using the built-in fourmolu plugin shows the error message in the notification, but using an external fourmolu simply shows "fourmolu: Internal Error: Fourmolu failed with exit code 3" in the notification, and you have to open the HLS logs to see the stderr

Seems specific to fourmolu:
https://github.com/haskell/haskell-language-server/blob/66f5526e675cf4eb4163be31146e1b42726183e0/plugins/hls-fourmolu-plugin/src/Ide/Plugin/Fourmolu.hs#L147-L148

Perhaps we should put stderr in the InternalError? I think that would match the bundled fourmolu logic. cc @georgefst

### PR DESCRIPTION
**Pull request by ijatinydv**
Right now, if you use an external `fourmolu` or `ormolu` executable and there's a syntax error in your file, the editor just pops up a generic `Internal Error: Fourmolu failed with exit code 3`. The actual parse error gets buried in the HLS logs, which is a bit frustrating since the bundled library paths already show the error directly in the IDE.

This PR fixes that by grabbing the `stderr` output from the CLI process and tacking it onto the `PluginInternalError` message for both plugins. 

A couple of minor UX details included:
- Added a `T.null` guard so we don't append empty newlines if the formatter fails silently.
- Used `T.stripEnd` instead of stripping both sides so that the internal indentation of the GHC parse errors stays intact when it renders in the editor popup.

Fixes #4853

### CODE REVIEW

**Comment by fendor** [comment]
Do we perhaps want to add a regression test for this?

**Comment by ijatinydv** [comment]
> Do we perhaps want to add a regression test for this?

I agree. Just pushed an update with tests for both of them. let me know if this looks good!

**Comment by ijatinydv** [comment]
@fendor almost 15 tests are failing. Can you help me in this where is the problem occuring?

**Comment by fendor** [comment]
Your tests don't compile on older GHC versions, see

```
 [1 of 1] Compiling Main             ( plugins/hls-ormolu-plugin/test/Main.hs, b/build/aarch64-osx/ghc-9.8.4/hls-2.13.0.0/t/hls-ormolu-plugin-tests/build/hls-ormolu-plugin-tests/hls-ormolu-plugin-tests-tmp/Main.o )
<no location info>: warning: [GHC-42258] [-Wunused-packages]
    The following packages were specified via -package or -package-id flags,
    but were not needed for compilation:
      - ormolu-0.7.4.0 (exposed by flag -package-id rml-0.7.4.0-b3a2b833)
Configuring test suite 'hls-notes-plugin-tests' for hls-2.13.0.0...

plugins/hls-ormolu-plugin/test/Main.hs:47:37: error: [GHC-87543]
Error:     Ambiguous occurrence ‘_result’.
    It could refer to
       either the field ‘_result’ of record ‘TResponseMessage’,
              imported from ‘Test.Hls’ at plugins/hls-ormolu-plugin/test/Main.hs:16:1-25
              (and originally defined in ‘lsp-types-2.4.0.0:Language.LSP.Protocol.Message.Types’),
           or the field ‘_result’ of record ‘ResponseMessage’,
              imported from ‘Test.Hls’ at plugins/hls-ormolu-plugin/test/Main.hs:16:1-25
              (and originally defined in ‘lsp-types-2.4.0.0:Language.LSP.Protocol.Message.Types’).
   |
47 |                   TResponseMessage {_result = Left (TResponseError {_message = msg})} ->
   |                                     ^^^^^^^

plugins/hls-ormolu-plugin/test/Main.hs:47:69: error: [GHC-87543]
Error:     Ambiguous occurrence ‘_message’.
    It could refer to
       either the field ‘_message’ of record ‘TResponseError’,
              imported from ‘Test.Hls’ at plugins/hls-ormolu-plugin/test/Main.hs:16:1-25
              (and originally defined in ‘lsp-types-2.4.0.0:Language.LSP.Protocol.Message.Types’),
           or the field ‘_message’ of record ‘Diagnostic’,
              imported from ‘Test.Hls’ at plugins/hls-ormolu-plugin/test/Main.hs:16:1-25
              (and originally defined in ‘lsp-types-2.4.0.0:Language.LSP.Protocol.Internal.Types.Diagnostic’),
Configuring test suite 'hls-hlint-plugin-tests' for hls-2.13.0.0...
           or the field ‘_message’ of record ‘DiagnosticRelatedInformation’,
              imported from ‘Test.Hls’ at plugins/hls-ormolu-plugin/test/Main.hs:16:1-25
              (and originally defined in ‘lsp-types-2.4.0.0:Language.LSP.Protocol.Internal.Types.DiagnosticRelatedInformation’),
           or the field ‘_message’ of record ‘LogMessageParams’,
              imported from ‘Test.Hls’ at plugins/hls-ormolu-plugin/test/Main.hs:16:1-25
              (and originally defined in ‘lsp-types-2.4.0.0:Language.LSP.Protocol.Internal.Types.LogMessageParams’),
           or the field ‘_message’ of record ‘LogTraceParams’,
              imported from ‘Test.Hls’ at plugins/hls-ormolu-plugin/test/Main.hs:16:1-25
              (and originally defined in ‘lsp-types-2.4.0.0:Language.LSP.Protocol.Internal.Types.LogTraceParams’),
           or the field ‘_message’ of record ‘ShowMessageParams’,
              imported from ‘Test.Hls’ at plugins/hls-ormolu-plugin/test/Main.hs:16:1-25
              (and originally defined in ‘lsp-types-2.4.0.0:Language.LSP.Protocol.Internal.Types.ShowMessageParams’),
           or the field ‘_message’ of record ‘ShowMessageRequestParams’,
              imported from ‘Test.Hls’ at plugins/hls-ormolu-plugin/test/Main.hs:16:1-25
              (and originally defined in ‘lsp-types-2.4.0.0:Language.LSP.Protocol.Internal.Types.ShowMessageRequestParams’),
           or the field ‘_message’ of record ‘WorkDoneProgressBegin’,
              imported from ‘Test.Hls’ at plugins/hls-ormolu-plugin/test/Main.hs:16:1-25
              (and originally defined in ‘lsp-types-2.4.0.0:Language.LSP.Protocol.Internal.Types.WorkDoneProgressBegin’),
           or the field ‘_message’ of record ‘WorkDoneProgressEnd’,
              imported from ‘Test.Hls’ at plugins/hls-ormolu-plugin/test/Main.hs:16:1-25
              (and originally defined in ‘lsp-types-2.4.0.0:Language.LSP.Protocol.Internal.Types.WorkDoneProgressEnd’),
           or the field ‘_message’ of record ‘WorkDoneProgressReport’,
              imported from ‘Test.Hls’ at plugins/hls-ormolu-plugin/test/Main.hs:16:1-25
              (and originally defined in ‘lsp-types-2.4.0.0:Language.LSP.Protocol.Internal.Types.WorkDoneProgressReport’),
           or the field ‘_message’ of record ‘ResponseError’,
              imported from ‘Test.Hls’ at plugins/hls-ormolu-plugin/test/Main.hs:16:1-25
              (and originally defined in ‘lsp-types-2.4.0.0:Language.LSP.Protocol.Message.Types’).
   |
47 |                   TResponseMessage {_result = Left (TResponseError {_message = msg})} ->
   |                                                                     ^^^^^^^^

plugins/hls-ormolu-plugin/test/Main.hs:53:37: error: [GHC-87543]
Error:     Ambiguous occurrence ‘_result’.
    It could refer to
       either the field ‘_result’ of record ‘TResponseMessage’,
              imported from ‘Test.Hls’ at plugins/hls-ormolu-plugin/test/Main.hs:16:1-25
              (and originally defined in ‘lsp-types-2.4.0.0:Language.LSP.Protocol.Message.Types’),
           or the field ‘_result’ of record ‘ResponseMessage’,
              imported from ‘Test.Hls’ at plugins/hls-ormolu-plugin/test/Main.hs:16:1-25
              (and originally defined in ‘lsp-types-2.4.0.0:Language.LSP.Protocol.Message.Types’).
   |
53 |                   TResponseMessage {_result = Right _} ->
   |                                     ^^^^^^^
```

**Comment by ijatinydv** [comment]
@fendor right, I totally missed that. I tried to skip the lens dependency but totally forgot how overloaded the `lsp-types` fields are on older GHC versions. Just fixed it using `Language.LSP.Protocol.Lens`
thanks for this fendor!

File: plugins/hls-fourmolu-plugin/test/Main.hs [hunk 1]
```diff
@@ -31,6 +35,25 @@ tests =
...
+                void waitForBuildQueue
+                resp <- request SMethod_TextDocumentFormatting $
+                    DocumentFormattingParams Nothing doc (FormattingOptions 4 True Nothing Nothing Nothing)
+                liftIO $ case resp ^. L.result of
+                    Left err ->
+                        -- The error message must contain more than just the exit code;
+                        -- it should include the stderr output with parse error details.
+                        assertBool
+                            ("Error message should contain stderr output, got: " <> T.unpack (err ^. L.message))
+                            (T.length (err ^. L.message) > T.length "Fourmolu failed with exit code 1")
```
Comment (fendor) [inline plugins/hls-fourmolu-plugin/test/Main.hs]: Please use a more fitting assertion, this does not ensure at all that the error details are included.

Comment (ijatinydv) [reply plugins/hls-fourmolu-plugin/test/Main.hs]: > Please use a more fitting assertion, this does not ensure at all that the error details are included.

yeah makes sense, i swapped the length check for explicit substring checks so it directly verifies `parse error` is in the payload. 
Please have a review now!

File: plugins/hls-fourmolu-plugin/src/Ide/Plugin/Fourmolu.hs [hunk 2]
```diff
@@ -145,7 +145,11 @@ provider recorder plId ideState token typ contents fp fo = ExceptT $ pluginWithI
                 pure $ InL $ makeDiffTextEdit contents out
             ExitFailure n -> do
                 logWith recorder Info $ StdErr err
-                throwError $ PluginInternalError $ "Fourmolu failed with exit code " <> T.pack (show n)
+                let cliError = if T.null (T.strip err)
+                               then ""
+                               else "\n" <> T.stripEnd err
+                throwError $ PluginInternalError $
+                    "Fourmolu failed with exit code " <> T.pack (show n) <> cliError
```
Comment (fendor) [inline plugins/hls-fourmolu-plugin/src/Ide/Plugin/Fourmolu.hs:153]: I am curious, is the error message ever `"   "` or `"\n"` s.t. it makes sense to `strip` here?
I can see the need for the `stripEnd` to avoid trailing newlines, but the first `strip` should never matter, and if it does, we'd much rather patch the upstream formatters.

Perhaps @georgefst has an opinion on this?

File: plugins/hls-fourmolu-plugin/test/Main.hs [hunk 3]
```diff
@@ -31,6 +35,28 @@ tests =
...
+                liftIO $ case resp ^. L.result of
+                    Left err -> do
+                        let msg = err ^. L.message
+                        -- Verify the error message structure:
+                        -- 1. Contains the exit code prefix (base message intact)
+                        assertBool ("Expected exit code prefix, got: " <> T.unpack msg)
+                            ("failed with exit code" `T.isInfixOf` msg)
+                        -- 2. Contains stderr parse error details
+                        assertBool ("Expected parse error details from stderr, got: " <> T.unpack msg)
+                            ("parse error" `T.isInfixOf` msg)
```
Comment (fendor) [inline plugins/hls-fourmolu-plugin/test/Main.hs]: Can we check for the actual message, or is `parse error` truly the only thing we get reliably check for?

File: plugins/hls-fourmolu-plugin/test/Main.hs [hunk 4]
```diff
@@ -31,6 +35,28 @@ tests =
...
+                    Right _ ->
+                        assertFailure "Expected formatting to fail on invalid syntax file"
```
Comment (fendor) [inline plugins/hls-fourmolu-plugin/test/Main.hs]:
```suggestion
                        assertFailure "Expected formatting to fail on unparsable file"
```

File: plugins/hls-fourmolu-plugin/src/Ide/Plugin/Fourmolu.hs (hunk 2 above)
Comment (ijatinydv) [reply plugins/hls-fourmolu-plugin/src/Ide/Plugin/Fourmolu.hs:153]: > I am curious, is the error message ever `" "` or `"\n"` s.t. it makes sense to `strip` here? I can see the need for the `stripEnd` to avoid trailing newlines, but the first `strip` should never matter, and if it does, we'd much rather patch the upstream formatters.
> 
> Perhaps @georgefst has an opinion on this?

yeah you're right, `T.strip` is overly defensive. if the formatter outputs pure whitespace, that's an upstream bug we shouldn't hide.
i dropped it, and just kept `T.stripEnd` to handle the standard trailing `\n` so the error popup stays clean. Pushed the fix for it. Please have a review.

File: plugins/hls-fourmolu-plugin/test/Main.hs (hunk 3 above)
Comment (ijatinydv) [reply plugins/hls-fourmolu-plugin/test/Main.hs]: > Can we check for the actual message, or is `parse error` truly the only thing we get reliably check for?

matching the full actual message gets pretty brittle since `ghc` changes its parser error formatting across versions (like injecting GHC codes or changing quote styles), and the `<stdin>` vs filepath prefix changes based on the environment.
since we're just verifying the stderr flow works, a stable substring is the safest choice to avoid flaky tests. i agree it could be more specific though, so i tightened it to `"parse error on input"` and dropped a comment in the code explaining the intentional flexibility. pushed the update, please have a review.
