### PR TITLE
don't crash when an unused operator import ends in `.`

### LINKED ISSUE #2025: Project indexing doesn't finish, probably due to "type" import?
I'm using recent version of hls and I'm hitting this bug during indexing of my project.
It seems to be related to "type" imports.
I tried to find which `head` call in hls codebase could be behind this, but there are too many `head` calls to know for sure.
If you could help me identify which occurrence of `head` might be causing this issue, I could try to fix it

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
$ haskell-language-server-wrapper --probe-tools
haskell-language-server version: 1.2.0.0 (GHC: 8.8.4) (PATH: /home/jhrcek/.local/bin/haskell-language-server-wrapper) (GIT hash: 92e4bad5b6c5432938ae0842e9ddd569bf0cdff8)
Tool versions found on the $PATH
cabal:		3.4.0.0
stack:		2.7.1
ghc:		8.8.4

```
Which OS do you use:
Linux, Fedora 34
Which lsp-client do you use:
VS Code
Describe your project (alternative: link to the project):
N/A

### Steps to reproduce
This screenshot should sum it up just fine
hls-indexing-stuck

### Expected behaviour
Project indexing should finish

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

This command runs fine and doesn't print anything related. But nevertheless the VSCode ui gets stuck on indexing.

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

Pasting just few log lines that surround the `Prelude.head: empty list` error..
<details>
<summary>
LSP logs:
</summary>

```
2021-07-19 09:25:26.21620834 [ThreadId 1405] INFO hls:	finish: Wingman.judgementForHole.TypeCheck (took 0.00s)
2021-07-19 09:25:26.219038669 [ThreadId 1405] INFO hls:	finish: Wingman.judgementForHole.GhcSessionDeps (took 0.00s)
2021-07-19 09:25:26.351273507 [ThreadId 1741] INFO hls:	finish: Wingman.emptyCaseScrutinees.GhcSessionDeps (took 0.00s)
2021-07-19 09:25:26.352217492 [ThreadId 1741] INFO hls:	finish: codeLens.GetGlobalBindingTypeSigs (took 0.14s)
2021-07-19 09:25:27.356491874 [ThreadId 1742] INFO hls:	finish: GhcideCodeActions.GetAnnotatedParsedSource (took 0.00s)
2021-07-19 09:25:27.357057045 [ThreadId 1742] INFO hls:	finish: GhcideCodeActions.GetParsedModule (took 0.00s)
2021-07-19 09:25:27.35733881 [ThreadId 1742] INFO hls:	finish: GhcideCodeActions.GetFileContents (took 0.00s)
2021-07-19 09:25:27.441057756 [ThreadId 1742] INFO hls:	finish: GhcideCodeActions.TypeCheck (took 0.00s)
2021-07-19 09:25:27.444346666 [ThreadId 1405] INFO hls:	finish: GhcideCodeActions.GetHieAst (took 0.00s)
2021-07-19 09:25:27.445053112 [ThreadId 1405] INFO hls:	finish: GhcideCodeActions.getParsedModule (took 0.00s)
2021-07-19 09:25:27.996904126 [ThreadId 1742] INFO hls:	finish: RefineImports (took 8.76s)
2021-07-19 09:25:27.997052683 [ThreadId 1742] INFO hls:	finish: RefineImports (took 8.81s)
2021-07-19 09:25:27.997096856 [ThreadId 1742] INFO hls:	finish: RefineImports (took 2.35s)
haskell-language-server-8.8.4: Prelude.head: empty list
2021-07-19 09:25:28.824963259 [ThreadId 2045] INFO hls:	finish: RefineImports (took 9.63s)
```
</details>

### LINKED ISSUE #2118: HLS crashes in vscode with `Prelude.head: empty list`
This is not a duplicate of #2117 as the issue occurs on a different platform (macOS instead of NixOS) and manifests differently.

The HLS crashes five times in a row while working on this file:
https://github.com/hasktorch/hasktorch/blob/744dc4aff70719c9149807e40dacce59fd77484c/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs
The problem goes away when I comment everything below the `decode` function.

I have observed this issue with ghc 8.10.4 and hls 1.0, ghc 8.10.5 and hls 1.2, and now ghc 9.0.1 and hls 1.3.

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 1.3.0.0 (GHC: 9.0.1) (PATH: /nix/store/wcygg534z7l88pkgapwnmafs9mz47da0-haskell-language-server-exe-haskell-language-server-1.3.0.0/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:		3.4.0.0
stack:		2.7.3
ghc:		9.0.1
```
Which OS do you use:
MacOS
Which lsp-client do you use:
vscode
Describe your project (alternative: link to the project):
https://github.com/hasktorch/hasktorch/tree/generation-2
Contents of `hie.yaml`:
https://github.com/hasktorch/hasktorch/blob/generation-2/hie.yaml

### Steps to reproduce
```
$ nix develop
$ code .
```

### Expected behaviour
HLS should not crash or become unresponsive.

### Actual behaviour
HLS crashes or becomes unresponsive.

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

HLS processes all files and exits normally.

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
LSP logs:
</summary>

```
haskell-language-server version: 1.3.0.0 (GHC: 9.0.1) (PATH: /nix/store/wcygg534z7l88pkgapwnmafs9mz47da0-haskell-language-server-exe-haskell-language-server-1.3.0.0/bin/haskell-language-server)
Starting (haskell-language-server)LSP server...
  with arguments: GhcideArguments {argsCommand = LSP, argsCwd = Nothing, argsShakeProfiling = Nothing, argsTesting = False, argsExamplePlugin = False, argsDebugOn = True, argsLogFile = Nothing, argsThreads = 0, argsProjectGhcVersion = False}
  with plugins: [PluginId "pragmas",PluginId "floskell",PluginId "ormolu",PluginId "retrie",PluginId "callHierarchy",PluginId "haddockComments",PluginId "eval",PluginId "importLens",PluginId "moduleName",PluginId "hlint",PluginId "ghcide-hover-and-symbols",PluginId "ghcide-code-actions-imports-exports",PluginId "ghcide-code-actions-type-signatures",PluginId "ghcide-code-actions-bindings",PluginId "ghcide-code-actions-fill-holes",PluginId "ghcide-completions",PluginId "ghcide-type-lenses",PluginId "ghcide-core"]
  in directory: /Users/torsten.scholak/Projects/thirdParty/hasktorch
 Starting LSP server...
If you are seeing this in a terminal, you probably should have run WITHOUT the --lsp option!
Started LSP server in 0.00s
setInitialDynFlags cradle: Cradle {cradleRootDir = "/Users/torsten.scholak/Projects/thirdParty/hasktorch", cradleOptsProg = CradleAction: Cabal}
Currently, HLS supports GHC 9 only partially. See [issue #297](https://github.com/haskell/haskell-language-server/issues/297) for more detail.
2021-08-20 19:33:15.070065 [ThreadId 9] DEBUG hls:	Initializing exports map from hiedb
2021-08-20 19:33:15.568587 [ThreadId 5] INFO hls:	Registering ide configuration: IdeConfiguration {workspaceFolders = fromList [NormalizedUri 3025941427988373460 "file:///Users/torsten.scholak/Projects/thirdParty/hasktorch"], clientSettings = hashed Nothing}
2021-08-20 19:33:15.643099 [ThreadId 27] DEBUG hls:	Configuration changed: Object (fromList [("haskell",Object (fromList [("diagnosticsOnChange",Bool True),("formatOnImportOn",Bool True),("formattingProvider",String "ormolu"),("indentationRules",Object (fromList [("enabled",Bool True)])),("logFile",String ""),("plugin",Object (fromList [("class",Object (fromList [("globalOn",Bool True)])),("eval",Object (fromList [("globalOn",Bool True)])),("ghcide-completions",Object (fromList [("config",Object (fromList [("autoExtendOn",Bool True),("snippetsOn",Bool True)]))])),("ghcide-type-lenses",Object (fromList [("config",Object (fromList [("mode",Bool True)])),("globalOn",Bool True)])),("haddockComments",Object (fromList [("globalOn",Bool True)])),("hlint",Object (fromList [("codeActionsOn",Bool True),("config",Object (fromList [("flags",Array [])])),("diagnosticsOn",Bool True)])),("importLens",Object (fromList [("codeActionsOn",Bool True),("codeLensOn",Bool True)])),("moduleName",Object (fromList [("globalOn",Bool True)])),("pragmas",Object (fromList [("codeActionsOn",Bool True),("completionOn",Bool True)])),("retrie",Object (fromList [("globalOn",Bool True)])),("splice",Object (fromList [("globalOn",Bool True)])),("tactics",Object (fromList [("config",Object (fromList [("auto_gas",Number 4.0),("hole_severity",Null),("max_use_ctor_actions",Number 5.0),("proofstate_styling",Bool True),("timeout_duration",Number 2.0)])),("globalOn",Bool True)]))])),("releasesURL",String ""),("serverExecutablePath",String ""),("trace",Object (fromList [("client",String "error"),("server",String "messages")])),("updateBehavior",String "keep-up-to-date")]))])
2021-08-20 19:33:15.645161 [ThreadId 30] DEBUG hls:	Finishing build session(exception: AsyncCancelled)
2021-08-20 19:33:15.645753 [ThreadId 27] DEBUG hls:	Restarting build session for keys [GetClientSettings; ] (aborting the previous one took 0.00s)
2021-08-20 19:33:15.647629 [ThreadId 27] DEBUG hls:	Set files of interest to: fromList []
2021-08-20 19:33:15.648167 [ThreadId 41] DEBUG hls:	Finishing build session(exception: AsyncCancelled)
2021-08-20 19:33:15.648299 [ThreadId 27] DEBUG hls:	Restarting build session for keys [GetModificationTime_ {missingFileDiagnostics = True}; /Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs,IsFileOfInterest; /Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs,GetClientSettings; ] (aborting the previous one took 0.00s)
2021-08-20 19:33:15.648471 [ThreadId 27] DEBUG hls:	Opened text document: file:///Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs
2021-08-20 19:33:15.650327 [ThreadId 125] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs"
2021-08-20 19:33:15.651755 [ThreadId 127] INFO hls:	Consulting the cradle for "experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs"
Output from setting up the cradle Cradle {cradleRootDir = "/Users/torsten.scholak/Projects/thirdParty/hasktorch", cradleOptsProg = CradleAction: Cabal}
> Build profile: -w ghc-9.0.1 -O1
> In order, the following will be built (use -v for more details):
>  - hasktorch-gradually-typed-0.2.0.0 (first run)
2021-08-20 19:33:16.132411 [ThreadId 9] DEBUG hls:	Done initializing exports map from hiedb (24887)
2021-08-20 19:33:16.524753 [ThreadId 144] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "fp" "/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs"
2021-08-20 19:33:16.790338 [ThreadId 162] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "fp" "/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs"
2021-08-20 19:33:16.802426 [ThreadId 177] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "fp" "/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs"
2021-08-20 19:33:16.913361 [ThreadId 192] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "fp" "/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs"
> Preprocessing library for hasktorch-gradually-typed-0.2.0.0..
2021-08-20 19:33:17.170706 [ThreadId 207] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "fp" "/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs"
2021-08-20 19:33:17.170827 [ThreadId 127] DEBUG hls:	Session loading result: Right (ComponentOptions {componentOptions = ["-fbuilding-cabal-package","-O0","-outputdir","/Users/torsten.scholak/.cache/hie-bios/dist-hasktorch-0342ef1337cc832e0323bd6ee3ac9d5e/build/x86_64-osx/ghc-9.0.1/hasktorch-gradually-typed-0.2.0.0/build","-odir","/Users/torsten.scholak/.cache/hie-bios/dist-hasktorch-0342ef1337cc832e0323bd6ee3ac9d5e/build/x86_64-osx/ghc-9.0.1/hasktorch-gradually-typed-0.2.0.0/build","-hidir","/Users/torsten.scholak/.cache/hie-bios/dist-hasktorch-0342ef1337cc832e0323bd6ee3ac9d5e/build/x86_64-osx/ghc-9.0.1/hasktorch-gradually-typed-0.2.0.0/build","-stubdir","/Users/torsten.scholak/.cache/hie-bios/dist-hasktorch-0342ef1337cc832e0323bd6ee3ac9d5e/build/x86_64-osx/ghc-9.0.1/hasktorch-gradually-typed-0.2.0.0/build","-i","-i/Users/torsten.scholak/.cache/hie-bios/dist-hasktorch-0342ef1337cc832e0323bd6ee3ac9d5e/build/x86_64-osx/ghc-9.0.1/hasktorch-gradually-typed-0.2.0.0/build","-isrc","-i/Users/torsten.scholak/.cache/hie-bios/dist-hasktorch-0342ef1337cc832e0323bd6ee3ac9d5e/build/x86_64-osx/ghc-9.0.1/hasktorch-gradually-typed-0.2.0.0/build/autogen","-i/Users/torsten.scholak/.cache/hie-bios/dist-hasktorch-0342ef1337cc832e0323bd6ee3ac9d5e/build/x86_64-osx/ghc-9.0.1/hasktorch-gradually-typed-0.2.0.0/build/global-autogen","-I/Users/torsten.scholak/.cache/hie-bios/dist-hasktorch-0342ef1337cc832e0323bd6ee3ac9d5e/build/x86_64-osx/ghc-9.0.1/hasktorch-gradually-typed-0.2.0.0/build/autogen","-I/Users/torsten.scholak/.cache/hie-bios/dist-hasktorch-0342ef1337cc832e0323bd6ee3ac9d5e/build/x86_64-osx/ghc-9.0.1/hasktorch-gradually-typed-0.2.0.0/build/global-autogen","-I/Users/torsten.scholak/.cache/hie-bios/dist-hasktorch-0342ef1337cc832e0323bd6ee3ac9d5e/build/x86_64-osx/ghc-9.0.1/hasktorch-gradually-typed-0.2.0.0/build","-optP-include","-optP/Users/torsten.scholak/.cache/hie-bios/dist-hasktorch-0342ef1337cc832e0323bd6ee3ac9d5e/build/x86_64-osx/ghc-9.0.1/hasktorch-gradually-typed-0.2.0.0/build/autogen/cabal_macros.h","-this-unit-id","hasktorch-gradually-typed-0.2.0.0-inplace","-hide-all-packages","-Wmissing-home-modules","-no-user-package-db","-package-db","/Users/torsten.scholak/.cabal/store/ghc-9.0.1/package.db","-package-db","/Users/torsten.scholak/.cache/hie-bios/dist-hasktorch-0342ef1337cc832e0323bd6ee3ac9d5e/packagedb/ghc-9.0.1","-package-db","/Users/torsten.scholak/.cache/hie-bios/dist-hasktorch-0342ef1337cc832e0323bd6ee3ac9d5e/build/x86_64-osx/ghc-9.0.1/hasktorch-gradually-typed-0.2.0.0/package.conf.inplace","-package-id","base-4.15.0.0","-package-id","containers-0.6.4.1","-package-id","exceptions-0.10.4","-package-id","finite-typelits-0.1.4.2-1dLKVitEZFWGBZgUMG5E4G","-package-id","free-5.1.7-7yKGIhcwgcS8SVBxXnMiB1","-package-id","generic-lens-2.2.0.0-BWomQImqnr72MBJHu3OVVq","-package-id","generics-sop-0.5.1.1-6a9fyHHEUWeGsTJGYyUZUT","-package-id","ghc-typelits-extra-0.4.3-28m2Tmf2vbx84MhFetwx3j","-package-id","ghc-typelits-knownnat-0.7.6-D5nS7iwD4PG7QktaszFeXX","-package-id","ghc-typelits-natnormalise-0.7.6-AjwJBCUWTfyFXJvu9mkx8v","-package-id","hasktorch-0.2.0.0-inplace","-package-id","hedgehog-1.0.5-300l1UK7WiWFHagDHFkXCs","-package-id","indexed-0.1.3-CKyh2YdeFAhFQphvQbjKDq","-package-id","indexed-extras-0.2-47l6GF1DGb8KG1FtSvLg4D","-package-id","indexed-list-literals-0.2.1.3-Bv46zhUC93R7rMV4csTAic","-package-id","lens-5.0.1-42rnNYIVKthIrXVzKJjm7D","-package-id","libtorch-ffi-1.9.0.0-inplace","-package-id","logict-0.7.0.3-HL2vhK670CaECk1RdONeLh","-package-id","megaparsec-9.1.0-DBn1hQinEoxCjxFNK947bZ","-package-id","mmorph-1.1.5-6XgAVHPGzECDm1vs0OocPx","-package-id","mtl-2.2.2","-package-id","normaldistribution-1.1.0.3-BNqAddtYRQnH4EaypioVUL","-package-id","parsers-0.12.10-3oj44n6lTQi9JHjJuqXytx","-package-id","pipes-4.3.16-CByT1AOcPux6BCfM9SuwSk","-package-id","pipes-concurrency-2.0.12-L0R4luS2X1yCcEMCRvI5Z7","-package-id","pipes-group-1.0.12-8E2QFKMhFzk5AN8oKOrN75","-package-id","random-1.2.0-6UzZwPIj89x7kKR4PhPZ8O","-package-id","singletons-3.0-Jt8unaXUKj46TY8PMZwo6X","-package-id","singletons-base-3.0-AxQRVN3bXOiGkfNxPA0eXM","-package-id","singletons-th-3.0-AoOnZm4xuYF3qS2DK2h9ii","-package-id","stm-2.5.0.0","-package-id","template-haskell-2.17.0.0","-package-id","text-1.2.4.1","-package-id","tknzrs-0.1.0.0-713af866","-package-id","transformers-0.5.6.2","-package-id","type-errors-pretty-0.0.1.2-H4vWkZ6CiZCH1Bx0vT3faN","-package-id","typlvl-rwrt-rls-1.0-c9b4862f","-package-id","vector-0.12.3.0-EqxQKEyaqr2AsJGS1A4pm1","-package-id","vector-sized-1.4.4-4FyUbrhSTpXBvhsrfKxRpg","-XHaskell2010","Torch.GraduallyTyped","Torch.GraduallyTyped.Prelude","Torch.GraduallyTyped.Prelude.List","Torch.GraduallyTyped.Prelude.Maybe","Torch.GraduallyTyped.Prelude.TypeLits","Torch.GraduallyTyped.Prelude.Bool","Torch.GraduallyTyped.Unify","Torch.GraduallyTyped.Scalar","Torch.GraduallyTyped.Tensor","Torch.GraduallyTyped.Tensor.Type","Torch.GraduallyTyped.Tensor.Creation","Torch.GraduallyTyped.Tensor.Indexing","Torch.GraduallyTyped.Tensor.IndexingSlicingJoining","Torch.GraduallyTyped.Tensor.Other","Torch.GraduallyTyped.Tensor.MathOperations","Torch.GraduallyTyped.Tensor.MathOperations.Pointwise","Torch.GraduallyTyped.Tensor.MathOperations.Reduction","Torch.GraduallyTyped.Tensor.MathOperations.Comparison","Torch.GraduallyTyped.Tensor.MathOperations.Spectral","Torch.GraduallyTyped.Tensor.MathOperations.Other","Torch.GraduallyTyped.Tensor.MathOperations.BlasLapack","Torch.GraduallyTyped.RequiresGradient","Torch.GraduallyTyped.DType","Torch.GraduallyTyped.Device","Torch.GraduallyTyped.Index","Torch.GraduallyTyped.Index.Type","Torch.GraduallyTyped.Index.Class","Torch.GraduallyTyped.Shape","Torch.GraduallyTyped.Shape.Type","Torch.GraduallyTyped.Shape.Class","Torch.GraduallyTyped.Layout","Torch.GraduallyTyped.Autograd","Torch.GraduallyTyped.Random","Torch.GraduallyTyped.Optim","Torch.GraduallyTyped.LearningRateSchedules","Torch.GraduallyTyped.NN","Torch.GraduallyTyped.NN.Type","Torch.GraduallyTyped.NN.Class","Torch.GraduallyTyped.NN.Initialization","Torch.GraduallyTyped.NN.Linear","Torch.GraduallyTyped.NN.Transformer","Torch.GraduallyTyped.NN.Transformer.Type","Torch.GraduallyTyped.NN.Transformer.GMultiHeadAttention","Torch.GraduallyTyped.NN.Transformer.GFeedForwardNetwork","Torch.GraduallyTyped.NN.Transformer.GSelfAttention","Torch.GraduallyTyped.NN.Transformer.GCrossAttention","Torch.GraduallyTyped.NN.Transformer.GBlock","Torch.GraduallyTyped.NN.Transformer.GStack","Torch.GraduallyTyped.NN.Transformer.GTransformer","Torch.GraduallyTyped.NN.Transformer.GLMHead","Torch.GraduallyTyped.NN.Transformer.GEncoderOnly","Torch.GraduallyTyped.NN.Transformer.GEncoderDecoder","Torch.GraduallyTyped.NN.Transformer.GPooler","Torch.GraduallyTyped.NN.Transformer.T5.Common","Torch.GraduallyTyped.NN.Transformer.T5.Small","Torch.GraduallyTyped.NN.Transformer.T5.Base","Torch.GraduallyTyped.NN.Transformer.T5.Large","Torch.GraduallyTyped.NN.Transformer.T5.ThreeB","Torch.GraduallyTyped.NN.Transformer.T5.ElevenB","Torch.GraduallyTyped.NN.Transformer.T5.Generation","Torch.GraduallyTyped.NN.Transformer.T5","Torch.GraduallyTyped.NN.Transformer.BART.Common","Torch.GraduallyTyped.NN.Transformer.BART.Base","Torch.GraduallyTyped.NN.Transformer.BART","Torch.GraduallyTyped.NN.Transformer.BERT.Common","Torch.GraduallyTyped.NN.Transformer.BERT.BaseUncased","Torch.GraduallyTyped.NN.Transformer.BERT","Torch.GraduallyTyped.NN.Transformer.RoBERTa.Common","Torch.GraduallyTyped.NN.Transformer.RoBERTa.Base","Torch.GraduallyTyped.NN.Transformer.RoBERTa","Torch.GraduallyTyped.NN.Transformer.Pegasus.Common","Torch.GraduallyTyped.NN.Transformer.Pegasus.XSum","Torch.GraduallyTyped.NN.Transformer.Pegasus","Torch.GraduallyTyped.NN.Transformer.Generation","Torch.GraduallyTyped.NN.Dropout","Torch.GraduallyTyped.NN.Activation","Torch.GraduallyTyped.NN.Normalization","Torch.GraduallyTyped.NN.Sparse","Torch.GraduallyTyped.NN.Loss","Torch.GraduallyTyped.NN.Training","Torch.GraduallyTyped.NN.Functional","Torch.GraduallyTyped.NN.Functional.Dropout","Torch.GraduallyTyped.NN.Functional.Activation","Torch.GraduallyTyped.NN.Functional.Linear","Torch.GraduallyTyped.NN.Functional.NonLinearActivation","Torch.GraduallyTyped.NN.Functional.Normalization","Torch.GraduallyTyped.NN.Functional.Sparse","Torch.GraduallyTyped.NN.Functional.Loss","Torch.GraduallyTyped.Internal.TensorOptions","Torch.GraduallyTyped.Internal.Void","Torch.GraduallyTyped.Internal.Vector","Torch.Language","Torch.Language.SpiderSQL","Torch.Data.Parser","Control.Monad.Fresh","-Wall","-fplugin","GHC.TypeLits.Normalise","-fplugin","GHC.TypeLits.KnownNat.Solver","-fplugin","GHC.TypeLits.Extra.Solver","-fconstraint-solver-iterations=0","-hide-all-packages"], componentRoot = "/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed", componentDependencies = ["experimental/gradually-typed/hasktorch-gradually-typed.cabal","cabal.project","cabal.project.local"]},"/nix/store/gfyfznxlch18bpa1mnzw17zdx8pgsqcr-ghc-shell-for-packages-ghc-9.0.1-env/lib/ghc-9.0.1")
2021-08-20 19:33:17.264663 [ThreadId 127] INFO hls:	Using interface files cache dir: /Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7
2021-08-20 19:33:17.265322 [ThreadId 127] INFO hls:	Making new HscEnv[hasktorch-gradually-typed-0.2.0.0-inplace]
2021-08-20 19:33:17.277681 [ThreadId 127] DEBUG hls:	New Component Cache HscEnvEq: (([],Just HscEnvEq 34),fromList [("/Users/torsten.scholak/Projects/thirdParty/hasktorch/hie.yaml",Just 2021-08-18 13:37:57.029496539 UTC),("cabal.project",Just 2021-08-19 23:44:52.686378146 UTC),("cabal.project.local",Nothing),("experimental/gradually-typed/hasktorch-gradually-typed.cabal",Just 2021-08-19 23:44:45.607654213 UTC)])
2021-08-20 19:33:17.775275 [ThreadId 127] DEBUG hls:	Known files updated: fromList [(TargetModule Torch.GraduallyTyped.NN.Sparse,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Sparse.hs"]),(TargetModule Torch.GraduallyTyped.Prelude.Bool,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Prelude/Bool.hs"]),(TargetModule Torch.GraduallyTyped.Random,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Random.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.Pegasus,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Pegasus.hs"]),(TargetModule Torch.GraduallyTyped.NN.Training,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Training.hs"]),(TargetModule Torch.GraduallyTyped.NN.Loss,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Loss.hs"]),(TargetModule Torch.GraduallyTyped.NN.Functional,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Functional.hs"]),(TargetModule Torch.GraduallyTyped.Tensor.Type,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/Type.hs"]),(TargetModule Torch.GraduallyTyped.Optim,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Optim.hs"]),(TargetModule Torch.GraduallyTyped.Tensor.MathOperations.Comparison,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/MathOperations/Comparison.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.Type,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Type.hs"]),(TargetModule Torch.GraduallyTyped.Layout,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Layout.hs"]),(TargetModule Torch.GraduallyTyped.NN.Functional.Sparse,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Functional/Sparse.hs"]),(TargetModule Torch.GraduallyTyped.Autograd,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Autograd.hs"]),(TargetModule Torch.GraduallyTyped.Shape.Type,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Shape/Type.hs"]),(TargetModule Torch.GraduallyTyped.Internal.Vector,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Internal/Vector.hs"]),(TargetModule Torch.GraduallyTyped.DType,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/DType.hs"]),(TargetModule Torch.GraduallyTyped.Shape,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Shape.hs"]),(TargetModule Torch.GraduallyTyped.Tensor.MathOperations,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/MathOperations.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.T5.ThreeB,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/T5/ThreeB.hs"]),(TargetModule Torch.GraduallyTyped.NN.Functional.Linear,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Functional/Linear.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.T5.Large,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/T5/Large.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.RoBERTa,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/RoBERTa.hs"]),(TargetModule Torch.GraduallyTyped.Scalar,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Scalar.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.GCrossAttention,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/GCrossAttention.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.T5.Common,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/T5/Common.hs"]),(TargetModule Torch.GraduallyTyped.LearningRateSchedules,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/LearningRateSchedules.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.Pegasus.Common,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Pegasus/Common.hs"]),(TargetModule Torch.GraduallyTyped.Tensor.MathOperations.BlasLapack,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/MathOperations/BlasLapack.hs"]),(TargetModule Torch.GraduallyTyped.NN.Linear,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Linear.hs"]),(TargetModule Torch.Language,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/Language.hs"]),(TargetModule Torch.GraduallyTyped.Index.Type,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Index/Type.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.Generation,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs"]),(TargetModule Torch.GraduallyTyped.Tensor.MathOperations.Other,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/MathOperations/Other.hs"]),(TargetModule Torch.GraduallyTyped.Device,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Device.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.BART,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/BART.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.BART.Common,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/BART/Common.hs"]),(TargetModule Control.Monad.Fresh,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Control/Monad/Fresh.hs"]),(TargetModule Torch.GraduallyTyped,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped.hs"]),(TargetModule Torch.GraduallyTyped.Prelude.TypeLits,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Prelude/TypeLits.hs"]),(TargetModule Torch.GraduallyTyped.NN.Type,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Type.hs"]),(TargetModule Torch.GraduallyTyped.Tensor.MathOperations.Reduction,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/MathOperations/Reduction.hs"]),(TargetModule Torch.GraduallyTyped.Tensor,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor.hs"]),(TargetModule Torch.GraduallyTyped.NN,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN.hs"]),(TargetModule Torch.GraduallyTyped.NN.Class,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Class.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.T5.Generation,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/T5/Generation.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.GStack,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/GStack.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.Pegasus.XSum,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Pegasus/XSum.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.T5,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/T5.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.BART.Base,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/BART/Base.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.GFeedForwardNetwork,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/GFeedForwardNetwork.hs"]),(TargetModule Torch.GraduallyTyped.NN.Functional.Dropout,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Functional/Dropout.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.GEncoderOnly,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/GEncoderOnly.hs"]),(TargetModule Torch.GraduallyTyped.Tensor.Other,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/Other.hs"]),(TargetModule Torch.GraduallyTyped.NN.Functional.Normalization,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Functional/Normalization.hs"]),(TargetModule Torch.GraduallyTyped.NN.Activation,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Activation.hs"]),(TargetModule Torch.GraduallyTyped.NN.Initialization,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Initialization.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.GLMHead,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/GLMHead.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.GSelfAttention,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/GSelfAttention.hs"]),(TargetModule Torch.GraduallyTyped.Prelude,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Prelude.hs"]),(TargetModule Torch.GraduallyTyped.NN.Functional.NonLinearActivation,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Functional/NonLinearActivation.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.RoBERTa.Common,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/RoBERTa/Common.hs"]),(TargetModule Torch.GraduallyTyped.Internal.Void,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Internal/Void.hs"]),(TargetModule Torch.GraduallyTyped.Index.Class,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Index/Class.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.GMultiHeadAttention,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/GMultiHeadAttention.hs"]),(TargetModule Torch.GraduallyTyped.Index,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Index.hs"]),(TargetModule Torch.GraduallyTyped.Tensor.MathOperations.Spectral,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/MathOperations/Spectral.hs"]),(TargetModule Torch.GraduallyTyped.NN.Functional.Activation,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Functional/Activation.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.BERT,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/BERT.hs"]),(TargetModule Torch.GraduallyTyped.NN.Normalization,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Normalization.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.BERT.Common,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/BERT/Common.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.T5.ElevenB,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/T5/ElevenB.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.T5.Small,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/T5/Small.hs"]),(TargetModule Torch.GraduallyTyped.Tensor.IndexingSlicingJoining,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/IndexingSlicingJoining.hs"]),(TargetModule Torch.GraduallyTyped.Prelude.List,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Prelude/List.hs"]),(TargetModule Torch.GraduallyTyped.Tensor.Creation,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/Creation.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.GPooler,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/GPooler.hs"]),(TargetModule Torch.GraduallyTyped.Prelude.Maybe,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Prelude/Maybe.hs"]),(TargetModule Torch.GraduallyTyped.Unify,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Unify.hs"]),(TargetModule Torch.GraduallyTyped.Tensor.MathOperations.Pointwise,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/MathOperations/Pointwise.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.GEncoderDecoder,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/GEncoderDecoder.hs"]),(TargetFile NormalizedFilePath "/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs",fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs"]),(TargetModule Torch.GraduallyTyped.Internal.TensorOptions,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Internal/TensorOptions.hs"]),(TargetModule Torch.GraduallyTyped.Tensor.Indexing,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/Indexing.hs"]),(TargetModule Torch.GraduallyTyped.RequiresGradient,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/RequiresGradient.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.GTransformer,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/GTransformer.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.GBlock,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/GBlock.hs"]),(TargetModule Torch.GraduallyTyped.NN.Dropout,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Dropout.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.BERT.BaseUncased,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/BERT/BaseUncased.hs"]),(TargetModule Torch.Language.SpiderSQL,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/Language/SpiderSQL.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.T5.Base,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/T5/Base.hs"]),(TargetModule Torch.GraduallyTyped.Shape.Class,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Shape/Class.hs"]),(TargetModule Torch.GraduallyTyped.NN.Functional.Loss,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Functional/Loss.hs"]),(TargetModule Torch.Data.Parser,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/Data/Parser.hs"]),(TargetModule Torch.GraduallyTyped.NN.Transformer.RoBERTa.Base,fromList ["/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/RoBERTa/Base.hs"])]
2021-08-20 19:33:17.79174 [ThreadId 127] DEBUG hls:	Restarting build session for keys [GetModificationTime_ {missingFileDiagnostics = True}; /Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs,IsFileOfInterest; /Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs,GhcSessionIO; ] (aborting the previous one took 0.00s)
2021-08-20 19:33:17.792002 [ThreadId 60] DEBUG hls:	Finishing build session(exception: AsyncCancelled)
2021-08-20 19:33:17.801691 [ThreadId 263] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs"
2021-08-20 19:33:17.815742 [ThreadId 269] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "fp" "/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs"
2021-08-20 19:33:17.837733 [ThreadId 425] INFO hls:	finish: ModuleName.ghcSession (took 0.04s)
2021-08-20 19:33:17.83777 [ThreadId 423] INFO hls:	finish: ModuleName.ghcSession (took 0.04s)
2021-08-20 19:33:17.837765 [ThreadId 426] INFO hls:	finish: ModuleName.ghcSession (took 0.04s)
2021-08-20 19:33:17.837837 [ThreadId 424] INFO hls:	finish: ModuleName.ghcSession (took 0.04s)
2021-08-20 19:33:17.837828 [ThreadId 427] INFO hls:	finish: ModuleName.ghcSession (took 0.04s)
2021-08-20 19:33:17.837816 [ThreadId 430] INFO hls:	finish: ModuleName.ghcSession (took 0.02s)

<no location info>: warning: [-Wmissed-extra-shared-lib]
    dlopen(libtokenizers_haskell.dylib, 5): image not found
    It's OK if you don't want to use symbols from it directly.
    (the package DLL is loaded by the system linker
     which manages dependencies by itself).
2021-08-20 19:33:18.48685 [ThreadId 443] INFO hls:	finish: ModuleName.ghcSession (took 0.00s)
2021-08-20 19:33:18.486517 [ThreadId 549] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "fp" "/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs"
2021-08-20 19:33:18.487115 [ThreadId 556] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "fp" "/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs"
2021-08-20 19:33:18.487494 [ThreadId 443] INFO hls:	finish: ModuleName.ghcSession (took 0.00s)
2021-08-20 19:33:18.488213 [ThreadId 563] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "fp" "/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Transformer/Generation.hs"

<no location info>: warning: [-Wmissed-extra-shared-lib]
    dlopen(libstdc++.dylib, 5): image not found
    It's OK if you don't want to use symbols from it directly.
    (the package DLL is loaded by the system linker
     which manages dependencies by itself).

<no location info>: warning: [-Wmissed-extra-shared-lib]
    dlopen(libstdc++.dylib, 5): image not found
    It's OK if you don't want to use symbols from it directly.
    (the package DLL is loaded by the system linker
     which manages dependencies by itself).
2021-08-20 19:33:19.464232 [ThreadId 437] INFO hls:	finish: ModuleName.ghcSession (took 0.00s)
2021-08-20 19:33:19.470608 [ThreadId 436] INFO hls:	finish: ModuleName.GetParsedModule (took 1.63s)
2021-08-20 19:33:19.470738 [ThreadId 436] INFO hls:	finish: Pragmas.GetParsedModule (took 1.31s)
2021-08-20 19:33:19.470767 [ThreadId 447] INFO hls:	finish: ModuleName.GetParsedModule (took 1.63s)
2021-08-20 19:33:19.47084 [ThreadId 443] INFO hls:	finish: Pragmas.GetParsedModule (took 1.67s)
2021-08-20 19:33:19.470849 [ThreadId 436] INFO hls:	finish: ModuleName.GetParsedModule (took 1.63s)
2021-08-20 19:33:19.470887 [ThreadId 447] INFO hls:	finish: GhcideCodeActions.getParsedModule (took 1.67s)
2021-08-20 19:33:19.471037 [ThreadId 443] INFO hls:	finish: Outline (took 1.67s)
2021-08-20 19:33:19.471078 [ThreadId 447] INFO hls:	finish: eval.GetParsedModuleWithComments (took 1.67s)
2021-08-20 19:33:19.471125 [ThreadId 446] INFO hls:	finish: eval.GetParsedModuleWithComments (took 1.67s)
2021-08-20 19:33:19.471271 [ThreadId 436] INFO hls:	finish: Pragmas.GetFileContents (took 0.00s)
2021-08-20 19:33:19.471774 [ThreadId 447] INFO hls:	finish: GhcideCodeActions.getParsedModule (took 1.31s)
2021-08-20 19:33:19.471859 [ThreadId 443] INFO hls:	finish: eval.GetParsedModuleWithComments (took 1.67s)
2021-08-20 19:33:19.471942 [ThreadId 446] INFO hls:	finish: eval.GetParsedModuleWithComments (took 1.66s)
2021-08-20 19:33:19.471973 [ThreadId 436] INFO hls:	finish: HaddockComments.GetAnnotatedParsedSource (took 1.67s)
2021-08-20 19:33:19.472091 [ThreadId 447] INFO hls:	finish: ModuleName.GetParsedModule (took 1.63s)
2021-08-20 19:33:19.472207 [ThreadId 446] INFO hls:	finish: Outline (took 1.67s)
2021-08-20 19:33:19.472231 [ThreadId 436] INFO hls:	finish: eval.GetParsedModuleWithComments (took 1.67s)
2021-08-20 19:33:19.472239 [ThreadId 447] INFO hls:	finish: ModuleName.GetParsedModule (took 0.00s)
2021-08-20 19:33:19.472296 [ThreadId 446] INFO hls:	finish: ModuleName.GetParsedModule (took 1.63s)
2021-08-20 19:33:19.472337 [ThreadId 436] INFO hls:	finish: HaddockComments.GetAnnotatedParsedSource (took 1.31s)
2021-08-20 19:33:19.472118 [ThreadId 443] INFO hls:	finish: eval.GetParsedModuleWithComments (took 0.98s)
2021-08-20 19:33:19.472502 [ThreadId 446] INFO hls:	finish: ModuleName.GetParsedModule (took 1.63s)
2021-08-20 19:33:19.472509 [ThreadId 447] INFO hls:	finish: eval.GetParsedModuleWithComments (took 0.98s)
2021-08-20 19:33:19.472543 [ThreadId 436] INFO hls:	finish: eval.GetParsedModuleWithComments (took 1.67s)
2021-08-20 19:33:19.472584 [ThreadId 446] INFO hls:	finish: importLens (took 1.67s)
2021-08-20 19:33:19.472601 [ThreadId 436] INFO hls:	finish: importLens (took 0.98s)
2021-08-20 19:33:19.472733 [ThreadId 436] INFO hls:	finish: Outline (took 1.31s)
2021-08-20 19:33:19.472976 [ThreadId 443] INFO hls:	finish: ModuleName.GetParsedModule (took 0.98s)
2021-08-20 19:33:19.473006 [ThreadId 436] INFO hls:	finish: eval.GetParsedModuleWithComments (took 0.99s)
2021-08-20 19:33:19.473058 [ThreadId 443] INFO hls:	finish: ModuleName.GetParsedModule (took 0.98s)
2021-08-20 19:33:19.472556 [ThreadId 144] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "excluded comments" "[]"
2021-08-20 19:33:19.472886 [ThreadId 207] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "excluded comments" "[]"
2021-08-20 19:33:19.471294 [ThreadId 162] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "excluded comments" "[]"
2021-08-20 19:33:19.473014 [ThreadId 549] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "excluded comments" "[]"
2021-08-20 19:33:19.472939 [ThreadId 556] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "excluded comments" "[]"
2021-08-20 19:33:19.471921 [ThreadId 177] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "excluded comments" "[]"
2021-08-20 19:33:19.47457 [ThreadId 556] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "comments" "Comments {lineComments = fromList [], blockComments = fromList [(Range {_start = Position {_line = 0, _character = 0}, _end = Position {_line = 0, _character = 26}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE DataKinds #-}\"}),(Range {_start = Position {_line = 1, _character = 0}, _end = Position {_line = 1, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE FlexibleContexts #-}\"}),(Range {_start = Position {_line = 2, _character = 0}, _end = Position {_line = 2, _character = 22}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE GADTs #-}\"}),(Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 38}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PartialTypeSignatures #-}\"}),(Range {_start = Position {_line = 4, _character = 0}, _end = Position {_line = 4, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PatternSynonyms #-}\"}),(Range {_start = Position {_line = 5, _character = 0}, _end = Position {_line = 5, _character = 27}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RankNTypes #-}\"}),(Range {_start = Position {_line = 6, _character = 0}, _end = Position {_line = 6, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RecordWildCards #-}\"}),(Range {_start = Position {_line = 7, _character = 0}, _end = Position {_line = 7, _character = 36}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE ScopedTypeVariables #-}\"}),(Range {_start = Position {_line = 8, _character = 0}, _end = Position {_line = 8, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeApplications #-}\"}),(Range {_start = Position {_line = 9, _character = 0}, _end = Position {_line = 9, _character = 29}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeFamilies #-}\"}),(Range {_start = Position {_line = 10, _character = 0}, _end = Position {_line = 10, _character = 30}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeOperators #-}\"})]}"
2021-08-20 19:33:19.474461 [ThreadId 207] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "comments" "Comments {lineComments = fromList [], blockComments = fromList [(Range {_start = Position {_line = 0, _character = 0}, _end = Position {_line = 0, _character = 26}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE DataKinds #-}\"}),(Range {_start = Position {_line = 1, _character = 0}, _end = Position {_line = 1, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE FlexibleContexts #-}\"}),(Range {_start = Position {_line = 2, _character = 0}, _end = Position {_line = 2, _character = 22}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE GADTs #-}\"}),(Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 38}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PartialTypeSignatures #-}\"}),(Range {_start = Position {_line = 4, _character = 0}, _end = Position {_line = 4, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PatternSynonyms #-}\"}),(Range {_start = Position {_line = 5, _character = 0}, _end = Position {_line = 5, _character = 27}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RankNTypes #-}\"}),(Range {_start = Position {_line = 6, _character = 0}, _end = Position {_line = 6, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RecordWildCards #-}\"}),(Range {_start = Position {_line = 7, _character = 0}, _end = Position {_line = 7, _character = 36}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE ScopedTypeVariables #-}\"}),(Range {_start = Position {_line = 8, _character = 0}, _end = Position {_line = 8, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeApplications #-}\"}),(Range {_start = Position {_line = 9, _character = 0}, _end = Position {_line = 9, _character = 29}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeFamilies #-}\"}),(Range {_start = Position {_line = 10, _character = 0}, _end = Position {_line = 10, _character = 30}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeOperators #-}\"})]}"
2021-08-20 19:33:19.47444 [ThreadId 144] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "comments" "Comments {lineComments = fromList [], blockComments = fromList [(Range {_start = Position {_line = 0, _character = 0}, _end = Position {_line = 0, _character = 26}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE DataKinds #-}\"}),(Range {_start = Position {_line = 1, _character = 0}, _end = Position {_line = 1, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE FlexibleContexts #-}\"}),(Range {_start = Position {_line = 2, _character = 0}, _end = Position {_line = 2, _character = 22}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE GADTs #-}\"}),(Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 38}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PartialTypeSignatures #-}\"}),(Range {_start = Position {_line = 4, _character = 0}, _end = Position {_line = 4, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PatternSynonyms #-}\"}),(Range {_start = Position {_line = 5, _character = 0}, _end = Position {_line = 5, _character = 27}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RankNTypes #-}\"}),(Range {_start = Position {_line = 6, _character = 0}, _end = Position {_line = 6, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RecordWildCards #-}\"}),(Range {_start = Position {_line = 7, _character = 0}, _end = Position {_line = 7, _character = 36}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE ScopedTypeVariables #-}\"}),(Range {_start = Position {_line = 8, _character = 0}, _end = Position {_line = 8, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeApplications #-}\"}),(Range {_start = Position {_line = 9, _character = 0}, _end = Position {_line = 9, _character = 29}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeFamilies #-}\"}),(Range {_start = Position {_line = 10, _character = 0}, _end = Position {_line = 10, _character = 30}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeOperators #-}\"})]}"
2021-08-20 19:33:19.474511 [ThreadId 162] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "comments" "Comments {lineComments = fromList [], blockComments = fromList [(Range {_start = Position {_line = 0, _character = 0}, _end = Position {_line = 0, _character = 26}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE DataKinds #-}\"}),(Range {_start = Position {_line = 1, _character = 0}, _end = Position {_line = 1, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE FlexibleContexts #-}\"}),(Range {_start = Position {_line = 2, _character = 0}, _end = Position {_line = 2, _character = 22}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE GADTs #-}\"}),(Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 38}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PartialTypeSignatures #-}\"}),(Range {_start = Position {_line = 4, _character = 0}, _end = Position {_line = 4, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PatternSynonyms #-}\"}),(Range {_start = Position {_line = 5, _character = 0}, _end = Position {_line = 5, _character = 27}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RankNTypes #-}\"}),(Range {_start = Position {_line = 6, _character = 0}, _end = Position {_line = 6, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RecordWildCards #-}\"}),(Range {_start = Position {_line = 7, _character = 0}, _end = Position {_line = 7, _character = 36}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE ScopedTypeVariables #-}\"}),(Range {_start = Position {_line = 8, _character = 0}, _end = Position {_line = 8, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeApplications #-}\"}),(Range {_start = Position {_line = 9, _character = 0}, _end = Position {_line = 9, _character = 29}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeFamilies #-}\"}),(Range {_start = Position {_line = 10, _character = 0}, _end = Position {_line = 10, _character = 30}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeOperators #-}\"})]}"
2021-08-20 19:33:19.474607 [ThreadId 177] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "comments" "Comments {lineComments = fromList [], blockComments = fromList [(Range {_start = Position {_line = 0, _character = 0}, _end = Position {_line = 0, _character = 26}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE DataKinds #-}\"}),(Range {_start = Position {_line = 1, _character = 0}, _end = Position {_line = 1, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE FlexibleContexts #-}\"}),(Range {_start = Position {_line = 2, _character = 0}, _end = Position {_line = 2, _character = 22}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE GADTs #-}\"}),(Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 38}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PartialTypeSignatures #-}\"}),(Range {_start = Position {_line = 4, _character = 0}, _end = Position {_line = 4, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PatternSynonyms #-}\"}),(Range {_start = Position {_line = 5, _character = 0}, _end = Position {_line = 5, _character = 27}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RankNTypes #-}\"}),(Range {_start = Position {_line = 6, _character = 0}, _end = Position {_line = 6, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RecordWildCards #-}\"}),(Range {_start = Position {_line = 7, _character = 0}, _end = Position {_line = 7, _character = 36}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE ScopedTypeVariables #-}\"}),(Range {_start = Position {_line = 8, _character = 0}, _end = Position {_line = 8, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeApplications #-}\"}),(Range {_start = Position {_line = 9, _character = 0}, _end = Position {_line = 9, _character = 29}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeFamilies #-}\"}),(Range {_start = Position {_line = 10, _character = 0}, _end = Position {_line = 10, _character = 30}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeOperators #-}\"})]}"
2021-08-20 19:33:19.474546 [ThreadId 549] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "comments" "Comments {lineComments = fromList [], blockComments = fromList [(Range {_start = Position {_line = 0, _character = 0}, _end = Position {_line = 0, _character = 26}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE DataKinds #-}\"}),(Range {_start = Position {_line = 1, _character = 0}, _end = Position {_line = 1, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE FlexibleContexts #-}\"}),(Range {_start = Position {_line = 2, _character = 0}, _end = Position {_line = 2, _character = 22}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE GADTs #-}\"}),(Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 38}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PartialTypeSignatures #-}\"}),(Range {_start = Position {_line = 4, _character = 0}, _end = Position {_line = 4, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PatternSynonyms #-}\"}),(Range {_start = Position {_line = 5, _character = 0}, _end = Position {_line = 5, _character = 27}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RankNTypes #-}\"}),(Range {_start = Position {_line = 6, _character = 0}, _end = Position {_line = 6, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RecordWildCards #-}\"}),(Range {_start = Position {_line = 7, _character = 0}, _end = Position {_line = 7, _character = 36}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE ScopedTypeVariables #-}\"}),(Range {_start = Position {_line = 8, _character = 0}, _end = Position {_line = 8, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeApplications #-}\"}),(Range {_start = Position {_line = 9, _character = 0}, _end = Position {_line = 9, _character = 29}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeFamilies #-}\"}),(Range {_start = Position {_line = 10, _character = 0}, _end = Position {_line = 10, _character = 30}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeOperators #-}\"})]}"
2021-08-20 19:33:19.471214 [ThreadId 192] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "excluded comments" "[]"
2021-08-20 19:33:19.475069 [ThreadId 556] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "Tests" "0 tests in 11 sections 0 setups 0 lenses."
2021-08-20 19:33:19.475142 [ThreadId 207] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "Tests" "0 tests in 11 sections 0 setups 0 lenses."
2021-08-20 19:33:19.475229 [ThreadId 144] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "Tests" "0 tests in 11 sections 0 setups 0 lenses."
2021-08-20 19:33:19.479663 [ThreadId 269] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "excluded comments" "[]"
2021-08-20 19:33:19.479669 [ThreadId 563] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "excluded comments" "[]"
2021-08-20 19:33:19.483242 [ThreadId 446] INFO hls:	finish: Pragmas.GetFileContents (took 0.00s)
2021-08-20 19:33:19.485327 [ThreadId 162] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "Tests" "0 tests in 11 sections 0 setups 0 lenses."
2021-08-20 19:33:19.487107 [ThreadId 556] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "tests" "0.01s"
2021-08-20 19:33:19.487141 [ThreadId 207] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "tests" "0.01s"
2021-08-20 19:33:19.486916 [ThreadId 177] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "Tests" "0 tests in 11 sections 0 setups 0 lenses."
2021-08-20 19:33:19.48703 [ThreadId 549] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "Tests" "0 tests in 11 sections 0 setups 0 lenses."
2021-08-20 19:33:19.487065 [ThreadId 192] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "comments" "Comments {lineComments = fromList [], blockComments = fromList [(Range {_start = Position {_line = 0, _character = 0}, _end = Position {_line = 0, _character = 26}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE DataKinds #-}\"}),(Range {_start = Position {_line = 1, _character = 0}, _end = Position {_line = 1, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE FlexibleContexts #-}\"}),(Range {_start = Position {_line = 2, _character = 0}, _end = Position {_line = 2, _character = 22}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE GADTs #-}\"}),(Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 38}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PartialTypeSignatures #-}\"}),(Range {_start = Position {_line = 4, _character = 0}, _end = Position {_line = 4, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PatternSynonyms #-}\"}),(Range {_start = Position {_line = 5, _character = 0}, _end = Position {_line = 5, _character = 27}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RankNTypes #-}\"}),(Range {_start = Position {_line = 6, _character = 0}, _end = Position {_line = 6, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RecordWildCards #-}\"}),(Range {_start = Position {_line = 7, _character = 0}, _end = Position {_line = 7, _character = 36}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE ScopedTypeVariables #-}\"}),(Range {_start = Position {_line = 8, _character = 0}, _end = Position {_line = 8, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeApplications #-}\"}),(Range {_start = Position {_line = 9, _character = 0}, _end = Position {_line = 9, _character = 29}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeFamilies #-}\"}),(Range {_start = Position {_line = 10, _character = 0}, _end = Position {_line = 10, _character = 30}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeOperators #-}\"})]}"
2021-08-20 19:33:19.488804 [ThreadId 144] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "tests" "0.01s"
2021-08-20 19:33:19.488931 [ThreadId 162] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "tests" "0.00s"
2021-08-20 19:33:19.488829 [ThreadId 269] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "comments" "Comments {lineComments = fromList [], blockComments = fromList [(Range {_start = Position {_line = 0, _character = 0}, _end = Position {_line = 0, _character = 26}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE DataKinds #-}\"}),(Range {_start = Position {_line = 1, _character = 0}, _end = Position {_line = 1, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE FlexibleContexts #-}\"}),(Range {_start = Position {_line = 2, _character = 0}, _end = Position {_line = 2, _character = 22}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE GADTs #-}\"}),(Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 38}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PartialTypeSignatures #-}\"}),(Range {_start = Position {_line = 4, _character = 0}, _end = Position {_line = 4, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PatternSynonyms #-}\"}),(Range {_start = Position {_line = 5, _character = 0}, _end = Position {_line = 5, _character = 27}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RankNTypes #-}\"}),(Range {_start = Position {_line = 6, _character = 0}, _end = Position {_line = 6, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RecordWildCards #-}\"}),(Range {_start = Position {_line = 7, _character = 0}, _end = Position {_line = 7, _character = 36}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE ScopedTypeVariables #-}\"}),(Range {_start = Position {_line = 8, _character = 0}, _end = Position {_line = 8, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeApplications #-}\"}),(Range {_start = Position {_line = 9, _character = 0}, _end = Position {_line = 9, _character = 29}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeFamilies #-}\"}),(Range {_start = Position {_line = 10, _character = 0}, _end = Position {_line = 10, _character = 30}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeOperators #-}\"})]}"
2021-08-20 19:33:19.488866 [ThreadId 563] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "comments" "Comments {lineComments = fromList [], blockComments = fromList [(Range {_start = Position {_line = 0, _character = 0}, _end = Position {_line = 0, _character = 26}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE DataKinds #-}\"}),(Range {_start = Position {_line = 1, _character = 0}, _end = Position {_line = 1, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE FlexibleContexts #-}\"}),(Range {_start = Position {_line = 2, _character = 0}, _end = Position {_line = 2, _character = 22}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE GADTs #-}\"}),(Range {_start = Position {_line = 3, _character = 0}, _end = Position {_line = 3, _character = 38}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PartialTypeSignatures #-}\"}),(Range {_start = Position {_line = 4, _character = 0}, _end = Position {_line = 4, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE PatternSynonyms #-}\"}),(Range {_start = Position {_line = 5, _character = 0}, _end = Position {_line = 5, _character = 27}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RankNTypes #-}\"}),(Range {_start = Position {_line = 6, _character = 0}, _end = Position {_line = 6, _character = 32}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE RecordWildCards #-}\"}),(Range {_start = Position {_line = 7, _character = 0}, _end = Position {_line = 7, _character = 36}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE ScopedTypeVariables #-}\"}),(Range {_start = Position {_line = 8, _character = 0}, _end = Position {_line = 8, _character = 33}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeApplications #-}\"}),(Range {_start = Position {_line = 9, _character = 0}, _end = Position {_line = 9, _character = 29}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeFamilies #-}\"}),(Range {_start = Position {_line = 10, _character = 0}, _end = Position {_line = 10, _character = 30}},RawBlockComment {getRawBlockComment = \"{-# LANGUAGE TypeOperators #-}\"})]}"
2021-08-20 19:33:19.496068 [ThreadId 556] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "codeLens" "1.01s"
2021-08-20 19:33:19.496141 [ThreadId 207] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "codeLens" "2.33s"
2021-08-20 19:33:19.496172 [ThreadId 177] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "tests" "0.01s"
2021-08-20 19:33:19.497703 [ThreadId 549] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "tests" "0.01s"
2021-08-20 19:33:19.497891 [ThreadId 144] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "codeLens" "2.97s"
2021-08-20 19:33:19.497925 [ThreadId 162] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "codeLens" "2.71s"
2021-08-20 19:33:19.497823 [ThreadId 192] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "Tests" "0 tests in 11 sections 0 setups 0 lenses."
2021-08-20 19:33:19.498189 [ThreadId 177] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "codeLens" "2.70s"
2021-08-20 19:33:19.497995 [ThreadId 269] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "Tests" "0 tests in 11 sections 0 setups 0 lenses."
2021-08-20 19:33:19.498274 [ThreadId 549] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "codeLens" "1.01s"
2021-08-20 19:33:19.498107 [ThreadId 563] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "Tests" "0 tests in 11 sections 0 setups 0 lenses."
2021-08-20 19:33:19.49835 [ThreadId 192] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "tests" "0.00s"
2021-08-20 19:33:19.498403 [ThreadId 269] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "tests" "0.00s"
2021-08-20 19:33:19.49848 [ThreadId 192] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "codeLens" "2.59s"
2021-08-20 19:33:19.498458 [ThreadId 563] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "tests" "0.00s"
2021-08-20 19:33:19.49851 [ThreadId 269] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "codeLens" "1.68s"
2021-08-20 19:33:19.498556 [ThreadId 563] DEBUG hls:	src/Ide/Plugin/Eval/CodeLens.hs:192:15 "codeLens" "1.01s"
2021-08-20 19:33:20.30474 [ThreadId 1608] DEBUG hls:	SUCCEEDED LOADING HIE FILE FOR:"/Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7/Torch/GraduallyTyped/Scalar.hie"
2021-08-20 19:33:20.304811 [ThreadId 1608] DEBUG hls:	Re-indexing hie file for/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Scalar.hs
2021-08-20 19:33:20.799509 [ThreadId 1627] DEBUG hls:	SUCCEEDED LOADING HIE FILE FOR:"/Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7/Torch/GraduallyTyped/Prelude.hie"
2021-08-20 19:33:20.799586 [ThreadId 1627] DEBUG hls:	Re-indexing hie file for/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Prelude.hs
2021-08-20 19:33:20.837144 [ThreadId 1686] DEBUG hls:	SUCCEEDED LOADING HIE FILE FOR:"/Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7/Torch/GraduallyTyped/Index/Type.hie"
2021-08-20 19:33:20.837231 [ThreadId 1686] DEBUG hls:	Re-indexing hie file for/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Index/Type.hs
2021-08-20 19:33:20.860814 [ThreadId 1691] DEBUG hls:	SUCCEEDED LOADING HIE FILE FOR:"/Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7/Torch/GraduallyTyped/RequiresGradient.hie"
2021-08-20 19:33:20.860904 [ThreadId 1691] DEBUG hls:	Re-indexing hie file for/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/RequiresGradient.hs
2021-08-20 19:33:20.872765 [ThreadId 1695] DEBUG hls:	SUCCEEDED LOADING HIE FILE FOR:"/Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7/Torch/GraduallyTyped/Layout.hie"
2021-08-20 19:33:20.872884 [ThreadId 1695] DEBUG hls:	Re-indexing hie file for/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Layout.hs
2021-08-20 19:33:20.87562 [ThreadId 1698] DEBUG hls:	SUCCEEDED LOADING HIE FILE FOR:"/Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7/Torch/GraduallyTyped/Device.hie"
2021-08-20 19:33:20.875714 [ThreadId 1698] DEBUG hls:	Re-indexing hie file for/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Device.hs
2021-08-20 19:33:20.916573 [ThreadId 1701] DEBUG hls:	SUCCEEDED LOADING HIE FILE FOR:"/Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7/Torch/GraduallyTyped/DType.hie"
2021-08-20 19:33:20.916691 [ThreadId 1701] DEBUG hls:	Re-indexing hie file for/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/DType.hs
2021-08-20 19:33:21.00468 [ThreadId 1704] DEBUG hls:	SUCCEEDED LOADING HIE FILE FOR:"/Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7/Torch/GraduallyTyped/Shape/Type.hie"
2021-08-20 19:33:21.004767 [ThreadId 1704] DEBUG hls:	Re-indexing hie file for/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Shape/Type.hs
2021-08-20 19:33:21.285991 [ThreadId 1770] DEBUG hls:	SUCCEEDED LOADING HIE FILE FOR:"/Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7/Torch/GraduallyTyped/Shape/Class.hie"
2021-08-20 19:33:21.286092 [ThreadId 1770] DEBUG hls:	Re-indexing hie file for/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Shape/Class.hs
2021-08-20 19:33:21.997429 [ThreadId 1798] DEBUG hls:	SUCCEEDED LOADING HIE FILE FOR:"/Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7/Torch/GraduallyTyped/Tensor/Type.hie"
2021-08-20 19:33:21.997528 [ThreadId 1798] DEBUG hls:	Re-indexing hie file for/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/Type.hs
2021-08-20 19:33:22.071061 [ThreadId 1955] DEBUG hls:	SUCCEEDED LOADING HIE FILE FOR:"/Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7/Torch/GraduallyTyped/Random.hie"
2021-08-20 19:33:22.071159 [ThreadId 1955] DEBUG hls:	Re-indexing hie file for/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Random.hs
2021-08-20 19:33:22.101826 [ThreadId 1989] DEBUG hls:	SUCCEEDED LOADING HIE FILE FOR:"/Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7/Torch/GraduallyTyped/Tensor/MathOperations/Comparison.hie"
2021-08-20 19:33:22.10201 [ThreadId 1989] DEBUG hls:	Re-indexing hie file for/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/MathOperations/Comparison.hs
2021-08-20 19:33:22.16855 [ThreadId 1995] DEBUG hls:	SUCCEEDED LOADING HIE FILE FOR:"/Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7/Torch/GraduallyTyped/Tensor/Creation.hie"
2021-08-20 19:33:22.168645 [ThreadId 1995] DEBUG hls:	Re-indexing hie file for/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/Creation.hs
2021-08-20 19:33:22.187677 [ThreadId 2002] DEBUG hls:	SUCCEEDED LOADING HIE FILE FOR:"/Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7/Torch/GraduallyTyped/Tensor/IndexingSlicingJoining.hie"
2021-08-20 19:33:22.187766 [ThreadId 2002] DEBUG hls:	Re-indexing hie file for/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/Tensor/IndexingSlicingJoining.hs
2021-08-20 19:33:22.783405 [ThreadId 2089] DEBUG hls:	SUCCEEDED LOADING HIE FILE FOR:"/Users/torsten.scholak/.cache/ghcide/hasktorch-gradually-typed-0.2.0.0-inplace-ad13d4d751279dd5fe5eb75e2dcbb5695e2f54b7/Torch/GraduallyTyped/NN/Class.hie"
2021-08-20 19:33:22.783486 [ThreadId 2089] DEBUG hls:	Re-indexing hie file for/Users/torsten.scholak/Projects/thirdParty/hasktorch/experimental/gradually-typed/src/Torch/GraduallyTyped/NN/Class.hs
2021-08-20 19:33:22.918091 [ThreadId 2618] INFO hls:	finish: codeLens.TypeCheck (took 5.12s)
2021-08-20 19:33:22.918225 [ThreadId 2619] INFO hls:	finish: codeLens.TypeCheck (took 5.12s)
2021-08-20 19:33:22.918283 [ThreadId 2621] INFO hls:	finish: codeLens.TypeCheck (took 5.12s)
2021-08-20 19:33:22.918292 [ThreadId 2626] INFO hls:	finish: codeLens.TypeCheck (took 5.10s)
2021-08-20 19:33:22.9183 [ThreadId 2624] INFO hls:	finish: codeLens.TypeCheck (took 5.12s)
2021-08-20 19:33:22.918316 [ThreadId 2628] INFO hls:	finish: codeLens.TypeCheck (took 4.43s)
2021-08-20 19:33:22.91831 [ThreadId 2625] INFO hls:	finish: codeLens.TypeCheck (took 5.12s)
2021-08-20 19:33:22.918326 [ThreadId 2630] INFO hls:	finish: codeLens.TypeCheck (took 3.45s)
2021-08-20 19:33:22.918378 [ThreadId 2629] INFO hls:	finish: codeLens.TypeCheck (took 3.45s)
2021-08-20 19:33:22.918353 [ThreadId 2627] INFO hls:	finish: retrie (took 4.76s)
2021-08-20 19:33:22.918372 [ThreadId 2620] INFO hls:	finish: retrie (took 5.12s)
2021-08-20 19:33:22.918479 [ThreadId 2623] INFO hls:	finish: MinimalImports (took 3.45s)
2021-08-20 19:33:22.918495 [ThreadId 2618] INFO hls:	finish:  (took 4.43s)
2021-08-20 19:33:22.918502 [ThreadId 2619] INFO hls:	finish:  (took 5.12s)
2021-08-20 19:33:22.91852 [ThreadId 2621] INFO hls:	finish:  (took 5.10s)
2021-08-20 19:33:22.918564 [ThreadId 2626] INFO hls:	finish:  (took 5.12s)
2021-08-20 19:33:22.91858 [ThreadId 2624] INFO hls:	finish:  (took 5.12s)
2021-08-20 19:33:22.918611 [ThreadId 2628] INFO hls:	finish:  (took 4.43s)
2021-08-20 19:33:22.918626 [ThreadId 2625] INFO hls:	finish:  (took 5.12s)
2021-08-20 19:33:22.918716 [ThreadId 2629] INFO hls:	finish: MinimalImports (took 3.45s)
2021-08-20 19:33:22.918761 [ThreadId 2630] INFO hls:	finish:  (took 4.43s)
2021-08-20 19:33:22.918763 [ThreadId 2620] INFO hls:	finish:  (took 5.12s)
2021-08-20 19:33:22.938376 [ThreadId 2665] INFO hls:	finish: codeLens.GetBindings (took 0.02s)
2021-08-20 19:33:22.938435 [ThreadId 2666] INFO hls:	finish: codeLens.GetBindings (took 0.02s)
2021-08-20 19:33:22.938488 [ThreadId 2670] INFO hls:	finish: codeLens.GetBindings (took 0.02s)
2021-08-20 19:33:22.938509 [ThreadId 2669] INFO hls:	finish: codeLens.GetBindings (took 0.02s)
2021-08-20 19:33:22.938556 [ThreadId 2671] INFO hls:	finish: codeLens.GetBindings (took 0.02s)
2021-08-20 19:33:22.938544 [ThreadId 2668] INFO hls:	finish: codeLens.GetBindings (took 0.02s)
2021-08-20 19:33:22.938574 [ThreadId 2672] INFO hls:	finish: codeLens.GetBindings (took 0.02s)
2021-08-20 19:33:22.938582 [ThreadId 2667] INFO hls:	finish: codeLens.GetBindings (took 0.02s)
2021-08-20 19:33:22.93859 [ThreadId 2673] INFO hls:	finish: codeLens.GetBindings (took 0.02s)
2021-08-20 19:33:22.938733 [ThreadId 2682] INFO hls:	finish: codeLens.GetGlobalBindingTypeSigs (took 0.00s)
2021-08-20 19:33:22.938735 [ThreadId 2683] INFO hls:	finish: codeLens.GetGlobalBindingTypeSigs (took 0.00s)
2021-08-20 19:33:22.938781 [ThreadId 2684] INFO hls:	finish: codeLens.GetGlobalBindingTypeSigs (took 0.00s)
2021-08-20 19:33:22.938842 [ThreadId 2685] INFO hls:	finish: codeLens.GetGlobalBindingTypeSigs (took 0.00s)
2021-08-20 19:33:22.938876 [ThreadId 2688] INFO hls:	finish: codeLens.GetGlobalBindingTypeSigs (took 0.00s)
2021-08-20 19:33:22.938955 [ThreadId 2686] INFO hls:	finish: codeLens.GetGlobalBindingTypeSigs (took 0.00s)
2021-08-20 19:33:22.938968 [ThreadId 2687] INFO hls:	finish: codeLens.GetGlobalBindingTypeSigs (took 0.00s)
2021-08-20 19:33:22.938975 [ThreadId 2689] INFO hls:	finish: codeLens.GetGlobalBindingTypeSigs (took 0.00s)
2021-08-20 19:33:22.938983 [ThreadId 2690] INFO hls:	finish: codeLens.GetGlobalBindingTypeSigs (took 0.00s)
2021-08-20 19:33:22.969279 [ThreadId 2717] DEBUG hls:	finish: InitialLoad (took 5.14s)
2021-08-20 19:33:23.174656 [ThreadId 2730] INFO hls:	finish: Pragmas.GetParsedModule (took 0.00s)
2021-08-20 19:33:23.174675 [ThreadId 2734] INFO hls:	finish: GhcideCodeActions.GetFileContents (took 0.00s)
2021-08-20 19:33:23.174752 [ThreadId 2740] INFO hls:	finish: importLens (took 0.00s)
2021-08-20 19:33:23.174777 [ThreadId 2742] INFO hls:	finish: retrie (took 0.00s)
2021-08-20 19:33:23.174801 [ThreadId 2732] INFO hls:	finish: HaddockComments.GetAnnotatedParsedSource (took 0.00s)
2021-08-20 19:33:23.174821 [ThreadId 2738] INFO hls:	finish: GhcideCodeActions.GhcSession (took 0.00s)
2021-08-20 19:33:23.174944 [ThreadId 2744] INFO hls:	finish: Pragmas.GetFileContents (took 0.00s)
2021-08-20 19:33:23.174914 [ThreadId 2736] INFO hls:	finish: GhcideCodeActions.GetGlobalBindingTypeSigs (took 0.00s)
2021-08-20 19:33:23.175011 [ThreadId 2746] INFO hls:	finish: GhcideCodeActions.GetAnnotatedParsedSource (took 0.00s)
2021-08-20 19:33:23.175043 [ThreadId 2748] INFO hls:	finish: MinimalImports (took 0.00s)
2021-08-20 19:33:23.175112 [ThreadId 2751] INFO hls:	finish: GhcideCodeActions.TypeCheck (took 0.00s)
2021-08-20 19:33:23.175188 [ThreadId 2753] INFO hls:	finish: GhcideCodeActions.GetBindings (took 0.00s)
2021-08-20 19:33:23.175335 [ThreadId 2755] INFO hls:	finish: GhcideCodeActions.getIdeOptions (took 0.00s)
2021-08-20 19:33:23.175475 [ThreadId 2757] INFO hls:	finish: GhcideCodeActions.GetParsedModule (took 0.00s)
2021-08-20 19:33:23.175894 [ThreadId 2759] INFO hls:	finish: GhcideCodeActions.GetParsedModule (took 0.00s)
2021-08-20 19:33:23.175988 [ThreadId 2761] INFO hls:	finish: GhcideCodeActions.GetAnnotatedParsedSource (took 0.00s)
2021-08-20 19:33:23.176186 [ThreadId 2763] INFO hls:	finish: GhcideCodeActions.GetFileContents (took 0.00s)
2021-08-20 19:33:23.850961 [ThreadId 2765] INFO hls:	finish: GhcideCodeActions.GetAnnotatedParsedSource (took 0.00s)
2021-08-20 19:33:23.851418 [ThreadId 2767] INFO hls:	finish: GhcideCodeActions.GetParsedModule (took 0.00s)
2021-08-20 19:33:23.851478 [ThreadId 2769] INFO hls:	finish: GhcideCodeActions.GetFileContents (took 0.00s)
2021-08-20 19:33:23.852485 [ThreadId 2771] INFO hls:	finish: GhcideCodeActions.TypeCheck (took 0.00s)
2021-08-20 19:33:23.852536 [ThreadId 2773] INFO hls:	finish: GhcideCodeActions.GetHieAst (took 0.00s)
2021-08-20 19:33:23.853339 [ThreadId 2775] INFO hls:	finish: GhcideCodeActions.getParsedModule (took 0.00s)
haskell-language-server: Prelude.head: empty list
[Info  - 7:33:24 PM] Connection to server got closed. Server will restart.
[Error - 7:33:24 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/Users/torsten.scholak/.vscode/extensions/haskell.haskell-1.6.0/dist/extension.js:247:58221)
    at Object.dispose (/Users/torsten.scholak/.vscode/extensions/haskell.haskell-1.6.0/dist/extension.js:1:78088)
    at E.handleConnectionClosed (/Users/torsten.scholak/.vscode/extensions/haskell.haskell-1.6.0/dist/extension.js:1:78300)
    at E.handleConnectionClosed (/Users/torsten.scholak/.vscode/extensions/haskell.haskell-1.6.0/dist/extension.js:247:11275)
    at t (/Users/torsten.scholak/.vscode/extensions/haskell.haskell-1.6.0/dist/extension.js:1:76393)
    at invoke (/Users/torsten.scholak/.vscode/extensions/haskell.haskell-1.6.0/dist/extension.js:1:155272)
    at o.fire (/Users/torsten.scholak/.vscode/extensions/haskell.haskell-1.6.0/dist/extension.js:1:156033)
    at J (/Users/torsten.scholak/.vscode/extensions/haskell.haskell-1.6.0/dist/extension.js:247:47583)
    at invoke (/Users/torsten.scholak/.vscode/extensions/haskell.haskell-1.6.0/dist/extension.js:1:155272)
    at o.fire (/Users/torsten.scholak/.vscode/extensions/haskell.haskell-1.6.0/dist/extension.js:1:156033)
    at fireClose (/Users/torsten.scholak/.vscode/extensions/haskell.haskell-1.6.0/dist/extension.js:247:37656)
    at Socket.<anonymous> (/Users/torsten.scholak/.vscode/extensions/haskell.haskell-1.6.0/dist/extension.js:247:39236)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
```
</details>

### PR DESCRIPTION
**Pull request by tscholak**
closes #2118 
closes #2025 

- [x] added a test for when an unused import can be removed that ends in `.`
- [x] resolved a crash (`Prelude.head: empty list`) in hls when an unused import ends in `.`
- [x] add a test for when an unused qualified export ends in `.`

### CODE REVIEW

**Comment by tscholak** [comment]
@jneira @jhrcek @pepeiborra this is an attempt of a fix for both #2025 and #2118. At the moment I'm just avoiding a crash, but it now occurs to me that a true solution would also have to exhibit the correct expected behavior. However, I'm not familiar with the code I'm changing, and I have no idea what the expected behavior is.
What is supposed to happen here? Can someone please give me some input-output examples for this function?

**Comment by pepeiborra** [comment]
> What is supposed to happen here? Can someone please give me some input-output examples for this function?

The ghcide test suite enforces the expected behaviour for code actions. Ideally this PR would extend it with an example that displays the crash, and the expected behaviour should follow from other examples

**Comment by tscholak** [comment]
@pepeiborra Hm, I'm sorry, but I don't think so. Clearly there are no examples in the test suite that covered the issue with `(^.)`. That also means that there are no examples I can use to deduce the correct behavior given the occurrence of `(^.)` in the imports. So, I'm asking again. What is the expected output of this function for `(^.)` and variations thereof?

**Comment by tscholak** [comment]
@pepeiborra Perhaps I misunderstood. Are you saying that adding an example with `(^')` to the hls integration tests is enough because if I were to implement this function incorrectly, then somehow the existing logic in ghcide would pick this up and make the test fail? If so, then I understand where you're coming from. However, working like this also makes for a very slow iteration loop.

**Comment by jhrcek** [comment]
When I was looking at this issue I came up with this minimal reproducer consisting of two modules:
```haskell
module A where
(@.) = 0 -- Must have an operator whose name ends with '.'
a = 1 -- .. but also something else
```
```haskell
module B where
import A (a,(@.)) -- Must use something from module A, but not (@.) <- generating the code action to remove this import triggers the head error
x = a
````

The idea would be to add a new test case to this list: https://github.com/haskell/haskell-language-server/blob/28222e9005daf7e62d9a1099f8653bec56cfbc6b/ghcide/test/exe/Main.hs#L933

The current implementation of code "Remove redundant imports" code action is parsing stuff from GHC's warnings.
One step of processing is "unqualifying" the symbols which is the source of this issue, called from [here](https://github.com/haskell/haskell-language-server/blob/28222e9005daf7e62d9a1099f8653bec56cfbc6b/ghcide/src/Development/IDE/Plugin/CodeAction.hs#L309)

I *think* you cannot actually have something qualified in import
like this:
```haskell
import Some.Module ( x, y, ... {- there can never be qualified thing like B.something in this list if I understand haskell syntax well enough.. -})
```
So the fix *might* be as simple as removing the "unqualify" call from "modifyBinding" which is called from the function linked above.
Unfortunately the function `modifyBinding` is also used for processing unused exports, where I think you CAN have qualified imports. So the fix would have to take that into account.

**Comment by tscholak** [comment]
Alright, I than gather that the following unit tests for `modifyBinding` would be appropriate, at a minimum:
```
modifyBinding "something" = "something"
modifyBinding "A.something" = "something"
modifyBinding "+" = "(+)" -- <<< somehow arguments are already stripped of parentheses, is that true?
modifyBinding "A.(+)" = "(+)" -- <<< or would the lhs be "A.+"?
modifyBinding "^." = "(^.)"
modifyBinding "A.(^.)" = "(^.)"
```

**Comment by tscholak** [comment]
@jhrcek I added an integration test as you suggested.
What would be a good way of testing the other usage of `modifyBinding`, i.e., processing unused exports?

**Comment by tscholak** [comment]
btw, here's how I run the tests:
```
$ nix develop
$ cabal test ghcide --test-show-details=direct --test-option=--pattern --test-option="remove import actions" 
```

**Comment by jhrcek** [comment]
First of all thank you for working on this!
I don't have much advice to offer, beyond what I already commented.
I only contribute once in a few months and don't know the codebase very well :)

I'd approach the fix as follows:
1. make wrapOperatorInParens tope level function
2. instead of modifyBinding, i'd only call wrapOperatorInParens in the rangesForBindingImport.
   because I think there's no way to actually have something qualified in the imports list:

```haskell
module A (Prelude.head) where
        --     ^... you can have qualified things in exports, so the unqualify makes sense here.

import B (Qualified.Think.here)
          --      ^... there can never be qualified thing like this, so no point in calling unqualify
```

3. keep the call to modifyBinding in the smallerRangesForBindingExport unless you have an example how that is currently broken

**Comment by tscholak** [comment]
I tried to write a test that triggers `modifyBinding` but so far to no avail.
What code would result in a pattern match with `L _ (IEThingWith _ _ _ _ _)`?
```
smallerRangesForBindingExport :: [LIE GhcPs] -> String -> [Range]
smallerRangesForBindingExport lies b =
    concatMap (mapMaybe srcSpanToRange . ranges') lies
  where
    b' = modifyBinding b
    ranges' (L _ (IEThingWith _ thing _  inners labels))
      | showSDocUnsafe (ppr thing) == b' = []
      | otherwise =
          [ l' | L l' x <- inners, showSDocUnsafe (ppr x) == b'] ++
          [ l' | L l' x <- labels, showSDocUnsafe (ppr x) == b']
    ranges' _ = []
```

**Comment by jhrcek** [comment]
Grepping GHC code base, I found this: https://gitlab.haskell.org/ghc/ghc/-/blob/master/testsuite/tests/parser/should_compile/T14189.hs

**Comment by tscholak** [comment]
Thanks! I also found the `IEThingWith` Note in https://hackage.haskell.org/package/ghc-8.10.2/docs/src/GHC.Hs.ImpExp.html#IE illuminating.

**Comment by tscholak** [comment]
Hm, I think we cannot have data constructors or classes ending in `.` without prepending them with the `type` keyword. But then we wouldn't have a `IEThingWith` anymore. Consider:
```hs
{-# LANGUAGE TypeOperators #-}
module B where
newtype (@.) = MkT {unT :: Int}
class (^.) a where
```
and
```hs
{-# LANGUAGE TypeOperators #-}
module A (type (B.@.) (MkT), type (B.^.)) where
import qualified B
a :: ()
a = ()
```

File: ghcide/test/exe/Main.hs [hunk 1]
```diff
@@ -1150,6 +1150,33 @@ removeImportTests = testGroup "remove import actions"
             , "type T = K.Type"
             ]
       liftIO $ expectedContentAfterAction @=? contentAfterAction
+  , testSession "remove unused operators whose name ends with '.'" $ do
+      let contentA = T.unlines
+            [ "module ModuleA where"
```
Comment (jhrcek) [inline ghcide/test/exe/Main.hs:1155]: Optional suggestion: I just realized there's (.|.) operator in Data.Bits in base, so we could potentially shrink the reproducer to just one module if you fancy minimalism :wink: 

```haskell
{-# OPTIONS_GHC -Wunused-imports #-}
module ModuleA where
import Data.Bits ((.|.), xor)
x=xor
```

**Comment by konn** [comment]
I tried this PR and confirmed that this also fixes #1705 (so it seems TH is irrelevant in #1705). Thank you for a great fix!

**Review by jneira — APPROVED** [review]
really a great work, three issues closed at once, solid tests after a thoroughfull investigation, congrats!
