### PR TITLE
fix lsp-types benchmark

### LINKED ISSUE #3102: CI bench-unit job failures
The upload of the .cabal folder to the CI cache fails with a 400. Example below: 

https://github.com/haskell/haskell-language-server/runs/7818378102?check_suite_focus=true

### PR DESCRIPTION
**Pull request by pepeiborra**
The lsp-types benchmark definition needs some fixes in ghc 9.2

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3079"></a>

Also fixes #3102 by tar'ing the benchmark artefacts before upload

### CODE REVIEW

File: ghcide/bench/lib/Experiments.hs [hunk 1]
```diff
@@ -563,6 +563,9 @@ setup = do
                 writeFile
                     (path </> "cabal.project.local")
                     ""
+                -- Fix newlines, required for GHC 9.2 and lsp-types
```
Comment (kokobd) [inline ghcide/bench/lib/Experiments.hs:566]: Why is this required? Does this mean HLS has some troubles when working on `lsp-types`?

**Review by kokobd — APPROVED** [review]

File: ghcide/bench/lib/Experiments.hs (hunk 1 above)
Comment (pepeiborra) [reply ghcide/bench/lib/Experiments.hs:566]: Honestly, I have no idea. The issue does not repro with ghc 8.10.7, which makes me think it's not an HLS bug. But it doesn't repro in `cabal repl` with ghc 9.2 either, so 🤷‍♂️🤷‍♂️🤷‍♂️

**Comment by michaelpj** [comment]
Maybe we should switch to a more stable package for benchmarking :laughing:

**Comment by pepeiborra** [comment]
> Maybe we should switch to a more stable package for benchmarking 😆

True, I chose `lsp-types` because it is guaranteed to be buildable by our CI, uses TH, and doesn't increase our dependency closure, but there are other options like `aeson` that also check those boxes
