### PR TITLE
Wingman: Fix TODO(sandy) when performing subsequent actions

### LINKED ISSUE #2448: Wingman: TODO(sandy) error pops up after the first tactic
### Your environment

Which OS do you use:
Ubuntu 20.04.3 LTS

Which lsp-client do you use:
VS Code

Describe your project (alternative: link to the project):
It is a regular `stack` project which can be found [here](https://github.com/lsmor/advent-of-code-2021). Nothing really wierd, just a normal advent of code project with one executable per day.

stack snapshot: 18.6 -> GHC 8.10.7
HLS version: 1.5.1

### Steps to reproduce

write the following file and positionate the cursor on the underscore, then trigger the code action "Wingman: case split on d"

```haskell
module Main where

data Input = Input

example :: Input -> Input
example d = _


main :: IO ()
main = print "hello hls"
```

### Expected behaviour
It should complete the line `example d  = _` introducing `Input` constructor like `example Input = _d`. Some times, It works fine when I re-start `hls` but 8 out of 10 times it keeps failing.

### Actual behaviour
And error pops up `TODO(sandy)`

### Include debug information
This is the output when I set VS code extension setting to debug. (I've been unable to run `haskell-language-server-wrapper`)

<details>
<summary>
Debug output:
</summary>

```
2021-12-07 12:01:51.274203053 [ThreadId 4442] INFO hls:	finish: Wingman.getIdeDynflags.GetModSummaryWithoutTimestamps (took 0.00s)
2021-12-07 12:01:51.274730682 [ThreadId 4443] INFO hls:	finish: Wingman.judgementForHole.GetHieAst (took 0.00s)
2021-12-07 12:01:51.275544442 [ThreadId 4444] INFO hls:	finish: Wingman.judgementForHole.GetBindings (took 0.00s)
2021-12-07 12:01:51.275816949 [ThreadId 4445] INFO hls:	finish: Wingman.judgementForHole.TypeCheck (took 0.00s)
[Error - 12:01:51] Request workspace/executeCommand failed.
  Message: TODO(sandy)
  Code: -32603 
2021-12-07 12:01:51.276098968 [ThreadId 4446] INFO hls:	finish: Wingman.judgementForHole.GhcSessionDeps (took 0.00s)
2021-12-07 12:01:51.350012789 [ThreadId 4464] INFO hls:	finish: Pragmas.GetParsedModule (took 0.00s)
2021-12-07 12:01:51.350191098 [ThreadId 4467] INFO hls:	finish: retrie (took 0.00s)
2021-12-07 12:01:51.350225369 [ThreadId 4465] INFO hls:	finish: Wingman.getIdeDynflags.GetModSummaryWithoutTimestamps (took 0.00s)
```
</details>

### PR DESCRIPTION
**Pull request by isovector**
This PR fixes #2448, by using `Uri` internally instead of `NormalizedFilePath`. It's not clear why it fixes it, since all the functions involved are pure, but who knows. Huge shoutouts to @pepeiborra for tracking down the issue in the first place.

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2580"></a>

### CODE REVIEW

File: plugins/hls-tactics-plugin/src/Wingman/AbstractLSP/Types.hs [hunk 1]
```diff
@@ -121,19 +121,13 @@ data Continuation sort target payload = Continuation
...
   { fc_uri      :: Uri
-  , fc_nfp      :: NormalizedFilePath
   , fc_range    :: Maybe (Tracked 'Current Range)
     -- ^ For code actions, this is 'Just'. For code lenses, you'll get
     -- a 'Nothing' in the request, and a 'Just' in the response.
   }
   deriving stock (Eq, Ord, Show, Generic)
   deriving anyclass (A.ToJSON, A.FromJSON)
 
-deriving anyclass instance A.ToJSON NormalizedFilePath
```
Comment (isovector) [inline plugins/hls-tactics-plugin/src/Wingman/AbstractLSP/Types.hs:132]: The problem is pretty obvious when you look at these :)

Comment (pepeiborra) [reply plugins/hls-tactics-plugin/src/Wingman/AbstractLSP/Types.hs:132]: Maybe there should be an `instance TypeError "Do not do this" => ToJSON NormalizedFilePath` definition in the `lsp` package where `NormalizedFilePath` is defined, to prevent this weird bug from happening again

**Review by pepeiborra — APPROVED** [review]

**Review by jneira — APPROVED** [review]
lgtm, thanks both for the fix

File: plugins/hls-tactics-plugin/src/Wingman/AbstractLSP/Types.hs (hunk 1 above)
Comment (pepeiborra) [reply plugins/hls-tactics-plugin/src/Wingman/AbstractLSP/Types.hs:132]: I don't remember anymore. Presumably the derived instances are not roundtripping, i.e. `fromJSON . receiveLSP . sendLSP . toJSON /= id`, because of the embedded hashes.
