### PR TITLE
Be much more intelligent about splitting matches

### LINKED ISSUE #1516: graftDecls stomps over too much
Wingman test `AutoThetaFix.hs` replaces an instance method:

```haskell
{-# LANGUAGE FlexibleContexts     #-}
{-# LANGUAGE UndecidableInstances #-}

data Fix f a = Fix (f (Fix f a))

instance ( Functor f
           -- FIXME(sandy): Unfortunately, the recursion tactic fails to fire
           -- on this case. By explicitly adding the @Functor (Fix f)@
           -- dictionary, we can get Wingman to generate the right definition.
         , Functor (Fix f)
         ) => Functor (Fix f) where
  fmap = _
```

but the result is:

```haskell
{-# LANGUAGE FlexibleContexts     #-}
{-# LANGUAGE UndecidableInstances #-}

data Fix f a = Fix (f (Fix f a))
instance (Functor f, Functor (Fix f)) => Functor (Fix f) where
  fmap fab (Fix fffa) = Fix (fmap (fmap fab) fffa)
```

Maybe what I really want here is a graftHsMatch, rather than the whole decl.

### LINKED ISSUE #1541: Wingman case split does the wrong thing on nested binds
@TOTBWF reports:

Found a case splitting bug

```haskell
proofs :: forall ext err s m goal. (MonadExtract ext m) => s -> ProofStateT ext ext err s m goal -> m [Either err (ext, s, [goal])]
proofs s p = go s [] pure p
    where
      go :: s -> [goal] -> (goal' -> ProofStateT ext ext err s m goal) -> ProofStateT ext ext err s m goal' -> m [Either err (ext, s, [goal])]
      go s goals cont p1  = _
```

splitting on `p1` causes this

```haskell
proofs :: forall ext err s m goal. (MonadExtract ext m) => s -> ProofStateT ext ext err s m goal -> m [Either err (ext, s, [goal])]
proofs s p = _
proofs s p = _
proofs s p = _
proofs s p = _
proofs s p = _
proofs s p = _
proofs s p = _
proofs s p = _
proofs s p = _
```

### LINKED ISSUE #1542: Wingman: case split on variable deletes existing function definition
### Your environment
```sh
haskell-language-server version: 1.0.0.0 (GHC: 8.8.4) (PATH: /home/jhrcek/.local/bin/haskell-language-server-wrapper) (GIT hash: 94573be3144fa47da0ebe547b62f0e172f48c40d)
Tool versions found on the $PATH
cabal:		3.4.0.0
stack:		2.5.1
ghc:		8.10.4
```
Which lsp-client do you use: vscode

### Steps to reproduce
```haskell
data A = A | B | C

some :: A -> IO ()
some a = do
    foo
    bar a
  where
      foo = putStrLn "Hi"
      
      bar :: A -> IO ()
      bar x = _ -- hover over this hole and pick "Case split on x"
```

### Expected behaviour
Case split should only affect the helper function bar and should not delete existing code.

### Actual behaviour
caseSplitBug

### PR DESCRIPTION
**Pull request by isovector**
Wingman used to implement case split by guessing where in the AST the match group was, and then annotating from there. But this had lots of problems --- it wouldn't work in `where` bindings, or `class` defaults. And I'd hand-coded support for `instance` methods, but due to a bug it would reformat the entire declaration.

This PR adds some new `syb` traversals that let us target very specific parts of the AST. For example, it's now possible to target "the smallest MatchGroup that contains a given source span," and then run a list-bind over its `Match`es. The machinery is reusable for other purposes, and makes the `Graft` system more composable. 

Fixes #1542
Fixes #1541
Fixes #1516

### CODE REVIEW

File: plugins/hls-tactics-plugin/test/golden/SplitPattern.hs.expected [hunk 1]
```diff
@@ -1,12 +1,11 @@
 data ADT = One | Two Int | Three | Four Bool ADT | Five
 
 case_split :: ADT -> Int
-case_split One = _
-case_split (Two i) = _
-case_split Three = _
-case_split (Four b One) = _
+case_split One        = _
+case_split (Two i)    = _
+case_split Three      = _case_split (Four b One) = _
```
Comment (isovector) [inline plugins/hls-tactics-plugin/test/golden/SplitPattern.hs.expected:6]: oh no

**Review by jneira — APPROVED** [review]
lgtm if it does for you

File: ghcide/src/Development/IDE/GHC/ExactPrint.hs [hunk 2]
```diff
@@ -504,3 +507,71 @@ render dflags = showSDoc dflags . ppr
...
+
+------------------------------------------------------------------------------
+-- | Apply the given 'GenericM' at every node that passes the 'GenericQ', but
+-- don't descend into children if the query matches.
+--
+-- Why is the query a @Maybe Bool@? The GHC AST intersperses 'Located' nodes
+-- with data nodes, so for any given node we can only definitely return an
+-- answer if it's a 'Located'. See 'genericIsSubspan' for how this parameter is
+-- used.
+largestM :: forall m. Monad m => GenericQ (Maybe Bool) -> GenericM m -> GenericM m
```
Comment (konn) [inline ghcide/src/Development/IDE/GHC/ExactPrint.hs:549]: The same here as above.

File: ghcide/src/Development/IDE/GHC/ExactPrint.hs [hunk 3]
```diff
@@ -504,3 +507,71 @@ render dflags = showSDoc dflags . ppr
...
+------------------------------------------------------------------------------
+-- | Apply the given 'GenericM' at all every node whose children fail the
+-- 'GenericQ', but which passes the query itself.
+--
+-- Why is the query a @Maybe Bool@? The GHC AST intersperses 'Located' nodes
+-- with data nodes, so for any given node we can only definitely return an
+-- answer if it's a 'Located'. See 'genericIsSubspan' for how this parameter is
+-- used.
+smallestM :: forall m. Monad m => GenericQ (Maybe Bool) -> GenericM m -> GenericM m
+smallestM q f = fmap snd . go
```
Comment (konn) [inline ghcide/src/Development/IDE/GHC/ExactPrint.hs:528]: Looks good!
It might be good to add some notes on *monotonicity* of the given predicate `q`; i.e. if `q x` holds for some subtree `x` of `z` and `z` has `Just`-value, then `q z` must hold.

File: ghcide/src/Development/IDE/GHC/ExactPrint.hs [hunk 4]
```diff
@@ -461,7 +462,7 @@ annotate dflags needs_space ast = do
     pure (anns', expr')
 
 -- | Given an 'LHsDecl', compute its exactprint annotations.
-annotateDecl :: DynFlags -> LHsDecl GhcPs -> TransformT (Either String) (Anns, LHsDecl GhcPs)
+annotateDecl :: DynFlags -> LHsDecl GhcPs -> TransformT (Either String) (LHsDecl GhcPs)
```
Comment (konn) [inline ghcide/src/Development/IDE/GHC/ExactPrint.hs:465]: This change eliminates much boilerplates. Great!

**Review by konn — COMMENTED** [review]
Thank you for refactorings in `graftWith*` families. I like them!

File: ghcide/src/Development/IDE/GHC/ExactPrint.hs (hunk 3 above)
Comment (isovector) [reply ghcide/src/Development/IDE/GHC/ExactPrint.hs:528]: Good idea

File: ghcide/src/Development/IDE/GHC/ExactPrint.hs [hunk 5]
```diff
@@ -504,3 +508,79 @@ render dflags = showSDoc dflags . ppr
...
+            Any False -> fmap (Any True,) $ f x'
+        Just False -> pure (mempty, x)
+
+------------------------------------------------------------------------------
+-- | Apply the given 'GenericM' at every node that passes the 'GenericQ', but
+-- don't descend into children if the query matches.
+--
+-- The query must be a monotonic function when it returns 'Just'. That is, if
+-- @s@ is a subtree of @t@, @q t@ should return @Just True@ if @q s@ does. It
+-- is the True-to-false edge of the query that triggers the transformation.
```
Comment (konn) [inline ghcide/src/Development/IDE/GHC/ExactPrint.hs:552]: In.`largest` case, returns immediately if the condition hold without edge comparison and monotonicity used in short-circuitting in `Just False` clause, right?

Comment (isovector) [reply ghcide/src/Development/IDE/GHC/ExactPrint.hs:552]: You're paying attention! Great catch, konn!

**Review by konn — APPROVED** [review]
LGTM 👍
