### PR TITLE
Progress reporting improvements

### LINKED ISSUE #1749: Progress messages logic might have race conditions
I'm not familiar with the current progress code, so the below is somewhat guesswork and assumption - happy to understand why I'm wrong. There seem to be two invariants around progress messages:

1. During testing we expect progress messages to be sent. If we don't, the benchmarking fails.
2. The LSP spec requires that no progress messages be sent between initialise request/response, as per https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#initialize

As far as I can tell, the way we ensure invariant 1 is by forking a progress thread and not doing a sleep at the beginning. Unfortunately, if you make the operations fast enough or lose a bunch of races, it doesn't get a progress notification, and we get failures. I'm seeing a failure with the ghcide benchmarking stuff I think comes from this.

As far as I can tell, the way we ensure invariant 2 is by hoping the initialise gets handled super quickly, and that the timer gets killed. Again, that's using sleeps and races to ensure the property.

I've changed a lot of timing properties around the Shake graph, and am suddenly getting a lot of errors from progress stuff. While these might be due to my changes, my debugging suggests progress itself might be at fault.

### PR DESCRIPTION
**Pull request by pepeiborra**
Rework of #1770. Summary of changes:

1. progress reporting logic extracted into its own module
2. Removed one layer of async handling, reducing the chances of race conditions
3. Correctly implement the LSP spec for `window/workDoneProgress/create` by waiting until the client has responded
4. Fix bugs: division by zero (when `todo` is 0) and handling when `NoProgress` 
5. Performance: the reporting loop is now O(1) instead of O(N) in the number of files

I think this is the best we can do to close #1749 while sharing the same logic for both tests and app code

### CODE REVIEW

File: hls-test-utils/src/Test/Hls.hs [hunk 1]
```diff
@@ -134,3 +137,15 @@ runSessionWithServer' plugin conf sconf caps root s = withLock lock $ keepCurren
...
       putStrLn $ "Finishing canceling (took " <> showDuration t <> "s)"
   pure x
+
+-- | Wait for all progress to be done
+-- Needs at least one progress done notification to return
+waitForProgressDone :: Session ()
+waitForProgressDone = loop
+  where
+    loop = do
+      ~() <- skipManyTill anyMessage $ satisfyMaybe $ \case
```
Comment (ndmitchell) [inline hls-test-utils/src/Test/Hls.hs:147]: What does `~()` mean? A lazy pattern match on `()`? How is that different from just ignoring the result?

File: hls-test-utils/src/Test/Hls.hs [hunk 2]
```diff
@@ -134,3 +137,15 @@ runSessionWithServer' plugin conf sconf caps root s = withLock lock $ keepCurren
       (t, _) <- duration $ cancel server
       putStrLn $ "Finishing canceling (took " <> showDuration t <> "s)"
   pure x
+
+-- | Wait for all progress to be done
+-- Needs at least one progress done notification to return
+waitForProgressDone :: Session ()
+waitForProgressDone = loop
+  where
+    loop = do
```
Comment (ndmitchell) [inline hls-test-utils/src/Test/Hls.hs:146]: `whileM` from extra can be used to do this - you just return True to keep going.

File: ghcide/src/Development/IDE/Core/ProgressReporting.hs [hunk 3]
```diff
@@ -0,0 +1,176 @@
...
+  :: Seconds  -- ^ Grace period before starting
+  -> Seconds  -- ^ sampling delay
+  -> Maybe (LSP.LanguageContextEnv c)
+  -> ProgressReportingStyle
+  -> IO ProgressReporting
+delayedProgressReporting before after lspEnv optProgressStyle = do
+    inProgressVar <- newVar $ InProgress 0 0 mempty
+    progressState <- newVar NotStarted
+    let progressUpdate event = modifyVar_ progressState $ updateState (mRunLspT lspEnv $ lspShakeProgress inProgressVar) (Event event)
+        progressStop   = modifyVar_ progressState $ updateState (mRunLspT lspEnv $ lspShakeProgress inProgressVar) StopProgress
```
Comment (ndmitchell) [inline ghcide/src/Development/IDE/Core/ProgressReporting.hs:100]: Worth defining something that abstracts over most of these lines? So:

````
let f = modifyVar_ progressState $ updateState (mRunLspT lspEnv $ lspShakeProgress inProgressVar)
```

File: ghcide/src/Development/IDE/Core/ProgressReporting.hs [hunk 4]
```diff
@@ -0,0 +1,176 @@
...
+                stop id = LSP.sendNotification LSP.SProgress
+                    LSP.ProgressParams
+                        { _token = id
+                        , _value = LSP.End WorkDoneProgressEndParams
+                          { _message = Nothing
+                          }
+                        }
+                loop id prev = do
+                    InProgress{..} <- liftIO $ readVar inProgress
+                    if todo == 0 then loop id 0 else do
```
Comment (ndmitchell) [inline ghcide/src/Development/IDE/Core/ProgressReporting.hs:137]: If we hit loop id 0, then we spin at 100% CPU. That path seems like it should still have a sleep on it.

File: ghcide/src/Development/IDE/Core/ProgressReporting.hs [hunk 5]
```diff
@@ -0,0 +1,176 @@
...
+                        let next = 100 * fromIntegral done / fromIntegral todo
+                        liftIO $ sleep after
+                        when (optProgressStyle /= NoProgress && next /= prev) $
```
Comment (ndmitchell) [inline ghcide/src/Development/IDE/Core/ProgressReporting.hs:140]: What's the point of running this loop at all if progress style is NoProgress?

File: ghcide/src/Development/IDE/Core/ProgressReporting.hs [hunk 6]
```diff
@@ -0,0 +1,176 @@
...
+        lspShakeProgress inProgress = do
+            -- first sleep a bit, so we only show progress messages if it's going to take
+            -- a "noticable amount of time" (we often expect a thread kill to arrive before the sleep finishes)
+            liftIO $ sleep before
+            u <- ProgressTextToken . T.pack . show . hashUnique <$> liftIO newUnique
+
+            b <- liftIO newBarrier
+            void $ LSP.sendRequest LSP.SWindowWorkDoneProgressCreate
+                LSP.WorkDoneProgressCreateParams { _token = u } $ liftIO . signalBarrier b
+            ready <- liftIO $ waitBarrier b
```
Comment (ndmitchell) [inline ghcide/src/Development/IDE/Core/ProgressReporting.hs:114]: If we send a WorkDoneProgressCreate, do we need to clean it up ever, or does it just expire on its own?

File: ghcide/src/Development/IDE/Core/Shake.hs [hunk 7]
```diff
@@ -487,23 +479,23 @@ shakeOpen lspEnv defaultConfig logger debouncer
...
         indexCompleted <- newTVarIO 0
         indexProgressToken <- newVar Nothing
         let hiedbWriter = HieDbWriter{..}
-        progressAsync <- async $
-            when reportProgress $
-                progressThread optProgressStyle mostRecentProgressEvent inProgress
         exportsMap <- newVar mempty
 
+        progress <- do
+            let (before, after) = if testing then (0,0.1) else (0.1,0.1)
```
Comment (ndmitchell) [inline ghcide/src/Development/IDE/Core/Shake.hs:490]: At a delay of 0, we've definitely reduced the window of the race condition, but it's not gone entirely.

File: ghcide/src/Development/IDE/Core/ProgressReporting.hs [hunk 8]
```diff
@@ -0,0 +1,176 @@
...
+noProgressReporting = return $ ProgressReporting
+  { progressUpdate = const $ pure ()
+  , inProgress = const id
+  , progressStop   = pure ()
+  }
+
+-- | State used in 'delayedProgressReporting'
+data State
+    = NotStarted
+    | Completed
```
Comment (ndmitchell) [inline ghcide/src/Development/IDE/Core/ProgressReporting.hs:54]: I can't find a case where NotStarted and Completed don't have the same behaviour. Could we collapse them?

**Review by ndmitchell — APPROVED** [review]
I see a few updates to the test - are these fixing race conditions that this patch showed up?

This code is way clearer!

File: hls-test-utils/src/Test/Hls.hs (hunk 1 above)
Comment (pepeiborra) [reply hls-test-utils/src/Test/Hls.hs:147]: I have no idea - it's part of the code that was already there. I can't think of any other meaning

File: ghcide/src/Development/IDE/Core/ProgressReporting.hs (hunk 8 above)
Comment (pepeiborra) [reply ghcide/src/Development/IDE/Core/ProgressReporting.hs:54]: Good tip, thanks

File: ghcide/src/Development/IDE/Core/Shake.hs (hunk 7 above)
Comment (pepeiborra) [reply ghcide/src/Development/IDE/Core/Shake.hs:490]: Agreed - but it's the best I can think of without introducing a separate code path for tests

File: ghcide/src/Development/IDE/Core/ProgressReporting.hs (hunk 6 above)
Comment (pepeiborra) [reply ghcide/src/Development/IDE/Core/ProgressReporting.hs:114]: As far as  I know it doesn't require any clean up

File: ghcide/src/Development/IDE/Core/ProgressReporting.hs (hunk 5 above)
Comment (pepeiborra) [reply ghcide/src/Development/IDE/Core/ProgressReporting.hs:140]: Good point

File: ghcide/src/Development/IDE/Core/ProgressReporting.hs (hunk 4 above)
Comment (pepeiborra) [reply ghcide/src/Development/IDE/Core/ProgressReporting.hs:137]: Good catch!

File: hls-test-utils/src/Test/Hls.hs (hunk 2 above)
Comment (pepeiborra) [reply hls-test-utils/src/Test/Hls.hs:146]: The codebase consistenly uses recursive functions for looping this way, so switching to `whileM` would be inconsistent.

Comment (ndmitchell) [reply hls-test-utils/src/Test/Hls.hs:146]: Fair enough

File: hls-test-utils/src/Test/Hls.hs (hunk 1 above)
Comment (ndmitchell) [reply hls-test-utils/src/Test/Hls.hs:147]: Maybe it enforces the type in a way that used to be ambiguous? I'd be OK with `_ <-` or `() <-`.

File: ghcide/src/Development/IDE/Core/Shake.hs (hunk 7 above)
Comment (ndmitchell) [reply ghcide/src/Development/IDE/Core/Shake.hs:490]: That seems pretty reasonable. Could we leave a comment in the code here that for testing we'd like to guarantee always sending messages, but instead we do a sleep of 0 and a dose of hope?

**Comment by pepeiborra** [comment]
> I see a few updates to the test - are these fixing race conditions that this patch showed up?

I fixed a bunch of tests in the previous version of this PR and decided to preserve the fixes. Not necessarily race conditions: often tests rely on sketchy invariants, e.g. a test that waits for *three* logging notifications before checking if the build session is restarted is going to break for reasons unrelated to the property it's checking.
