### PR TITLE
Fix multiline eval plugin padding

### LINKED ISSUE #2907: Evaluate lens only comments the first line of multiline output
### Steps to reproduce

Code:
```hs
module Lib where

data MultiLine = MultiLine

instance Show MultiLine where
    show MultiLine = "Multi\nLine"

-- >>> MultiLine
```
Click `Evaluate...`:

multiline1

### Expected behaviour

multiline3

### Actual behaviour

multiline2

### Versions

GHC: 9.2.2, 9.0.2, 8.10.7
HLS: 1.7.0.0

### PR DESCRIPTION
**Pull request by xsebek**
- fix multiline eval padding (`concatMap lines`)
- add test for multiline show instance

---

- closes #2907

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2910"></a>

### CODE REVIEW

File: plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs [hunk 1]
```diff
@@ -358,8 +358,9 @@ runTests EvalConfig{..} e@(_st, _) tests = do
         dbg "TEST RESULTS" rs
 
         let checkedResult = testCheck eval_cfg_diff (section, test) rs
+        let resultLines = concatMap T.lines checkedResult
```
Comment (xsebek) [inline plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs:361]: Honestly, I am unsure why we get `[Text]` that does not have the `show` result split into lines.

We might want to consider splitting in the `evals` function. :man_shrugging:

File: plugins/hls-eval-plugin/test/testdata/TMultiResult.expected.hs [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+data Multiline = M {l1 :: String, l2 :: String} deriving Read
+
+instance Show Multiline where
+  show m = "M {\n  l1=" <> show (l1 m) <> ",\n  l2=" <> show (l2 m) <> "\n}"
+
+-- >>> M "first line" "second line"
+-- M {
+--   l1="first line",
+--   l2="second line"
+-- }
```
Comment (xsebek) [inline plugins/hls-eval-plugin/test/testdata/TMultiResult.expected.hs:13]: This only tests `--` comments, but I figured `{- -}` would be fine and covered by the other multiline tests.

**Comment by pepeiborra** [comment]
> @pepeiborra Could you please take a look? 🙂

I'm not the owner of the Eval plugin, even though I was the original contributor. @tittoassini rewrote it and I have not been keeping up. If no one else can review your PR, it will have to wait until I have spare time (probably the weekend).

**Comment by xsebek** [comment]
Thanks, @pepeiborra, I am aware but I don't know about anyone else familiar with the plugin except maybe @Ailrun?

Either way, I am in no hurry to merge this :slightly_smiling_face:

**Review by Ailrun — APPROVED** [review]
> I am aware but I don't know about anyone else familiar with the plugin except maybe @Ailrun?

You can tag me, though I'm sometimes not super reactive.

Anyway, looks good to me.
