### PR TITLE
Use hie-bios 0.16

### LINKED ISSUE #3730: HLS breaks cabals tool detection
Reproduce:

1. `cabal unpack filepath`
2. `cd filepath-*/`
3. `echo -e 'packages: .\nwith-compiler: ghc-9.4.5\ndocumentation: True' > cabal.project`
4. `ghcup install ghc 9.4.5`
5. `ghcup run -i --ghc 8.10.7 --hls latest -- haskell-language-server-wrapper typecheck`

Error:

```
  Installing unordered-containers-0.2.19.1 (lib)
  Completed unordered-containers-0.2.19.1 (lib)

  Error: cabal-3.10.1.0: Haddock's internal GHC version must match the
  configured GHC version.
  The GHC version is 9.4.5 but haddock is using GHC version 8.10.7

  Warning: Failed to build documentation for filepath-1.4.100.3 (which is
  required by test:abstract-filepath from filepath-1.4.100.3).


  Process Environment:
  HIE_BIOS_GHC: /home/hasufell/.ghcup/ghc/9.4.5/lib/ghc-9.4.5/bin/ghc-9.4.5
  HIE_BIOS_GHC_ARGS: -B/home/hasufell/.ghcup/ghc/9.4.5/lib/ghc-9.4.5/lib
```

We invoke cabal via:

```
cabal
  --builddir=/home/hasufell/.cache/hie-bios/dist-filepath-1.4.100-0ff2db8e132055d383407b5377ae4045
  v2-repl --with-compiler /home/hasufell/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36
  --with-hc-pkg /home/hasufell/.cache/hie-bios/ghc-pkg-af203fda954acac33325522618af549f
```

Following that, I believe this part of the cabal code fails to find qualified tool binaries (see `takeVersionSuffix`): https://github.com/haskell/cabal/blob/4aa5f88618a29cb53b988a8ae859caa2c70a6e62/Cabal/src/Distribution/Simple/GHC.hs#L278-L340

It's not clear whether to consider this a cabal issue or a HLS issue. It might work if we name the wrapper script `wrapper-b54f81dea4c0e6d1626911c526bc4e36_-9.4.5` or so.

----

First reported by @merijn in haskell IRC.

### LINKED ISSUE #4590: "Failed to parse result of calling cabal" on HLS 2.10.0.0 & cabal-install 3.15.0.0
### Your environment

Which OS do you use? Fedora 42
Which version of GHC do you use and how did you install it? 9.10.1
How is your project built (alternative: link to the project)? `cabal-install version 3.15.0.0 (commit 2b0ccee, Sat May 10 23:35:27 2025 +0000)`

Which LSP client (editor/plugin) do you use?

Which version of HLS do you use and how did you install it? `haskell-language-server version: 2.10.0.0 (GHC: 9.10.1) (PATH: /home/tchoutri/.ghcup/hls/2.10.0.0/lib/haskell-language-server-2.10.0.0/bin/haskell-language-server-wrapper)` from GHCup
Have you configured HLS in any way (especially: a `hie.yaml` file)? No

---

While working on a new cabal project, HLS is unhappy with what `cabal-install` reports, even though the files compile well. Happy to try the invocation with other flags if it can provide more details.

<details><summary>Debug logs</summary>
<p>

```
No 'hie.yaml' found. Try to discover the project type!
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper) Version 2.10.0.0 x86_64 ghc-9.10.1
Current directory: /home/tchoutri/Projects/kitty-keyboard-protocol
Operating system: linux
Arguments: ["-d"]
Cradle directory: /home/tchoutri/Projects/kitty-keyboard-protocol
Cradle type: Cabal

Tool versions found on the $PATH
cabal:          3.15.0.0
stack:          3.1.1
ghc:            9.6.7


Consulting the cradle to get project GHC version...
2025-05-12T10:31:16.293475Z | Debug | cabal exec -v0 -- ghc --print-libdir
2025-05-12T10:31:16.418990Z | Debug | cabal exec -v0 -- ghc -package-env=- -ignore-dot-ghci -e Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)
2025-05-12T10:31:16.473949Z | Debug | cabal --builddir=/home/tchoutri/.cache/hie-bios/dist-kitty-keyboard-protocol-1388541a692403313ef229670782cab8 v2-exec --with-compiler /home/tchoutri/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /home/tchoutri/.cache/hie-bios/ghc-pkg-8fae37528692e63199f77bd1a20e5f72 ghc -v0 -- --numeric-version
  Environment Variables
    HIE_BIOS_GHC: /home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/bin/ghc-9.10.1
    HIE_BIOS_GHC_ARGS: -B/home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib
Project GHC version: 9.10.1
haskell-language-server exe candidates: ["haskell-language-server-9.10.1","haskell-language-server"]
Launching haskell-language-server exe at:/home/tchoutri/.ghcup/bin/haskell-language-server-9.10.1
2025-05-12T10:31:16.531680Z | Debug | cabal exec -v0 -- ghc --print-libdir
2025-05-12T10:31:16.646668Z | Debug | cabal exec -v0 -- ghc -package-env=- -ignore-dot-ghci -e Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)
2025-05-12T10:31:16.772561Z | Debug | cabal --builddir=/home/tchoutri/.cache/hie-bios/dist-kitty-keyboard-protocol-1388541a692403313ef229670782cab8 v2-exec --with-compiler /home/tchoutri/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /home/tchoutri/.cache/hie-bios/ghc-pkg-8fae37528692e63199f77bd1a20e5f72 ghc -v0 -- -v0 -package-env=- -ignore-dot-ghci -e Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)
  Environment Variables
    HIE_BIOS_GHC: /home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/bin/ghc-9.10.1
    HIE_BIOS_GHC_ARGS: -B/home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib
2025-05-12T10:31:16.830419Z | Debug | cabal exec -v0 -- ghc --print-libdir
2025-05-12T10:31:16.946130Z | Debug | cabal exec -v0 -- ghc -package-env=- -ignore-dot-ghci -e Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)
2025-05-12T10:31:17.012367Z | Debug | cabal --builddir=/home/tchoutri/.cache/hie-bios/dist-kitty-keyboard-protocol-1388541a692403313ef229670782cab8 v2-exec --with-compiler /home/tchoutri/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /home/tchoutri/.cache/hie-bios/ghc-pkg-8fae37528692e63199f77bd1a20e5f72 ghc -v0 -- --print-libdir
  Environment Variables
    HIE_BIOS_GHC: /home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/bin/ghc-9.10.1
    HIE_BIOS_GHC_ARGS: -B/home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib
2025-05-12T10:31:18.145988Z | Info | haskell-language-server version: 2.10.0.0 (GHC: 9.10.1) (PATH: /home/tchoutri/.ghcup/hls/2.10.0.0/lib/haskell-language-server-2.10.0.0/bin/haskell-language-server-9.10.1)
2025-05-12T10:31:18.147082Z | Info | Directory: /home/tchoutri/Projects/kitty-keyboard-protocol
2025-05-12T10:31:18.147337Z | Info | Logging heap statistics every 60.00s
 ghcide setup tester in /home/tchoutri/Projects/kitty-keyboard-protocol.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/4: Finding files to test in /home/tchoutri/Projects/kitty-keyboard-protocol
Found 3 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle
  ()

Step 3/4: Initializing the IDE
2025-05-12T10:31:18.152661Z | Debug | Initializing exports map from hiedb
2025-05-12T10:31:18.153152Z | Debug | Shake session initialized

Step2025-05-12T10:31:18.153320Z | Debug | Done initializing exports map from hiedb. Size: 0
 4/4: Type checking the files
2025-05-12T10:31:18.155239Z | Info | Cradle path: test/Main.hs
2025-05-12T10:31:18.155326Z | Warning | No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for test/Main.hs.
Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie).
You should ignore this message, unless you see a 'Multi Cradle: No prefixes matched' error.
2025-05-12T10:31:18.155715Z | Debug | Cradle: Cradle{ cradleRootDir = "/home/tchoutri/Projects/kitty-keyboard-protocol", cradleOptsProg = CradleAction: Cabal}
2025-05-12T10:31:18.155769Z | Info | invoking build tool to determine build flags (this may take some time depending on the cache)
2025-05-12T10:31:18.155815Z | Debug | Requested to load Cabal cradle using single file mode
2025-05-12T10:31:18.174916Z | Debug | cabal --numeric-version
2025-05-12T10:31:18.233916Z | Debug | cabal exec -v0 -- ghc --print-libdir
2025-05-12T10:31:18.364771Z | Debug | cabal exec -v0 -- ghc -package-env=- -ignore-dot-ghci -e Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)
2025-05-12T10:31:18.424491Z | Debug | cabal --builddir=/home/tchoutri/.cache/hie-bios/dist-kitty-keyboard-protocol-1388541a692403313ef229670782cab8 v2-exec --with-compiler /home/tchoutri/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /home/tchoutri/.cache/hie-bios/ghc-pkg-8fae37528692e63199f77bd1a20e5f72 ghc -v0 -- --numeric-version
  Environment Variables
    HIE_BIOS_GHC: /home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/bin/ghc-9.10.1
    HIE_BIOS_GHC_ARGS: -B/home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib
2025-05-12T10:31:18.424768Z | Info | Load cabal cradle using single file
2025-05-12T10:31:18.485433Z | Debug | cabal exec -v0 -- ghc --print-libdir
2025-05-12T10:31:18.606522Z | Debug | cabal exec -v0 -- ghc -package-env=- -ignore-dot-ghci -e Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)
2025-05-12T10:31:18.607818Z | Info | cabal --builddir=/home/tchoutri/.cache/hie-bios/dist-kitty-keyboard-protocol-1388541a692403313ef229670782cab8 v2-repl --with-compiler /home/tchoutri/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /home/tchoutri/.cache/hie-bios/ghc-pkg-8fae37528692e63199f77bd1a20e5f72 /home/tchoutri/Projects/kitty-keyboard-protocol/test/Main.hs
  Environment Variables
    HIE_BIOS_OUTPUT: /tmp/HIE_BIOS_OUTPUT129052-0
    HIE_BIOS_GHC: /home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/bin/ghc-9.10.1
    HIE_BIOS_GHC_ARGS: -B/home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib
2025-05-12T10:31:18.616805Z | Debug | Warning: this is a debug build of cabal-install with assertions enabled.
2025-05-12T10:31:18.622698Z | Debug | Configuration is affected by the following files:
2025-05-12T10:31:18.622845Z | Debug | - cabal.project
2025-05-12T10:31:18.622911Z | Debug | - cabal.project.freeze
2025-05-12T10:31:18.622966Z | Debug | - cabal.project.local
2025-05-12T10:31:18.637751Z | Debug | Build profile: -w ghc-9.10.1 -O1
2025-05-12T10:31:18.637928Z | Debug | In order, the following will be built (use -v for more details):
2025-05-12T10:31:18.638176Z | Debug |  - kitty-keyboard-protocol-0.1.0.0 (interactive) (test:kitty-keyboard-protocol-test) (first run)
2025-05-12T10:31:18.640611Z | Debug | Warning: this is a debug build of cabal-install with assertions enabled.
2025-05-12T10:31:18.670146Z | Debug | Preprocessing test suite 'kitty-keyboard-protocol-test' for kitty-keyboard-protocol-0.1.0.0...
2025-05-12T10:31:18.699848Z | Debug | when making flags consistent: warning: [GHC-74335] [-Winconsistent-flags]
2025-05-12T10:31:18.699979Z | Debug |     Ignoring optimization flags since they are experimental for the byte-code interpreter. Pass -fno-unoptimized-core-for-interpreter to enable this feature.
2025-05-12T10:31:18.700098Z | Debug | 
2025-05-12T10:31:18.700174Z | Debug | GHCi, version 9.10.1: https://www.haskell.org/ghc/  :? for help
2025-05-12T10:31:18.851800Z | Debug | Loaded GHCi configuration from /home/tchoutri/Dotfiles/ghci/ghci
2025-05-12T10:31:18.856856Z | Debug | [1 of 2] Compiling Main
2025-05-12T10:31:18.860321Z | Debug | Ok, one module loaded.
2025-05-12T10:31:18.860854Z | Debug | ghci> Leaving GHCi.
2025-05-12T10:31:18.897947Z | Debug | Session loading result: Left [CradleError {cradleErrorDependencies = ["kitty-keyboard-protocol.cabal","cabal.project","cabal.project.local"], cradleErrorExitCode = ExitSuccess, cradleErrorStderr = ["Failed to parse result of calling cabal","Failed command: cabal --builddir=/home/tchoutri/.cache/hie-bios/dist-kitty-keyboard-protocol-1388541a692403313ef229670782cab8 v2-repl --with-compiler /home/tchoutri/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /home/tchoutri/.cache/hie-bios/ghc-pkg-8fae37528692e63199f77bd1a20e5f72 /home/tchoutri/Projects/kitty-keyboard-protocol/test/Main.hs","Build profile: -w ghc-9.10.1 -O1\nIn order, the following will be built (use -v for more details):\n - kitty-keyboard-protocol-0.1.0.0 (interactive) (test:kitty-keyboard-protocol-test) (first run)\nPreprocessing test suite 'kitty-keyboard-protocol-test' for kitty-keyboard-protocol-0.1.0.0...\nGHCi, version 9.10.1: https://www.haskell.org/ghc/  :? for help\nLoaded GHCi configuration from /home/tchoutri/Dotfiles/ghci/ghci\n[1 of 2] Compiling Main\nOk, one module loaded.\nghci> Leaving GHCi.\n","Warning: this is a debug build of cabal-install with assertions enabled.\nConfiguration is affected by the following files:\n- cabal.project\n- cabal.project.freeze\n- cabal.project.local\nWarning: this is a debug build of cabal-install with assertions enabled.\nwhen making flags consistent: warning: [GHC-74335] [-Winconsistent-flags]\n    Ignoring optimization flags since they are experimental for the byte-code interpreter. Pass -fno-unoptimized-core-for-interpreter to enable this feature.\n\n","","Process Environment:","HIE_BIOS_GHC: /home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/bin/ghc-9.10.1","HIE_BIOS_GHC_ARGS: -B/home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib"]}]
2025-05-12T10:31:18.898652Z | Info | Cradle path: src/Kitty/KeyboardProtocol/Keys.hs
2025-05-12T10:31:18.898737Z | Warning | No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for src/Kitty/KeyboardProtocol/Keys.hs.
Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie).
You should ignore this message, unless you see a 'Multi Cradle: No prefixes matched' error.
2025-05-12T10:31:18.899068Z | Debug | Cradle: Cradle{ cradleRootDir = "/home/tchoutri/Projects/kitty-keyboard-protocol", cradleOptsProg = CradleAction: Cabal}
2025-05-12T10:31:18.899107Z | Info | invoking build tool to determine build flags (this may take some time depending on the cache)
2025-05-12T10:31:18.899143Z | Debug | Requested to load Cabal cradle using single file mode
2025-05-12T10:31:18.905362Z | Info | updateFileDiagnostics published different from new diagnostics - file diagnostics: File:     /home/tchoutri/Projects/kitty-keyboard-protocol/test/Main.hs
Hidden:   no
Range:    1:1-2:1
Source:   cradle
Severity: DiagnosticSeverity_Error
Code:     <none>
Message: 
  Failed to parse result of calling cabal
  Failed command: cabal
  --builddir=/home/tchoutri/.cache/hie-bios/dist-kitty-keyboard-protocol-1388541a692403313ef229670782cab8
  v2-repl --with-compiler /home/tchoutri/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36
  --with-hc-pkg /home/tchoutri/.cache/hie-bios/ghc-pkg-8fae37528692e63199f77bd1a20e5f72
  /home/tchoutri/Projects/kitty-keyboard-protocol/test/Main.hs
  Build profile: -w ghc-9.10.1 -O1
  In order, the following will be built (use -v for more details):
  - kitty-keyboard-protocol-0.1.0.0 (interactive) (test:kitty-keyboard-protocol-test) (first run)
  Preprocessing test suite 'kitty-keyboard-protocol-test' for kitty-keyboard-protocol-0.1.0.0...
  GHCi, version 9.10.1: https://www.haskell.org/ghc/ :? for help
  Loaded GHCi configuration from /home/tchoutri/Dotfiles/ghci/ghci
  [1 of 2] Compiling Main
  Ok, one module loaded.
  ghci> Leaving GHCi.

  Warning: this is a debug build of cabal-install with assertions enabled.
  Configuration is affected by the following files:
  - cabal.project
  - cabal.project.freeze
  - cabal.project.local
  Warning: this is a debug build of cabal-install with assertions enabled.
  when making flags consistent: warning: [GHC-74335] [-Winconsistent-flags]
  Ignoring optimization flags since they are experimental for the byte-code interpreter. Pass
  -fno-unoptimized-core-for-interpreter to enable this feature.



  Process Environment:
  HIE_BIOS_GHC: /home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/bin/ghc-9.10.1
  HIE_BIOS_GHC_ARGS: -B/home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib
2025-05-12T10:31:18.915745Z | Debug | cabal --numeric-version
2025-05-12T10:31:18.974590Z | Debug | cabal exec -v0 -- ghc --print-libdir
2025-05-12T10:31:19.094958Z | Debug | cabal exec -v0 -- ghc -package-env=- -ignore-dot-ghci -e Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)
2025-05-12T10:31:19.153518Z | Debug | cabal --builddir=/home/tchoutri/.cache/hie-bios/dist-kitty-keyboard-protocol-1388541a692403313ef229670782cab8 v2-exec --with-compiler /home/tchoutri/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /home/tchoutri/.cache/hie-bios/ghc-pkg-8fae37528692e63199f77bd1a20e5f72 ghc -v0 -- --numeric-version
  Environment Variables
    HIE_BIOS_GHC: /home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/bin/ghc-9.10.1
    HIE_BIOS_GHC_ARGS: -B/home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib
2025-05-12T10:31:19.153821Z | Info | Load cabal cradle using single file
2025-05-12T10:31:19.215286Z | Debug | cabal exec -v0 -- ghc --print-libdir
2025-05-12T10:31:19.336392Z | Debug | cabal exec -v0 -- ghc -package-env=- -ignore-dot-ghci -e Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)
2025-05-12T10:31:19.337684Z | Info | cabal --builddir=/home/tchoutri/.cache/hie-bios/dist-kitty-keyboard-protocol-1388541a692403313ef229670782cab8 v2-repl --with-compiler /home/tchoutri/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /home/tchoutri/.cache/hie-bios/ghc-pkg-8fae37528692e63199f77bd1a20e5f72 /home/tchoutri/Projects/kitty-keyboard-protocol/src/Kitty/KeyboardProtocol/Keys.hs
  Environment Variables
    HIE_BIOS_OUTPUT: /tmp/HIE_BIOS_OUTPUT129052-1
    HIE_BIOS_GHC: /home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/bin/ghc-9.10.1
    HIE_BIOS_GHC_ARGS: -B/home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib
2025-05-12T10:31:19.348458Z | Debug | Warning: this is a debug build of cabal-install with assertions enabled.
2025-05-12T10:31:19.353593Z | Debug | Configuration is affected by the following files:
2025-05-12T10:31:19.353672Z | Debug | - cabal.project
2025-05-12T10:31:19.353729Z | Debug | - cabal.project.freeze
2025-05-12T10:31:19.353774Z | Debug | - cabal.project.local
2025-05-12T10:31:19.365908Z | Debug | Build profile: -w ghc-9.10.1 -O1
2025-05-12T10:31:19.366024Z | Debug | In order, the following will be built (use -v for more details):
2025-05-12T10:31:19.366100Z | Debug |  - kitty-keyboard-protocol-0.1.0.0 (interactive) (lib) (configuration changed)
2025-05-12T10:31:19.370048Z | Debug | Warning: this is a debug build of cabal-install with assertions enabled.
2025-05-12T10:31:19.373345Z | Debug | Configuring library for kitty-keyboard-protocol-0.1.0.0...
2025-05-12T10:31:21.132551Z | Debug | Warning: this is a debug build of cabal-install with assertions enabled.
2025-05-12T10:31:21.158919Z | Debug | Preprocessing library for kitty-keyboard-protocol-0.1.0.0...
2025-05-12T10:31:21.188244Z | Debug | when making flags consistent: warning: [GHC-74335] [-Winconsistent-flags]
2025-05-12T10:31:21.188392Z | Debug |     Ignoring optimization flags since they are experimental for the byte-code interpreter. Pass -fno-unoptimized-core-for-interpreter to enable this feature.
2025-05-12T10:31:21.188455Z | Debug | 
2025-05-12T10:31:21.188526Z | Debug | GHCi, version 9.10.1: https://www.haskell.org/ghc/  :? for help
2025-05-12T10:31:21.335562Z | Debug | Loaded GHCi configuration from /home/tchoutri/Dotfiles/ghci/ghci
2025-05-12T10:31:21.342756Z | Debug | [1 of 2] Compiling Kitty.KeyboardProtocol.Keys
2025-05-12T10:31:21.366823Z | Debug | [2 of 2] Compiling Kitty.KeyboardProtocol.State
2025-05-12T10:31:21.367689Z | Debug | Ok, two modules loaded.
2025-05-12T10:31:21.368036Z | Debug | ghci> Leaving GHCi.
2025-05-12T10:31:21.399964Z | Debug | Session loading result: Left [CradleError {cradleErrorDependencies = ["kitty-keyboard-protocol.cabal","cabal.project","cabal.project.local"], cradleErrorExitCode = ExitSuccess, cradleErrorStderr = ["Failed to parse result of calling cabal","Failed command: cabal --builddir=/home/tchoutri/.cache/hie-bios/dist-kitty-keyboard-protocol-1388541a692403313ef229670782cab8 v2-repl --with-compiler /home/tchoutri/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /home/tchoutri/.cache/hie-bios/ghc-pkg-8fae37528692e63199f77bd1a20e5f72 /home/tchoutri/Projects/kitty-keyboard-protocol/src/Kitty/KeyboardProtocol/Keys.hs","Build profile: -w ghc-9.10.1 -O1\nIn order, the following will be built (use -v for more details):\n - kitty-keyboard-protocol-0.1.0.0 (interactive) (lib) (configuration changed)\nConfiguring library for kitty-keyboard-protocol-0.1.0.0...\nPreprocessing library for kitty-keyboard-protocol-0.1.0.0...\nGHCi, version 9.10.1: https://www.haskell.org/ghc/  :? for help\nLoaded GHCi configuration from /home/tchoutri/Dotfiles/ghci/ghci\n[1 of 2] Compiling Kitty.KeyboardProtocol.Keys\n[2 of 2] Compiling Kitty.KeyboardProtocol.State\nOk, two modules loaded.\nghci> Leaving GHCi.\n","Warning: this is a debug build of cabal-install with assertions enabled.\nConfiguration is affected by the following files:\n- cabal.project\n- cabal.project.freeze\n- cabal.project.local\nWarning: this is a debug build of cabal-install with assertions enabled.\nWarning: this is a debug build of cabal-install with assertions enabled.\nwhen making flags consistent: warning: [GHC-74335] [-Winconsistent-flags]\n    Ignoring optimization flags since they are experimental for the byte-code interpreter. Pass -fno-unoptimized-core-for-interpreter to enable this feature.\n\n","","Process Environment:","HIE_BIOS_GHC: /home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/bin/ghc-9.10.1","HIE_BIOS_GHC_ARGS: -B/home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib"]}]
2025-05-12T10:31:21.401347Z | Info | Cradle path: src/Kitty/KeyboardProtocol/State.hs
2025-05-12T10:31:21.401426Z | Warning | No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for src/Kitty/KeyboardProtocol/State.hs.
Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie).
You should ignore this message, unless you see a 'Multi Cradle: No prefixes matched' error.
2025-05-12T10:31:21.401719Z | Debug | Cradle: Cradle{ cradleRootDir = "/home/tchoutri/Projects/kitty-keyboard-protocol", cradleOptsProg = CradleAction: Cabal}
2025-05-12T10:31:21.401758Z | Info | invoking build tool to determine build flags (this may take some time depending on the cache)
2025-05-12T10:31:21.401793Z | Debug | Requested to load Cabal cradle using single file mode
2025-05-12T10:31:21.408646Z | Info | updateFileDiagnostics published different from new diagnostics - file diagnostics: File:     /home/tchoutri/Projects/kitty-keyboard-protocol/src/Kitty/KeyboardProtocol/Keys.hs
Hidden:   no
Range:    1:1-2:1
Source:   cradle
Severity: DiagnosticSeverity_Error
Code:     <none>
Message: 
  Failed to parse result of calling cabal
  Failed command: cabal
  --builddir=/home/tchoutri/.cache/hie-bios/dist-kitty-keyboard-protocol-1388541a692403313ef229670782cab8
  v2-repl --with-compiler /home/tchoutri/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36
  --with-hc-pkg /home/tchoutri/.cache/hie-bios/ghc-pkg-8fae37528692e63199f77bd1a20e5f72
  /home/tchoutri/Projects/kitty-keyboard-protocol/src/Kitty/KeyboardProtocol/Keys.hs
  Build profile: -w ghc-9.10.1 -O1
  In order, the following will be built (use -v for more details):
  - kitty-keyboard-protocol-0.1.0.0 (interactive) (lib) (configuration changed)
  Configuring library for kitty-keyboard-protocol-0.1.0.0...
  Preprocessing library for kitty-keyboard-protocol-0.1.0.0...
  GHCi, version 9.10.1: https://www.haskell.org/ghc/ :? for help
  Loaded GHCi configuration from /home/tchoutri/Dotfiles/ghci/ghci
  [1 of 2] Compiling Kitty.KeyboardProtocol.Keys
  [2 of 2] Compiling Kitty.KeyboardProtocol.State
  Ok, two modules loaded.
  ghci> Leaving GHCi.

  Warning: this is a debug build of cabal-install with assertions enabled.
  Configuration is affected by the following files:
  - cabal.project
  - cabal.project.freeze
  - cabal.project.local
  Warning: this is a debug build of cabal-install with assertions enabled.
  Warning: this is a debug build of cabal-install with assertions enabled.
  when making flags consistent: warning: [GHC-74335] [-Winconsistent-flags]
  Ignoring optimization flags since they are experimental for the byte-code interpreter. Pass
  -fno-unoptimized-core-for-interpreter to enable this feature.



  Process Environment:
  HIE_BIOS_GHC: /home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/bin/ghc-9.10.1
  HIE_BIOS_GHC_ARGS: -B/home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib
2025-05-12T10:31:21.419759Z | Debug | cabal --numeric-version
2025-05-12T10:31:21.478817Z | Debug | cabal exec -v0 -- ghc --print-libdir
2025-05-12T10:31:21.600460Z | Debug | cabal exec -v0 -- ghc -package-env=- -ignore-dot-ghci -e Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)
2025-05-12T10:31:21.661718Z | Debug | cabal --builddir=/home/tchoutri/.cache/hie-bios/dist-kitty-keyboard-protocol-1388541a692403313ef229670782cab8 v2-exec --with-compiler /home/tchoutri/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /home/tchoutri/.cache/hie-bios/ghc-pkg-8fae37528692e63199f77bd1a20e5f72 ghc -v0 -- --numeric-version
  Environment Variables
    HIE_BIOS_GHC: /home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/bin/ghc-9.10.1
    HIE_BIOS_GHC_ARGS: -B/home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib
2025-05-12T10:31:21.661909Z | Info | Load cabal cradle using single file
2025-05-12T10:31:21.721706Z | Debug | cabal exec -v0 -- ghc --print-libdir
2025-05-12T10:31:21.832145Z | Debug | cabal exec -v0 -- ghc -package-env=- -ignore-dot-ghci -e Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)
2025-05-12T10:31:21.835054Z | Info | cabal --builddir=/home/tchoutri/.cache/hie-bios/dist-kitty-keyboard-protocol-1388541a692403313ef229670782cab8 v2-repl --with-compiler /home/tchoutri/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /home/tchoutri/.cache/hie-bios/ghc-pkg-8fae37528692e63199f77bd1a20e5f72 /home/tchoutri/Projects/kitty-keyboard-protocol/src/Kitty/KeyboardProtocol/State.hs
  Environment Variables
    HIE_BIOS_OUTPUT: /tmp/HIE_BIOS_OUTPUT129052-2
    HIE_BIOS_GHC: /home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/bin/ghc-9.10.1
    HIE_BIOS_GHC_ARGS: -B/home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib
2025-05-12T10:31:21.843928Z | Debug | Warning: this is a debug build of cabal-install with assertions enabled.
2025-05-12T10:31:21.848995Z | Debug | Configuration is affected by the following files:
2025-05-12T10:31:21.849181Z | Debug | - cabal.project
2025-05-12T10:31:21.849285Z | Debug | - cabal.project.freeze
2025-05-12T10:31:21.849335Z | Debug | - cabal.project.local
2025-05-12T10:31:21.861361Z | Debug | Build profile: -w ghc-9.10.1 -O1
2025-05-12T10:31:21.861508Z | Debug | In order, the following will be built (use -v for more details):
2025-05-12T10:31:21.861587Z | Debug |  - kitty-keyboard-protocol-0.1.0.0 (interactive) (lib) (first run)
2025-05-12T10:31:21.866302Z | Debug | Warning: this is a debug build of cabal-install with assertions enabled.
2025-05-12T10:31:21.893711Z | Debug | Preprocessing library for kitty-keyboard-protocol-0.1.0.0...
2025-05-12T10:31:21.923329Z | Debug | when making flags consistent: warning: [GHC-74335] [-Winconsistent-flags]
2025-05-12T10:31:21.923479Z | Debug |     Ignoring optimization flags since they are experimental for the byte-code interpreter. Pass -fno-unoptimized-core-for-interpreter to enable this feature.
2025-05-12T10:31:21.923564Z | Debug | 
2025-05-12T10:31:21.923640Z | Debug | GHCi, version 9.10.1: https://www.haskell.org/ghc/  :? for help
2025-05-12T10:31:22.072586Z | Debug | Loaded GHCi configuration from /home/tchoutri/Dotfiles/ghci/ghci
2025-05-12T10:31:22.080099Z | Debug | [1 of 2] Compiling Kitty.KeyboardProtocol.Keys
2025-05-12T10:31:22.101745Z | Debug | [2 of 2] Compiling Kitty.KeyboardProtocol.State
2025-05-12T10:31:22.102655Z | Debug | Ok, two modules loaded.
2025-05-12T10:31:22.103244Z | Debug | ghci> Leaving GHCi.
2025-05-12T10:31:22.145552Z | Debug | Session loading result: Left [CradleError {cradleErrorDependencies = ["kitty-keyboard-protocol.cabal","cabal.project","cabal.project.local"], cradleErrorExitCode = ExitSuccess, cradleErrorStderr = ["Failed to parse result of calling cabal","Failed command: cabal --builddir=/home/tchoutri/.cache/hie-bios/dist-kitty-keyboard-protocol-1388541a692403313ef229670782cab8 v2-repl --with-compiler /home/tchoutri/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /home/tchoutri/.cache/hie-bios/ghc-pkg-8fae37528692e63199f77bd1a20e5f72 /home/tchoutri/Projects/kitty-keyboard-protocol/src/Kitty/KeyboardProtocol/State.hs","Build profile: -w ghc-9.10.1 -O1\nIn order, the following will be built (use -v for more details):\n - kitty-keyboard-protocol-0.1.0.0 (interactive) (lib) (first run)\nPreprocessing library for kitty-keyboard-protocol-0.1.0.0...\nGHCi, version 9.10.1: https://www.haskell.org/ghc/  :? for help\nLoaded GHCi configuration from /home/tchoutri/Dotfiles/ghci/ghci\n[1 of 2] Compiling Kitty.KeyboardProtocol.Keys\n[2 of 2] Compiling Kitty.KeyboardProtocol.State\nOk, two modules loaded.\nghci> Leaving GHCi.\n","Warning: this is a debug build of cabal-install with assertions enabled.\nConfiguration is affected by the following files:\n- cabal.project\n- cabal.project.freeze\n- cabal.project.local\nWarning: this is a debug build of cabal-install with assertions enabled.\nwhen making flags consistent: warning: [GHC-74335] [-Winconsistent-flags]\n    Ignoring optimization flags since they are experimental for the byte-code interpreter. Pass -fno-unoptimized-core-for-interpreter to enable this feature.\n\n","","Process Environment:","HIE_BIOS_GHC: /home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/bin/ghc-9.10.1","HIE_BIOS_GHC_ARGS: -B/home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib"]}]
2025-05-12T10:31:22.146489Z | Info | updateFileDiagnostics published different from new diagnostics - file diagnostics: File:     /home/tchoutri/Projects/kitty-keyboard-protocol/src/Kitty/KeyboardProtocol/State.hs
Hidden:   no
Range:    1:1-2:1
Source:   cradle
Severity: DiagnosticSeverity_Error
Code:     <none>
Message: 
  Failed to parse result of calling cabal
  Failed command: cabal
  --builddir=/home/tchoutri/.cache/hie-bios/dist-kitty-keyboard-protocol-1388541a692403313ef229670782cab8
  v2-repl --with-compiler /home/tchoutri/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36
  --with-hc-pkg /home/tchoutri/.cache/hie-bios/ghc-pkg-8fae37528692e63199f77bd1a20e5f72
  /home/tchoutri/Projects/kitty-keyboard-protocol/src/Kitty/KeyboardProtocol/State.hs
  Build profile: -w ghc-9.10.1 -O1
  In order, the following will be built (use -v for more details):
  - kitty-keyboard-protocol-0.1.0.0 (interactive) (lib) (first run)
  Preprocessing library for kitty-keyboard-protocol-0.1.0.0...
  GHCi, version 9.10.1: https://www.haskell.org/ghc/ :? for help
  Loaded GHCi configuration from /home/tchoutri/Dotfiles/ghci/ghci
  [1 of 2] Compiling Kitty.KeyboardProtocol.Keys
  [2 of 2] Compiling Kitty.KeyboardProtocol.State
  Ok, two modules loaded.
  ghci> Leaving GHCi.

  Warning: this is a debug build of cabal-install with assertions enabled.
  Configuration is affected by the following files:
  - cabal.project
  - cabal.project.freeze
  - cabal.project.local
  Warning: this is a debug build of cabal-install with assertions enabled.
  when making flags consistent: warning: [GHC-74335] [-Winconsistent-flags]
  Ignoring optimization flags since they are experimental for the byte-code interpreter. Pass
  -fno-unoptimized-core-for-interpreter to enable this feature.



  Process Environment:
  HIE_BIOS_GHC: /home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/bin/ghc-9.10.1
  HIE_BIOS_GHC_ARGS: -B/home/tchoutri/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib
2025-05-12T10:31:22.147074Z | Debug | Finished: User TypeCheck Took: 3.99s
2025-05-12T10:31:22.147530Z | Debug | Finished: GetHie Took: 0.00s
2025-05-12T10:31:22.147973Z | Debug | Finished: GenerateCore Took: 0.00s
Files that failed:
 * /home/tchoutri/Projects/kitty-keyboard-protocol/src/Kitty/KeyboardProtocol/Keys.hs
 * /home/tchoutri/Projects/kitty-keyboard-protocol/src/Kitty/KeyboardProtocol/State.hs
 * /home/tchoutri/Projects/kitty-keyboard-protocol/test/Main.hs

Completed (0 files worked, 3 files failed)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by fendor**
Adds support for `cabal repl --with-repl`, see https://github.com/haskell/hie-bios/issues/467 and https://github.com/haskell/cabal/issues/9115 for context.

This tests whether HLS uncovers any errors already.

Closes #4590 and closes #3730

### CODE REVIEW

**Comment by fendor** [comment]
^ @tchoutri might be interesting for you

File: ghcide/session-loader/Development/IDE/Session.hs [hunk 1]
```diff
@@ -70,6 +70,7 @@ import qualified HIE.Bios                            as HieBios
 import           HIE.Bios.Environment                hiding (getCacheDir)
 import           HIE.Bios.Types                      hiding (Log)
 import qualified HIE.Bios.Types                      as HieBios
+import qualified HIE.Bios.Cradle.Utils               as HieBios
```
Comment (fendor) [inline ghcide/session-loader/Development/IDE/Session.hs]:
```suggestion
import qualified HIE.Bios.Cradle.Utils               as HieBios
import           HIE.Bios.Environment                hiding (getCacheDir)
import           HIE.Bios.Types                      hiding (Log)
import qualified HIE.Bios.Types                      as HieBios
```

**Review by VeryMilkyJoe — APPROVED** [review]
