### PR TITLE
Make adding missing constraint work in presence of 'forall' (fixes #1164)

### LINKED ISSUE #1164: Adding missing constraint to type signature is broken when "forall" is present
Reproducer

Reproduced with 
haskell-language-server version: 0.8.0.0 (GHC: 8.8.4) (PATH: /home/jhrcek/.local/bin/haskell-language-server) (GIT hash: bde552bcdc702b97c4fd0cd27b24db60b3daeb26)

NOTE: previously I've made this code action more robust by fixing the behavior when context is formatted over multiple lines (https://github.com/haskell/ghcide/pull/839). But it seems some more work is needed. I'll probably get to fixing this over the weekend.

### PR DESCRIPTION
**Pull request by jhrcek**
Fixes https://github.com/haskell/haskell-language-server/issues/1164

worksWithForall

### CODE REVIEW

File: ghcide/test/exe/Main.hs [hunk 1]
```diff
@@ -1993,6 +2015,10 @@ addFunctionConstraintTests = let
     "Add `Eq a` to the context of the type signature for `eq`"
     (missingConstraintSourceCode "")
     (missingConstraintSourceCode "Eq a => ")
+  , check
+    "Add `Eq a` to the context of the type signature for `eq`"
```
Comment (pepeiborra) [inline ghcide/test/exe/Main.hs:2019]:
```suggestion
    "Add `Eq a` to the context of the type signature for `eq` (forall)"
```

File: ghcide/test/exe/Main.hs [hunk 2]
```diff
@@ -2001,6 +2027,10 @@ addFunctionConstraintTests = let
     "Add `Eq c` to the context of the type signature for `eq`"
     (incompleteConstraintSourceCode2 "(Eq a, Eq b)")
     (incompleteConstraintSourceCode2 "(Eq a, Eq b, Eq c)")
+  , check 
+    "Add `Eq b` to the context of the type signature for `eq`"
```
Comment (pepeiborra) [inline ghcide/test/exe/Main.hs:2031]:
```suggestion
    "Add `Eq b` to the context of the type signature for `eq` (forall)"
```

**Review by pepeiborra — APPROVED** [review]
good catch, thanks!

File: ghcide/test/exe/Main.hs (hunk 1 above)
Comment (jhrcek) [reply ghcide/test/exe/Main.hs]: Unfortunately this is not name of test, but the name of code action which must match exactly, so I expect the tests to fail after this change..

**Comment by jhrcek** [comment]
Given my reply above @pepeiborra I hope you don't mind reverting your change.
If you want I can refactor the tests so that test description and code action names are separated.

File: ghcide/test/exe/Main.hs (hunk 1 above)
Comment (pepeiborra) [reply ghcide/test/exe/Main.hs:2019]: > Given my reply above @pepeiborra I hope you don't mind reverting your change.
> If you want I can refactor the tests so that test description and code action names are separated.

sure, but it would be good to find another way to avoid duplicating test names

**Comment by jhrcek** [comment]
Alright, I changed in the most obvious way by not reusing code action names for test description, instead adding separate description for each test.

File: ghcide/src/Development/IDE/GHC/Compat.hs [hunk 3]
```diff
@@ -283,3 +283,12 @@ pattern ExposePackage s a mr <- DynFlags.ExposePackage s a _ mr
 #else
 pattern ExposePackage s a mr = DynFlags.ExposePackage s a mr
 #endif
+
```
Comment (jhrcek) [inline ghcide/src/Development/IDE/GHC/Compat.hs:286]: Seems like `splitLHsForAllTy` no longer exists since ghc 8.10 and there's now just [splitLHsForAllTyInvis](https://hackage.haskell.org/package/ghc-8.10.1/docs/GHC-Hs-Types.html#v:splitLHsForAllTyInvis).
Is this way of handling this situation ok?
