### PR TITLE
Fix flaky test 

### LINKED ISSUE #2831: Test "add missing module (non workspace)" is very flaky
It consistently fails on CI for #2789 but I can't reproduce it locally. I'm disabling it for now.

### PR DESCRIPTION
**Pull request by pepeiborra**
"add missing modules (non workspace)" became flaky after the recent changes to snapshot VFS data.

The test calls `createDoc` to open a `module B imports A` where `A` does not exist, then waits for the missing module error and calls `createDoc` to open a `module A`. Importantly, both `B` and `A` live outside the workspace and thus are not subject to `FileWatched` notifications. 

Unfortunately, the test wasn't testing the right thing because `createDoc` sends a `FileWatched` notification right before sending a `DidOpen` notification! This was causing a race condition, where the `FileWatched` notification triggers a build that may or may not run the `FileExists ModuleA` key:
* If it does, then the key will resolve to `False` since `ModuleA` exists neither in the file system nor in VFS, and the test will fail since the key will not get rebuilt again (nothing dirties it).
* If the build gets aborted before it does, then the key will get computed in the next build (for the `DidOpen` notification) and will return true because the file now exists in VFS.

I imagine that the test was passing before since the VFS state would get updated concurrently, and the race condition would not get triggered in practice.

To fix the test, we simply tell `lsp-test` not to send `FileWatched` notifications.

I also found an old comment stating that "VFS existence is not enough, a file must exist in disk". This is clearly not true anymore, so I have deleted it.

Fixes #2831 

<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2835"></a>

### CODE REVIEW

**Review by wz1000 — APPROVED** [review]
Thanks for looking into this! I ran the testsuite a couple of times but could not reproduce this failure locally at all.

**Review by wz1000 — APPROVED** [review]

File: ghcide/test/exe/Main.hs [hunk 1]
```diff
@@ -421,16 +421,16 @@ diagnosticTests = testGroup "diagnostics"
       let contentA = T.unlines [ "module ModuleA where" ]
       _ <- createDoc "ModuleA.hs" "haskell" contentA
       expectDiagnostics [("ModuleB.hs", [])]
-  , ignoreTestBecause "Flaky #2831" $ testSessionWait "add missing module (non workspace)" $ do
+  , testSession' "add missing module (non workspace)" $ \tmpDir -> do
       -- need to canonicalize in Mac Os
```
Comment (michaelpj) [inline ghcide/test/exe/Main.hs:425]: dead comment

**Comment by michaelpj** [comment]
> To fix the test, we simply tell lsp-test not to send FileWatched notifications.

I'm confused, that doesn't look like what the change does? And I don't see the comment you mentioned being deleted?

**Comment by pepeiborra** [comment]
> I'm confused, that doesn't look like what the change does? And I don't see the comment you mentioned being deleted?

Fixed now, thanks for noticing this. I must have forgotten to `git push -f`

File: ghcide/test/exe/Main.hs [hunk 2]
```diff
@@ -421,9 +422,8 @@ diagnosticTests = testGroup "diagnostics"
       let contentA = T.unlines [ "module ModuleA where" ]
       _ <- createDoc "ModuleA.hs" "haskell" contentA
       expectDiagnostics [("ModuleB.hs", [])]
-  , ignoreTestBecause "Flaky #2831" $ testSessionWait "add missing module (non workspace)" $ do
-      -- need to canonicalize in Mac Os
-      tmpDir <- liftIO $ canonicalizePath =<< getTemporaryDirectory
+  , testCase "add missing module (non workspace)" $
+    withTempDir $ \tmpDir -> runInDir'' lspTestCapsNoFileWatches tmpDir "." "." [] $ do
```
Comment (michaelpj) [inline ghcide/test/exe/Main.hs:426]: This definitely deserves a comment, it's very non-obvious why we would run this with restricted capabilities (after all, it took lots of debugging and reasoning for you to figure out that we needed it!).

**Review by michaelpj — APPROVED** [review]
