### PR TITLE
Unify session loading using implicit-hie

### LINKED ISSUE #1782: HLS Uses Wrong GHC for Stack Builds
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 1.1.0.0 (GHC: 8.10.4) (PATH: /Users/emilypi/.ghcup/bin/haskell-language-server-wrapper-1.1.0) (GIT hash: f1c096927186a93d8e3ccd4fe8385cc1b070350b)
Tool versions found on the $PATH
cabal:		3.4.0.0
stack:		2.5.1
ghc:		8.8.4
```
Which OS do you use:

MacOS Big Sur

Which lsp-client do you use:
Emacs

Describe your project (alternative: link to the project):
All of `stack.yaml`, `cabal.project`, `*.cabal`. 

See: https://github.com/kadena-io/pact

Contents of `hie.yaml`:
NA

### Steps to reproduce
Manage a GHC in $PATH that does not match the existing GHC defined by the stack LTS in the `stack.yaml`.  

### Expected behaviour
When generating an implicit `hie.yaml`, if the Stack build is preferred, then HLS should not use $PATH GHC, but rather, defer to the GHC defined for the LTS. 

### Actual behaviour

See here: $PATH GHC is reported, but the stack build results in an implicit cradle for 8.8.3 (the GHC associated with the Stack lts) but the build is initiated with $PATH GHC, resulting in an out of sync build: 

```sh
Module "/Users/emilypi/kadena/pact/a" is loaded by Cradle: Cradle {cradleRootDir = "/Users/emilypi/kadena/pact", cradleOptsProg = CradleAction: Stack}
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper) Version 1.1.0.0, Git revision f1c096927186a93d8e3ccd4fe8385cc1b070350b (dirty) x86_64 ghc-8.10.4
Current directory: /Users/emilypi/kadena/pact
Operating system: darwin
Arguments: []
Cradle directory: /Users/emilypi/kadena/pact
Cradle type: Stack

Tool versions found on the $PATH
cabal:		3.4.0.0
stack:		2.5.1
ghc:		8.8.4


Consulting the cradle to get project GHC version...
Project GHC version: 8.8.3
haskell-language-server exe candidates: ["haskell-language-server-8.8.3","haskell-language-server-8.8","haskell-language-server"]
Launching haskell-language-server exe at:/Users/emilypi/.ghcup/bin/haskell-language-server-8.8.3
haskell-language-server version: 1.1.0.0 (GHC: 8.8.3) (PATH: /Users/emilypi/.ghcup/bin/haskell-language-server-8.8.3~1.1.0) (GIT hash: f1c096927186a93d8e3ccd4fe8385cc1b070350b)
 ghcide setup tester in /Users/emilypi/kadena/pact.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/4: Finding files to test in /Users/emilypi/kadena/pact
Found 154 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle
  ()

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
2021-04-30 15:03:36.660893 [ThreadId 150] INFO hls:	Consulting the cradle for "src/Pact/Repl.hs"
2021-04-30 15:03:36.661953 [ThreadId 150] WARNING hls:	No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for src/Pact/Repl.hs.
 Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie).
You should ignore this message, unless you see a 'Multi Cradle: No prefixes matched' error.
Output from setting up the cradle Cradle {cradleRootDir = "/Users/emilypi/kadena/pact", cradleOptsProg = CradleAction: Cabal}
> Build profile: -w ghc-8.8.4 -O0
> In order, the following will be built (use -v for more details):
>  - Boolean-0.2.4 (lib:Boolean) (requires build)
>  - Decimal-0.5.2 (lib) (requires build)
>  - NumInstances-1.4 (lib) (requires build)
>  - Only-0.1 (lib) (requires build)
>  - blaze-builder-0.4.2.1 (lib) (requires build)
... etc
```

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

<details>
<summary>
Debug output:
</summary>

```
λ P pact → λ git fix-modref-json → haskell-language-server-wrapper --debug
Module "/Users/emilypi/kadena/pact/a" is loaded by Cradle: Cradle {cradleRootDir = "/Users/emilypi/kadena/pact", cradleOptsProg = CradleAction: Stack}
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper) Version 1.1.0.0, Git revision f1c096927186a93d8e3ccd4fe8385cc1b070350b (dirty) x86_64 ghc-8.10.4
Current directory: /Users/emilypi/kadena/pact
Operating system: darwin
Arguments: ["--debug"]
Cradle directory: /Users/emilypi/kadena/pact
Cradle type: Stack

Tool versions found on the $PATH
cabal:		3.4.0.0
stack:		2.5.1
ghc:		8.8.4


Consulting the cradle to get project GHC version...
Project GHC version: 8.8.3
haskell-language-server exe candidates: ["haskell-language-server-8.8.3","haskell-language-server-8.8","haskell-language-server"]
Launching haskell-language-server exe at:/Users/emilypi/.ghcup/bin/haskell-language-server-8.8.3
haskell-language-server version: 1.1.0.0 (GHC: 8.8.3) (PATH: /Users/emilypi/.ghcup/bin/haskell-language-server-8.8.3~1.1.0) (GIT hash: f1c096927186a93d8e3ccd4fe8385cc1b070350b)
 ghcide setup tester in /Users/emilypi/kadena/pact.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/4: Finding files to test in /Users/emilypi/kadena/pact
Found 154 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle
  ()

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
2021-04-30 15:07:53.20436 [ThreadId 4] DEBUG hls:	Set files of interest to: [(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Types.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Types/Server.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/Blake2Spec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/TypesSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/SizeOf.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Native/Keysets.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Names.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Parser.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Native/SPV.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/HLint.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/PersistPactDb/Regression.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Native/Decrypt.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/executables/Repl.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/Analyze/Eval.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Repl/Lib.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/Setup.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/hspec-ghcjs.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/hspec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Native/Time.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Command.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/GasModel/Utils.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Hash.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/ExpParser.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Server/ApiServer.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/GasModel/GasModel.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Types/Languages.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/SchemeSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Version.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/executables/ReplGhcjs.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/AnalyzePropertiesSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Types/Shared.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Types/Crypto.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Parse/Invariant.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/GasModelSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Server/History/Persistence.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/ReplTools.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Exp.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Scheme.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Eval/Core.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Gas.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Types/Eval.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Guard.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/LegacySFunArray.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Native/Internal.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/PersistSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/Analyze/Gen.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Types/Types.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/API.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/Analyze/TimeGen.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/ParserSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Parse/Prop.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Persist/Pure.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Types/Capability.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Model/Graph.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/AnalyzeSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Util.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Purity.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Eval/Prop.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/GasModel/Types.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/ApiReq.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Term.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Crypto/Hash/Blake2Native.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/PersistPactDb.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Eval/Invariant.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Parse/Types.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/executables/Bench.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/executables/GasModel.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Main.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Typecheck.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/MockDb.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Gas.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Types/ECDSA.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Runtime/Typecheck.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Persist/MockPersist.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Server/Test.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Eval.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/RPC.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Runtime/Capabilities.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Continuation.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Check.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Logger.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Native/Db.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Errors.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Native/Capabilities.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Util.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/PactTestsSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Patterns.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Runtime.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/GoldenSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Server/PactService.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Types/Model.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Lang.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/RemoteVerifySpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Remote/Types.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/Analyze/Translate.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Repl.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Bench.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Types/SQLite.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Server/History/Service.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Persistence.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Eval.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Alloc.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Swagger.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Model/Text.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/KeysetSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Server/Server.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Parse.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Typechecker.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Compile.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Interpreter.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Remote/Client.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Native.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Types/Numerical.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/SPV.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/PactValue.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/ChainMeta.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Eval/Numerical.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Docgen.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Type.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Eval/Term.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Runtime/Utils.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Capability.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/ChainId.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/GasModel/GasTests.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Types/ObjUtil.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Gas/Table.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/PactContinuationSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Model.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Model/Dot.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/HistoryServiceSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/DocgenSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/SignatureSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Repl/Types.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Feature.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Codec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Persist/SQLite.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Pretty.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Server/API.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/PrenexNormalize.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/PactError.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Persist.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/ClientSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Native/Ops.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Model/Tags.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Info.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Translate.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Orphans.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Remote/Server.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Server/History/Types.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/tests/TypecheckSpec.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Parse.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Native.hs",OnDisk),(NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Perf.hs",OnDisk)]
2021-04-30 15:07:53.210207 [ThreadId 34] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/tests/RemoteVerifySpec.hs"
2021-04-30 15:07:53.210198 [ThreadId 30] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Parse/Prop.hs"
2021-04-30 15:07:53.21029 [ThreadId 33] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Parse.hs"
2021-04-30 15:07:53.210296 [ThreadId 35] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Remote/Server.hs"
2021-04-30 15:07:53.210302 [ThreadId 25] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Repl/Lib.hs"
2021-04-30 15:07:53.210316 [ThreadId 31] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/executables/Bench.hs"
2021-04-30 15:07:53.210329 [ThreadId 32] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Util.hs"
2021-04-30 15:07:53.210362 [ThreadId 34] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Server/ApiServer.hs"
2021-04-30 15:07:53.210413 [ThreadId 30] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Bench.hs"
2021-04-30 15:07:53.210456 [ThreadId 33] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/tests/ClientSpec.hs"
2021-04-30 15:07:53.210504 [ThreadId 35] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Docgen.hs"
2021-04-30 15:07:53.210549 [ThreadId 25] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/tests/PactTestsSpec.hs"
2021-04-30 15:07:53.210626 [ThreadId 31] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/PersistPactDb/Regression.hs"
2021-04-30 15:07:53.21066 [ThreadId 32] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Native/Capabilities.hs"
2021-04-30 15:07:53.210694 [ThreadId 34] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/GasModel/GasTests.hs"
2021-04-30 15:07:53.210724 [ThreadId 30] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/tests/AnalyzeSpec.hs"
2021-04-30 15:07:53.210824 [ThreadId 33] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/tests/ParserSpec.hs"
2021-04-30 15:07:53.21085 [ThreadId 25] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Native/Keysets.hs"
2021-04-30 15:07:53.210863 [ThreadId 35] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/tests/SignatureSpec.hs"
2021-04-30 15:07:53.210849 [ThreadId 31] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Repl/Types.hs"
2021-04-30 15:07:53.210926 [ThreadId 32] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/tests/TypesSpec.hs"
2021-04-30 15:07:53.210951 [ThreadId 34] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Translate.hs"
2021-04-30 15:07:53.211043 [ThreadId 33] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Orphans.hs"
2021-04-30 15:07:53.211287 [ThreadId 32] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Types/Crypto.hs"
2021-04-30 15:07:53.211439 [ThreadId 25] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Command.hs"
2021-04-30 15:07:53.211522 [ThreadId 31] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/ApiReq.hs"
2021-04-30 15:07:53.21155 [ThreadId 32] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Logger.hs"
2021-04-30 15:07:53.211608 [ThreadId 35] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Crypto/Hash/Blake2Native.hs"
2021-04-30 15:07:53.211959 [ThreadId 34] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Continuation.hs"
2021-04-30 15:07:53.211984 [ThreadId 32] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/HLint.hs"
2021-04-30 15:07:53.212008 [ThreadId 25] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/ReplTools.hs"
2021-04-30 15:07:53.212454 [ThreadId 25] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Gas.hs"
2021-04-30 15:07:53.212516 [ThreadId 35] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/LegacySFunArray.hs"
2021-04-30 15:07:53.212853 [ThreadId 35] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/tests/Analyze/Eval.hs"
2021-04-30 15:07:53.213147 [ThreadId 30] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Server/Server.hs"
2021-04-30 15:07:53.213434 [ThreadId 34] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Types/ObjUtil.hs"
2021-04-30 15:07:53.213655 [ThreadId 34] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Eval.hs"
2021-04-30 15:07:53.213682 [ThreadId 30] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Persist/SQLite.hs"
2021-04-30 15:07:53.213873 [ThreadId 34] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/executables/GasModel.hs"
2021-04-30 15:07:53.214041 [ThreadId 32] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Check.hs"
2021-04-30 15:07:53.214178 [ThreadId 25] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/executables/Repl.hs"
2021-04-30 15:07:53.21429 [ThreadId 32] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Type.hs"
2021-04-30 15:07:53.21442 [ThreadId 25] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Persistence.hs"
2021-04-30 15:07:53.214541 [ThreadId 32] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Server/History/Service.hs"
2021-04-30 15:07:53.214547 [ThreadId 30] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Remote/Types.hs"
2021-04-30 15:07:53.214775 [ThreadId 25] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/RPC.hs"
2021-04-30 15:07:53.214933 [ThreadId 30] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Lang.hs"
2021-04-30 15:07:53.215133 [ThreadId 25] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Feature.hs"
2021-04-30 15:07:53.215201 [ThreadId 35] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Types/SQLite.hs"
2021-04-30 15:07:53.215396 [ThreadId 34] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/API.hs"
2021-04-30 15:07:53.215614 [ThreadId 32] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Errors.hs"
2021-04-30 15:07:53.215644 [ThreadId 34] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/PactError.hs"
2021-04-30 15:07:53.215892 [ThreadId 33] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/ChainId.hs"
2021-04-30 15:07:53.216189 [ThreadId 33] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Parser.hs"
2021-04-30 15:07:53.216377 [ThreadId 32] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/tests/Blake2Spec.hs"
2021-04-30 15:07:53.216607 [ThreadId 32] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Server/PactService.hs"
2021-04-30 15:07:53.216999 [ThreadId 35] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/tests/DocgenSpec.hs"
2021-04-30 15:07:53.217048 [ThreadId 25] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/Runtime.hs"
2021-04-30 15:07:53.217514 [ThreadId 34] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Native/Ops.hs"
2021-04-30 15:07:53.217644 [ThreadId 30] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Types/Server.hs"
2021-04-30 15:07:53.217664 [ThreadId 35] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Server/API.hs"
2021-04-30 15:07:53.217676 [ThreadId 25] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Types/Languages.hs"
2021-04-30 15:07:53.217864 [ThreadId 33] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Alloc.hs"
2021-04-30 15:07:53.218092 [ThreadId 33] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Model/Tags.hs"
2021-04-30 15:07:53.2181 [ThreadId 34] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src-ghc/Pact/Main.hs"
2021-04-30 15:07:53.218334 [ThreadId 34] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Analyze/Remote/Client.hs"
2021-04-30 15:07:53.218941 [ThreadId 33] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Repl.hs"
2021-04-30 15:07:53.218951 [ThreadId 30] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/emilypi/kadena/pact/src/Pact/Types/ExpParser.hs"
2021-04-30 15:07:53.220101 [ThreadId 113] INFO hls:	Consulting the cradle for "tests/hspec.hs"
2021-04-30 15:07:53.220165 [ThreadId 113] WARNING hls:	No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for tests/hspec.hs.
 Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie).
You should ignore this message, unless you see a 'Multi Cradle: No prefixes matched' error.
Output from setting up the cradle Cradle {cradleRootDir = "/Users/emilypi/kadena/pact", cradleOptsProg = CradleAction: Cabal}
> Build profile: -w ghc-8.8.4 -O0
> In order, the following will be built (use -v for more details):
>  - Boolean-0.2.4 (lib:Boolean) (requires build)
>  - Decimal-0.5.2 (lib) (requires build)
```

### PR DESCRIPTION
**Pull request by fendor**
Make Wrapper and Session loader use the same logic to avoid
loading logic divergence.

Cleans up existing usages to use infrastructure in place.

Closes #1782

### CODE REVIEW

**Comment by fendor** [comment]
@emilypi Would you mind trying if this fixes your issue?

File: ghcide/session-loader/Development/IDE/Session.hs [hunk 1]
```diff
@@ -100,15 +98,17 @@ data CacheDirs = CacheDirs
   { hiCacheDir, hieCacheDir, oCacheDir :: Maybe FilePath}
 
 data SessionLoadingOptions = SessionLoadingOptions
-  { findCradle          :: FilePath -> IO (Maybe FilePath)
-  , loadCradle          :: FilePath -> IO (HieBios.Cradle Void)
+  { findCradle             :: FilePath -> IO (Maybe FilePath)
+  -- | Load the cradle with the given Config. If the config is 'Nothing', use the provided
+  -- project root directory to determine the 'Cradle' type.
```
Comment (pepeiborra) [inline ghcide/session-loader/Development/IDE/Session.hs:103]: This comment could be easier to understand. What does 'Config' mean in this context?

**Review by pepeiborra — COMMENTED** [review]
How do we know that this fixes the issue? It would be great to have a test

**Comment by fendor** [comment]
I think, we need end-to-end tests to truly prove the issue doesn't occur anymore. The issue was basically that Wrapper and HLS didn't use the same logic for loading a cradle, thus, came to different conclusions regarding the cradle type. As we now unified the logic behaviour, e.g. there is only a single occurence of `loadCradle` from `hie-bios` and `loadImplicitHieCradle` respectively, it should be fixed.

Do we have something resembling end-to-end tests?

**Comment by emilypi** [comment]
@fendor I can confirm this works, calling the executable with HEAD on your branch: 

```
λ athena pact → λ git fix-modref-json* → ../haskell-language-server/dist-newstyle/build/x86_64-linux/ghc-8.8.4/haskell-language-server-1.1.0.0/x/haskell-language-server-wrapper/noopt/build/haskell-language-server-wrapper/haskell-language-server-wrapper

Found "/home/tapas/haskell/pact/hie.yaml" for "/home/tapas/haskell/pact/a"
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper) Version 1.1.0.0, Git revision 73b472ae33b14d68c6071f01ce85d349ca8ac3ce (2196 commits) x86_64 ghc-8.8.4
Current directory: /home/tapas/haskell/pact
Operating system: linux
Arguments: []
Cradle directory: /home/tapas/haskell/pact
Cradle type: Cabal

Tool versions found on the $PATH
cabal:		3.4.0.0
stack:		2.5.1
ghc:		8.8.4


Consulting the cradle to get project GHC version...
Project GHC version: 8.8.4
haskell-language-server exe candidates: ["haskell-language-server-8.8.4","haskell-language-server-8.8","haskell-language-server"]
Launching haskell-language-server exe at:/home/tapas/.ghcup/bin/haskell-language-server-8.8.4
haskell-language-server version: 1.1.0.0 (GHC: 8.8.4) (PATH: /home/tapas/.ghcup/bin/haskell-language-server-8.8.4~1.1.0) (GIT hash: f1c096927186a93d8e3ccd4fe8385cc1b070350b)
 ghcide setup tester in /home/tapas/haskell/pact.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/4: Finding files to test in /home/tapas/haskell/pact
Found 154 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle
  (/home/tapas/haskell/pact/hie.yaml)

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
2021-04-30 19:02:11.935783385 [ThreadId 37] INFO hls:	Consulting the cradle for "src/Pact/Types/Native.hs"
Output from setting up the cradle Cradle {cradleRootDir = "/home/tapas/haskell/pact", cradleOptsProg = CradleAction: Cabal}
> Build profile: -w ghc-8.8.4 -O0
> In order, the following will be built (use -v for more details):
>  - pact-3.7 (lib) (ephemeral targets)
> Preprocessing library for pact-3.7..
2021-04-30 19:02:12.496481628 [ThreadId 37] INFO hls:	Using interface files cache dir: /home/tapas/.cache/ghcide/pact-3.7-inplace-64068f8443af49203e4e0b3f9e4d9e46a17947f8
2021-04-30 19:02:12.496959855 [ThreadId 37] INFO hls:	Making new HscEnv[pact-3.7-inplace]
2021-04-30 19:02:12.819720384 [ThreadId 180] INFO hls:	Consulting the cradle for "tests/TypesSpec.hs"
Output from setting up the cradle Cradle {cradleRootDir = "/home/tapas/haskell/pact", cradleOptsProg = CradleAction: Cabal}
^C2021-04-30 19:02:12.862796969 [ThreadId 190] INFO hls:	Consulting the cradle for "tests/hspec.hs"
Output from setting up the cradle Cradle {cradleRootDir = "/home/tapas/haskell/pact", cradleOptsProg = CradleAction: Cabal}
haskell-language-server-wrapper: waitForProcess: does not exist (No child processes)
```

File: ghcide/session-loader/Development/IDE/Session.hs (hunk 1 above)
Comment (Ailrun) [reply ghcide/session-loader/Development/IDE/Session.hs:103]: That would be easier to read IMO

**Comment by fendor** [comment]
Added a test as suggested by @jneira 

Implements new major mode `BiosMode` that prints the cradle type and could be expanded in the future for more `hie-bios` commands.

I had troubles running the tests locally, let's see what CI says.

**Comment by fendor** [comment]
As per usual, you spend more time on trying to write tests than actually solving the issue.

**Review by jneira — APPROVED** [review]
LGTM, great job @fendor, as usual
I hope the new cli option will be helpful beyond this concrete issue.
